### ISSUE TITLE
RELAX Q

### ISSUE THREAD

**Issue by vinjlynch** [veg/hyphy#1012]
Hi All,

I don't have a question, not an issue. Is there a way to have RELAX automatically define foreground and background lineages? Something akin to what GA-Branch and aBSREL do?

Thanks
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

You mean to search for lineages that "maximally" separate in terms of selective constraints, or best fit the data? Not at the moment, although one could always just bolt GA search on top of the branch partition; that would take some time however!

You can do a *very* crude _post hoc_ partitioning with the current approach by fitting using branch level `k` parameters from the `general descriptive` model and partitioning those estimates into groups by value.

What are you thinking you might use this for?

Best,
Sergei

**Comment by vinjlynch** [comment]
Hey Sergei,

Thanks for the quick reply! I think I mean best fit the data.

So I have a dataset of 119 PGR genes from placental mammals with lots of primates and tested for an episode of relaxation in the stem-lineage of humans (we also include Neaderthal and Denisova); k<1 was significant. Then we tested other primate clades (apes, Colobine monkeys, Cercopithicine monkeys, Old World monkeys, New World monkeys, etc.) to determine if the k<1 in the human-lineage was restricted to that lineage, or reflected a longer term trend of relaxation; most primates have k<1. But this does seem a very ad hoc approach, and maybe not statistically justifiable.


Best,
Vinny


Vincent J. Lynch, Ph.D.
Assistant Professor
Department of Biological Sciences
University at Buffalo, SUNY
551 Cooke Hall
Buffalo NY, 14260

vjlynch@buffalo.edu<mailto:vjlynch@chicago.edu>

"There is a grandeur in this view of life, with its several powers,
having been originally breathed into a few forms or into one; and that
whilst this planet has gone on cycling according to the fixed laws of
gravity, from so simple a beginning endless forms most beautiful and most
wonderful have been, and are being, evolved." -C. Darwin, 1859

On Aug 30, 2019, at 10:33 AM, Sergei Pond <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @vinjlynch<https://github.com/vinjlynch>,

You mean to search for lineages that "maximally" separate in terms of selective constraints, or best fit the data? Not at the moment, although one could always just bolt GA search on top of the branch partition; that would take some time however!

You can do a very crude post hoc partitioning with the current approach by fitting using branch level k parameters from the general descriptive model and partitioning those estimates into groups by value.

What are you thinking you might use this for?

Best,
Sergei

**Comment by spond** [comment]
Dear Vinny,

So you basically want to see how far back in the primate clade you can go and still maintain `k<1`? You can definitely do a series of individual hypothesis tests, where you consider different sets of branches as test. The issue arises because this procedure is a type of `HARKing`, or hypothesizing after the result is known ([Andrew Gelman](https://statmodeling.stat.columbia.edu/2016/12/15/hark-hark-p-value-heavens-gate-sings/) has written about at length). 

One way to think about it in terms of what would be the multiple hypothesis test correct that is appropriate here? Even if you do a single additional hypothesis test **after** seeing the data, e.g. by changing the set of branches that is being used at `test`, one could argue that the suitable correction would be for all the other hypotheses in the same class that you didn't conduct: i.e. all **possible** partitions of tree branches into groups, which of course is combinatorial. In reality you don't have to be this drastic, but if you see anything but very **low** p-values (e.g. <<0.0001) from additional tests, it probably is not statistically sound.

I think what you could do instead is test a limited number of hypotheses in the general descriptive framework, where *for each* branch, you consider `k=1` vs `k` unrestricted and identify branches that are significantly deviant from background (you need to correct for the # of hypotheses == number of tree branches).

HTH,
Sergei

**Comment by vinjlynch** [comment]
Hi Sergei,

Thanks the info! I think the approach you describe makes sense, and we do have an a priori hypothesis for why these primates are probably different so we picked the location of our fishing hole for a good reason!

Best,
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

Sounds good. The `RELAX.bf` file needs to be modified a bit to do this test; I can put it on (https://github.com/veg/hyphy-analyses)[hyphy-analyses] repo if you want.

Best,
Sergei

**Comment by vinjlynch** [comment]
That would be great!

**Comment by spond** [comment]
Dear @vinjlynch,

Take a look at https://github.com/veg/hyphy-analyses/tree/master/RELAX-scan 

Let me know what it does on your data or if you find some bugs/missing features.

Best,
Sergei

**Comment by vinjlynch** [comment]
Hi Sergei,

Thanks, this looks perfect. Which versions of HyPhy are compatible?

Best,
Vinny

**Comment by spond** [comment]
Dear @vinjlynch,

This script requires the _bleeding edge_ `dev` branch (see the README for https://github.com/veg/hyphy-analyses/)

Best,
Sergei

**Comment by juliayork** [comment]
I am trying to do this scan analysis, and it is asking me to specify branches. Am I wrong in thinking this scan method does not require branch specification?

**Comment by spond** [comment]
Dear @juliayork,

There should be no branch requirements for this analysis. Can you please paste in what you see in the terminal, starting with the command that you use to call RELAX scan

Best,
Sergei

**Comment by juliayork** [comment]
`hyphy RELAX.bf --alignment /path/to/alignmentandtree.txt`

gives me:

Analysis Description
--------------------
RELAX (a random effects test of selection relaxation) uses a random
effects branch-site model framework to test whether a set of 'Test'
branches evolves under relaxed selection relative to a set of
'Reference' branches (R), as measured by the relaxation parameter (K).
Version 2.1 adds a check for stability in K estimates to try to mitigate
convergence problems. Version 3 provides support for >2 branch sets.
Version 3.1 adds LHC + Nedler-Mead initial fit phase and keyword support

- __Requirements__: in-frame codon alignment and a phylogenetic tree, with at least two
groups of branches defined using the {} notation (one group can be
defined as all unlabeled branches)

- __Citation__: RELAX: Detecting Relaxed Selection in a Phylogenetic Framework (2015).
Mol Biol Evol 32 (3): 820-832

- __Written by__: Sergei L Kosakovsky Pond, Ben Murrell, Steven Weaver and Temple iGEM /
UCSD viral evolution group

- __Contact Information__: spond@temple.edu

- __Analysis Version__: 3.1


>code –> Universal
>Loaded a multiple sequence alignment with **24** sequences, **852** codons, and **1** partitions from `/path/to/alignmentandtree.txt`
Error:
RELAX requires at least one designated set of branches in the tree. in call to assert(wgagfTcd.option_count>=2, error_msg);

Function call stack
1 :  assert(wgagfTcd.option_count>=2, error_msg);

-------
2 :  ExecuteCommands("assert (`statement`, error_msg)", /path/to/res/TemplateBatchFiles/libv3/);
-------
3 :  [namespace = wgagfTcd] io.CheckAssertion("`&option_count` >= 2","RELAX requires at least one designated set of branches in the tree.");
-------
4 :  [namespace = relax] selected_branches=Call(settings[utility.getGlobalValue("terms.settings.branch_selector")],partitions_and_trees);
-------
5 :  [namespace = relax] load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});
-------
6 :  namespace

Step 0.LoadFunctionLibrary("modules/shared-load-file.bf", /path/to/hyphy/);

Step 1.load_file({utility.getGlobalValue("terms.prefix"):"relax",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"relax.select_branches"}});

Step 2.LoadFunctionLibrary("modules/grid_compute.ibf", /path/to/hyphy/);;
-------

Check errors.log for execution error details.

**Comment by juliayork** [comment]
I guess what I am trying to do is generate a plot like Wertheim et al., 2015 Figure 6, much like #1034 

The issues I've run into:
1) the general descriptive K changed quite a bit for each node if I ran the full analysis on the same data but with different branches specified so I thought this scan method might be a better descriptive tool

2) the general descriptive K doesn't make a lot of sense in regard to my results. For example, I got significant relaxation in one result, but the K general descriptive parameter for the test branch is around 8 and the K for the reference branches are all <1. Is this similar to #559? In which case, perhaps plotting the descriptive K would be unhelpful in understanding the data

3) I'm having difficulty transferring node labels between my RELAX output and visualization programs. For example, if my test node is Node17, then I go to plot my K values onto the tree using something like phytools, the node phytools thinks is 17 is completely different node. Is there any easy way to plot values from JSON output to a tree? Maybe this is the reason values are so different in the first part of this post? Am I just comparing different nodes in this case? 

Any help would be much appreciated.

**Comment by skaul31** [comment]
> I guess what I am trying to do is generate a plot like Wertheim et al., 2015 Figure 6, much like #1034
> 
> The issues I've run into:
> 
> 1. the general descriptive K changed quite a bit for each node if I ran the full analysis on the same data but with different branches specified so I thought this scan method might be a better descriptive tool
> 2. the general descriptive K doesn't make a lot of sense in regard to my results. For example, I got significant relaxation in one result, but the K general descriptive parameter for the test branch is around 8 and the K for the reference branches are all <1. Is this similar to [Interpreting results from RELAX #559](https://github.com/veg/hyphy/issues/559)? In which case, perhaps plotting the descriptive K would be unhelpful in understanding the data
> 3. I'm having difficulty transferring node labels between my RELAX output and visualization programs. For example, if my test node is Node17, then I go to plot my K values onto the tree using something like phytools, the node phytools thinks is 17 is completely different node. Is there any easy way to plot values from JSON output to a tree? Maybe this is the reason values are so different in the first part of this post? Am I just comparing different nodes in this case?
> 
> Any help would be much appreciated.

To your last point about plotting a figure similar to Fig 6 in the Wertheim et al., 2015 paper, what I have found is that visualization programs like phytools and ggtree label nodes differently than HyPhy and hence the node labelling does not match when trying to map K values to generate the figure. The way that I overcame the issue is very cumbersome but its the only way I was able to plot the figure I wanted (I am using ggtree and also plotting a figure like Fig 6 in the Wertheim paper). Basically, I use the tree from the output RELAX json files and input it into iTOL (https://itol.embl.de/upload.cgi) so I can visualize where the nodes are and what the labelling of each node is. I then compare this to the node labelling that ggtree provides and basically relabel the nodes in the tree from the output json file to be congruent with ggtree's labelling. This way when I generate my dataframes the node labels are the same as ggtree's and also match the K values generated through RELAX. I know this is an extremely manual and time consuming way to do it but this was the only way I was able to plot my data. Hope this helps (if you are still looking for help since I am commenting 2 years later haha)! 

On another note, if you were able to find a better way to make the plots I would love to learn about it. Thanks!

**Comment by spond** [comment]
Dear @skaul31,

The figure in the paper was generated with a script that I wrote to produce PostScript for trees (no longer maintained). I have developed a notebook (https://observablehq.com/@spond/plotting-relax-k-values-on-branches-of-the-tree) which allows you to load RELAX JSON and visualize the distribution of `k` on tree branches

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1018513/205467424-db83a8cb-bcfc-45f8-9b80-f8755eae5006.png">

It also generates an annotated Newick string that you may have an easier time working with

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1018513/205467447-9ddf9035-9a1c-4fd3-89fa-7e6de08ff136.png">

Best,
Sergei
