### ISSUE TITLE
w = infinite, namely ds=0. Is this situation reliable ?

### ISSUE THREAD

**Issue by ybdong919** [veg/hyphy#1018]
The analysis found some codon site with w= infinite, ds=0. 
Is this meaningful or reliable? 
For PAML, this situation is not reliable. What is about FEL of Datamonkey?

**Comment by spond** [comment]
Dear @ybdong919,

You should **never** look at parameter estimates alone. If the `p-value` or `posterior probability` provides strong evidence for deviation from neutrality, you can interpret it as evidence that the site is positively/negatively selected. 

The situation is not comparable to `PAML`, because **unlike** PAML, FEL allows synonymous rates to vary from site to site. 

Best,
Sergei
