### ISSUE TITLE
interpreting GARD results

### ISSUE THREAD

**Issue by jayoung** [veg/hyphy#1022]
hi there,

I'm confused about how to interpret a GARD results I have, and I'm hoping you can help me understand what's going on. I ran GARD on the datamonkey site using the general discrete model and 3 rate classes on a codon alignment.

At first glance, it looks like there's recombination in my alignment, with two segments (reading the summary statement).  But if I look at the deltaAIC of the one-topology-one-rate model versus the two-topology model, it's barely different (deltaAIC=1.63, which I think says the two-topology model is 2.2x better).   The big improvement GARD sees is that the two-topology model is much much better than the one-topology-two-rate model (I'm looking in the topological incongruity report).     

Somehow the AIC of the one-tree-two-rate model is way worse than that of the one-tree-one-rate model, which doesn't make much sense to me.   I wonder if the algorithm somehow got stuck on a local optimum? 

Intuitively, if there is true recombination, I'd want to see that the two-topology model being better than BOTH the one-topology model AND the two-topology-two-rate models.   

Does that make sense?   I'm not sure if I should worry about recombination in this alignment or not.

I'll attach the json results file and the input alignment.

thanks in advance for any advice you can give. all the best,

Janet Young

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

------------------------------------------------------------------- 

[TMCC_passeriformes.fas_aln1_NT.fa.treeorder.nonRedundant.withoutZosterops.noStops_GARDresult.json.txt](https://github.com/veg/hyphy/files/3628856/TMCC_passeriformes.fas_aln1_NT.fa.treeorder.nonRedundant.withoutZosterops.noStops_GARDresult.json.txt)

[TMCC_passeriformes.fas_aln1_NT.fa.treeorder.nonRedundant.withoutZosterops.noStops.degapcodon.fa.txt](https://github.com/veg/hyphy/files/3628859/TMCC_passeriformes.fas_aln1_NT.fa.treeorder.nonRedundant.withoutZosterops.noStops.degapcodon.fa.txt)

**Comment by spond** [comment]
Dear @jayoung,

Your intuition is correct in that the small &Delta;AIC is not terribly persuasive. 

The one-tree two-rate model is a bit of a straw-man: you estimates two sets of branch lengths (i.e. many more than one parameter) from two partitions using the same topology and compare it to the model with one tree and one set of branch lengths. Because of the many additional parameters, you rarely expect to find that the one-tree two-rate model will do better or even be close to the one-tree one-rate model. If recombination is present, then you are fitting the wrong topology, and having separate branch lengths does not help you. If recombination is absent, then unless you have very strong spatial rate variability (e.g. heterotachy that affects one part of the gene), then you expect the extra set of branch length parameters to not be terribly useful.

But my interpretation of your dataset is that there is **weak** evidence for recombination, both based on &Delta;AIC and on not terribly impressive SH-like p-values. 

Best,
Sergei

**Comment by jayoung** [comment]
Thanks, Sergei - that is very helpful.   

It was also interesting to me that when I ran the alignment with one additional sequence, there was not any hint of recombination, but after removing that sequence (that I suspect contains some errors) I start to see this weak evidence. The borderline cases are always going to be tricky, I'm sure.

The whole recombination test is philosophically challenging when our motivation is to use it to say "we're justified in doing positive selection analysis on the entire alignment".  Results are usually convincing when we DO see recombination, but when we don't see it, or see weak evidence, it's hard to tell whether it's truly not there, or just hard to detect. The classic problem of "absence of evidence" versus "evidence for absence".  Luckily this particular alignment is probably not one we will publish on anyway!

all the best,

Janet
