### ISSUE TITLE
Different results (FUBAR+MEME) and BUSTED

### ISSUE THREAD

**Issue by gubrins** [veg/hyphy#1031]
Hello,
First of all, I want to thank you for allowing us to use the datamonkey server, it is really useful for my research!
I'm working on mitogenomes and I was running a BUSTED analysis (exploratory), FUBAR and MEME tests and I was quite surprised when I got my results back. 
In MEME I have all the significant genes that I got with FUBAR plus some others (I understand that FUBAR is just looking for pervasive selection, so the new genes in MEME are due to episodic positive selection) but when I checked the results from BUSTED I was quite surprised: all the genes that were significant for BUSTED were not for FUBAR and the other way around. 
I understand that I can't use BUSTED for detecting positive selection in individual sites, but if BUSTED got significant results in one or more genes is because some branch or site was under episodic or pervasive selection and I was expecting them to be the same genes as I got previously. What am I missing? 

Regards,
Gabriel

**Comment by gubrins** [comment]
Heys,
I'm still with the same doubt, I don't fully understand why do I get these opposite results between MEME and BUSTED. If BUSTED is looking for natural selection at the gene level and MEME at the site level, how is that both methods are reporting different genes?

**Comment by spond** [comment]
Dear @gubrins,

How large are your alignments? Complete disagreement is unusual. Can you provide an example or two for me to look at?

Best,
Sergei

**Comment by gubrins** [comment]
Dear Sergei,
thanks for your answer. The alignment's length is different depending on the gene i'm using. I'm working with all the mitochondrial genes. What should I provide you? The JSON files?

Regards,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

The JSON files and the underlying alignments with trees (so I can troubleshoot).

Best,
Sergei

**Comment by gubrins** [comment]
Dear Sergei,
Here are the files.

Regards


[ATP8-out.zip](https://github.com/veg/hyphy/files/3941734/ATP8-out.zip)

**Comment by spond** [comment]
Dear @gubrins,

I think there are two contributing factors here

1. Only a few sites are under selection (MEME finds 4, FUBAR and FEL find 1). In our BUSTED paper we noted that BUSTED needs a relatively high fraction to be under selection (5-10%). 

2. Your alignment is very short (*52*) codons. This may create "small-sample" issues, where BUSTED is trying to fit a relatively overparameterized model to a small number of sites. You can experiment with the command line version of BUSTED to tune the number of rates (`3` is the default on Datamonkey, which seems to work well for most applications). For example, if you run

```
hyphy busted --alignment ~/Downloads/ATP8-out/ATP8-out.fas \
--srv Yes --code Vertebrate-mtDNA --rates 2 --syn-rates 2 --starting-points 10
```

(run `hyphy busted --help` for a list of options), you get something like what I have pasted below. There's simply not enough signal for the mixture model in BUSTED to "peel off" the selected sites component. 

Best,
Sergei


----

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -6169.64, AIC-c = 12639.99 (144 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.3526

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -5985.38, AIC-c = 12282.39 (149 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.001     |   57.030    |                                   |
|         Neutral evolution         |     1.000     |   42.970    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.160               |    19.459     |                                   |
|               1.203               |    80.541     |                                   |


### No evidence for episodic diversifying positive selection under the unconstrained model, skipping constrained model fitting
----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.5000**.

**Comment by gubrins** [comment]
Dear Sergei,

Thank you very much for your useful comments, I appreciate them a lot! I also thought that MEME would have more power of resolution, but your second point it's also really interesting.
I was also reanalyzing the data because I observed some extrange patterns and now it looks way better. However, there is still one gene that appears to be significant for BUSTED but not for MEME and it's larger (606 sites). I attach it here, just in case you have time to check it.

Again, thank you very much!!

[ND5-out.zip](https://github.com/veg/hyphy/files/3953216/ND5-out.zip)

**Comment by gubrins** [comment]
Dear Sergei,

Thank you very much for your answer!! It helped me a lot and everything is much more clear!
I hope I don't have to bother you again.

Regards,
Gabriel

**Comment by spond** [comment]
Dear @gubrins,

For your ND-5 file (BUSTED yes, MEME no), the difference was due to modeling synonymous rate variation (SRV). MEME does it, and BUSTED (classic version) does not. If you allow SRV in BUSTED, the results agree.

Best,
Sergei

```
hyphy busted --alignment /Users/sergei/Downloads/ND5-out/ND5-out.fas --code Vertebrate-mtDNA --srv Yes
```

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -43238.18, AIC-c = 86783.54 (153 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   54.979    |                                   |
|        Negative selection         |     0.066     |   44.017    |                                   |
|      Diversifying selection       |     1.046     |    1.004    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.293               |    18.124     |                                   |
|               0.801               |    65.596     |                                   |
|               2.588               |    16.279     |                                   |


### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -43238.20, AIC-c = 86781.56 (152 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   55.756    |                                   |
|        Negative selection         |     0.067     |   43.219    |                                   |
|         Neutral evolution         |     1.000     |    1.024    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.292               |    18.067     |                                   |
|               0.800               |    65.564     |                                   |
|               2.580               |    16.370     |                                   |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.4927**.
