### ISSUE TITLE
Ancestral state in output

### ISSUE THREAD

**Issue by erikenbody** [veg/hyphy#1038]
Hi there,

I am running FADE on a large dataset. It's great, thank you!

Is there any way to extract the ancestral state for all of the nodes for a single position? It doesn't look like it is in the default output, but I was wondering if there was a way to do this as it must be computed as part of the analysis.

Thank you!

Erik

**Comment by spond** [comment]
Dear @erikenbody,

Ancestral states are computed as a part of the FADE analysis (please use the `dev` branch, because v2.5 release contained a buggy version of FADE), and site compositions and substitution histories are written to the JSON under keys `['site annotations']['site annotations']`.

However, the code does not store the identity of individual ancestral states. That would not be too hard to include; what format would you find useful?

Something like ?
```
{
"tree" : "((a,b)N1, (c,d)N2..."
"node names" : {'N1','N2'...
"ancestral states" : 
 [
    ['A','A' ...], // site 1
    ['D','A' ...], // site 2
    ...
 ]
}
```

Best,
Sergei

**Comment by erikenbody** [comment]
Hey Sergei,

Thanks so much for the quick followup and for offering to assist this. What you describe makes sense to me - mostly I am looking for something that I can use to generate visuals for the small number of sites that are significant (which can be done by parsing what you sent), as a sort of proof of concept and to compare to other methods I've used for ancestral state reconstruction per site. 

Thanks for the tip on the devel branch - I will re-run with that branch now. 

Thank you!

Erik

**Comment by spond** [comment]
Dear @erikenbody,

@stephenshank has implemented something *like* this already for a different project. He's currently on vacation, returning next week at which point he should be able to circle back to you.

Best,
Sergei

![tree_and_sites](https://user-images.githubusercontent.com/1018513/67720894-99688b00-f9ab-11e9-8f74-483d620d78f5.png)

**Comment by erikenbody** [comment]
That sounds and looks great! Looking forward to hearing more. We've cobbled together something similar, but not nearly as data-rich as this. 

Erik

**Comment by erikenbody** [comment]
Hey Sergei,

I wanted to followup on your point to run the devel version of FADE. I'm glad you suggested this, as the results differ considerably if I compare the bayes factor calculation for running with my dataset on 2.5.2 (from devel branch) or 2.5.0:

![compare_plot_2 5 2_2 5 0](https://user-images.githubusercontent.com/12717495/69128170-0f907700-0aac-11ea-8adb-27dd08f7b8c1.png)

It is particularly noticeable at a site that I expected to see listed no longer has a high bias in 2.5.2, although the substitutions have been inferred the same:

HYPHY version | bias | rate | prob.bias | composition | substitutions | bayes.factor
-- | -- | -- | -- | -- | -- | --
2.5.0 | 34.59 | 0.24 | 1 | F815,Y356 | F->Y(11), Y->F(7) | 235681.99
2.5.2 | 0.54 | 2.8 | 0.92 | F815,Y356 | F->Y(11), Y->F(7) | 0.92

I realize the method is still in development and the change was likely an improvement, but given the direction and magnitude of the difference between versions, I wanted to ask if this was as you might expect in the update. 

Thank you!

Erik

**Comment by spond** [comment]
Dear Erik,

The implementation in 2.5.0 has a bug and its results are not to be considered valid. The substitution models for the biased case were not being correctly populated in some cases. Some earlier implementations of FADE were correct, but the port to 2.5.0 introduced a bug. Thankfully FADE has not yet been published, so I will claim the experimental "exception" clause here. For your specific site, because you have bidirectional evolution (Y<->F), the results from 2.5.2 make a lot more sense. 

I have performed extensive simulation validation of the version in 2.5.2 and the model performs well. 

Best,
Sergei

**Comment by erikenbody** [comment]
Hey Sergei,

Thanks so much for the detailed response, that all makes sense and is comforting to know. 

I'd still love to be able to pull out the node states from the output, but it is not critical. If it is useful to leave this issue active that I can, but feel free to close this otherwise.

Thanks!
Erik
