### ISSUE TITLE
Internal error when running the fel method of hyphy

### ISSUE THREAD

**Issue by hongzhonglu** [veg/hyphy#1040]
Dear manager,
Today I run the followed command line:
**hyphy fel --alignment /Users/luho/Documents/GitHub/proteinER/measuring_dNdS/OG5327_aligned_codon.fasta --tree /Users/luho/Documents/GitHub/proteinER/measuring_dNdS/OG5327_aa_aligned_trim2 --srv No --pvalue 0.1**
The followed error occured:
**Internal error 
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:fel.site_tree.Node108.alpha:=1*5.09922070159572 must be in [0,10000]. Current value = 0.7626503610231493.**
Can you help to find the reason for this error?
Thanks in advance!

**Comment by spond** [comment]
Dear @hongzhonglu,

Could you send `Users/luho/Documents/GitHub/proteinER/measuring_dNdS/HRH1_aligned_codon.fasta` and  `/Users/luho/Documents/GitHub/proteinER/measuring_dNdS/RAxML_bestTree.HRH1_tree` files to me by email (spond) at (temple dot edu)?

I am not 100% sure what is causing the problem.

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear Sergei,
Great thanks for your help!
I am sorry that the file i used /Users/luho/Documents/GitHub/proteinER/measuring_dNdS/OG5327_aligned_codon.fasta /Users/luho/Documents/GitHub/proteinER/measuring_dNdS/OG5327_aa_aligned_trim2.tre 
I have send the two file into your email.

**Comment by spond** [comment]
Dear @hongzhonglu,

Great. I received the files, and will attempt to replicate the issue.

Best,
Sergei

**Comment by hongzhonglu** [comment]
Dear @spond,
Have you found the time to test it?

Best,
Hongzhong

**Comment by spond** [comment]
Dear Hongzhong,

I have been able to replicate the issue, working on a fix.
Thanks for your patience.

Best,
Sergei

**Comment by spond** [comment]
Dear @hongzhonglu,

Thanks for letting me know. The letter `Y` should not matter in this context, but I will check.

Best,
Sergei

**Comment by jteisher** [comment]
Hello,

I am not sure if this is helpful, and if you'd like me to make a separate issue for it I'd be happy to, but I received a very similar error message while running meme with the command line. Mine reads:

**Error:
Internal error
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:meme.site_tree_bsrel.Bathycoccus_prasinos_XM_007513742.beta_2:=5170.264979813962*3.439134096962391 must be in [0,0]. Current value = 0.**

The test dataset (lysin.fna) ran with meme using this setup without problems. 

Best,
Jordan

**Comment by spond** [comment]
Dear @jteisher,

This error usually occurs when the sequences are very divergent or possibly misaligned (not always, but most of the time). Can you check to make sure that that's not the case in your situation? You can run your alignment through SLAC or FUBAR and look at the tree length that's reported by either analysis. If its in 100s or 1000s, then the sequences are either too divergent or there is some issue with sequence alignment

Best,
Sergei

**Comment by spond** [comment]
Dear @hongzhonglu,

The issue should (finally!) be resolved with the commit to the `develop` branch. 

Best,
Sergei

**Comment by hongzhonglu** [comment]
@spond Thanks so much for your help!
Best regards,
Hongzhong

**Comment by jteisher** [comment]
@spond Thank you very much for the suggestion. When I ran FUBAR it reported a tree length of 71. However, the tree has 1612 sequences of a relatively short (622 codons) gene from a wide phylogenetic range, so I don't know that the alignment isn't the problem. Is the fix you applied relevant to this error message in MEME as well?

**Comment by spond** [comment]
Dear @jteisher,

The fix is broadly applicable, but it does not address the question of "overly" long trees. Having very long branches induces a degree of numerical instability in likelihood calculations that I have not been able to fully address. Because such situations point to a more fundamental underlying problem of saturated data, throwing error in this context is not entirely unreasonable.

Best,
Sergei
