### ISSUE TITLE
correlation between number of seqs in alignment and number of sites under selection with FUBAR?

### ISSUE THREAD

**Issue by jhcepas** [veg/hyphy#1059]
Hi there! 
thanks for developing such an useful software. 

We have recently noticed that, for a gene family of 15-20 seqs, the number of sites under selection inferred by FUBAR varies a lot (from just 3 to more than 100 sites) by just adding/removing 3 or 4 sequences from the alignment. 

at this point we wonder whether there is any known effect or correlation between number of sequences in the original alignment and the number of sites under selection. 
thanks!

**Comment by spond** [comment]
Dear @jhcepas,

I think what you are mentioning is an effect we (and others) have reported at. In our [MEME paper](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002764)

```
Effect of sequence sampling

Although a previous analysis of  vertebrate rhodopsin sequences found no sites under selection
at posterior probability  [18], the same authors found 7 selected sites in the subset of  
squirrelfish sequences, and 2 selected sites when the subset of  fish sequences was analyzed.
These results run counter to the expectation that more data should provide greater power to 
detect selection. MEME, on the other hand, detects more selected sites when more sequences
are included. One site is identified in the squirrelfish alignment,  in the fish alignment, and  in the complete rhodopsin alignment. All but  sites detected in the subset alignments are also identified in the full alignment (Table S20). Allowing  to vary over branches at least partially mitigates the 
pathology of constant- models which effectively rely on an average  for inferring selection. A 
similar pattern is seen in the analysis of the influenza A virus H3N2 hemagglutinin sequences, 
where site-level methods also appear to be sensitive to sequence sampling ([19], see Text S1 
and Table 23).
```

This behavior suggests that you have episodic selection in your data. FUBAR looks for *pervasive* selection, meaning that adding or removing some sequences can move the needle quite a bit. For alignments with ~20 sequences, you may want to run MEME and see if the same pattern persists. 

Best,
Sergei

**Comment by jhcepas** [comment]
thanks for the quick answer @spond!

would not MEME lead to similar a correlation with sampling size? (more sites when more seqs are included? 

we basically found differences in the number of sites under negative selection between two categories of gene families, one containing on average fewer seqs per alignment (and fewer sites under selection based on FUBAR).  We are not sure if the differences are the result of different sampling size or biological reasons.

**Comment by spond** [comment]
Dear @jhcepas,

Site methods (like MEME) do gain power as you add more sequences (unless your sequences are all too similar), assuming there is selection to be detected of course. 

If you want to compare selection regimes between genes, I would not recommend comparing the number of sites under selection, because it is fraught with statistical issues like the one you report. You can't know for sure if the lack of finding (negatively selected sites) is due to the fact that they are not there, or due to lack of power (sample size).

The "proper" way to do this comparison is to fit a mixed effects model, with genes being modeled by using a random effect, and gene families -- a fixed effect. This would involve analyzing all the genes together, fitting a hierarchical model to all of them jointly, and then performing hypothesis testing.

A simpler exploratory way to do the same is to estimate distributions of dN/dS for all genes, and compare these distributions. You can use BUSTED or FUBAR for it. With FUBAR, you can then do distributional clustering (see https://jvi.asm.org/content/90/18/8085) using an appropriate distance metric. With BUSTED, you can estimate fractions of sites under negative selection in each gene, the strength of said selection (&omega; value) and compare them between families in a post-hoc fashion.

Best,
Sergei
