### ISSUE TITLE
MEME: EBF-annotated trees

### ISSUE THREAD

**Issue by snaketron** [veg/hyphy#1067]
Dear @spond ,

Is it possible to visualize phylogenetic trees annotated with EBF (from MEME's json output)?

Based on my limited experience vision.hyphy does not provide such utility. Would you please suggest an alternative?

Best

**Comment by snaketron** [comment]
While we are at the subject of MEME: is it possible to obtain the branch-specific omega attributes (for different sites)? Does this make sense, i.e. would these estimates be reliable?

Best

**Comment by spond** [comment]
Dear @snaketron,

1. Take a look at https://observablehq.com/@spond/plotting-meme-ebf-on-branches-at-individual-sites. 

2. It is not possible to obtain meaningful estimates of branch-specific estimates for individual sites, because your effective sample size is ~1 (evolution along one branch at one site).

Best,
Sergei

**Comment by snaketron** [comment]
Many thanks!
