### ISSUE TITLE
Relative rate test for groups of species

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#1079]
Dear Hyphy team,
I'm interested in if evolutionary rates are significantly different between different groups of species. For example, in this tree: (outgroup, ((A, B), (C, (D, E)))); A, D, E belong to group 1; B, C belong to group 2. It is possible to test whether the evolutionary rate of group 1 is significantly higher than group 2? 

I'm using the Hyphy relative rate test, but it seems like it only does pairwise relative rate tests. I was wondering if there's a way for me to also include a labeled tree as input for the relative rate test? 

Thank you! 

YY

**Comment by spond** [comment]
Dear @lyy005,

Could you please clarify what you mean by the evolutionary rate of a group? The reason I ask is that there are three "standard" types of tests in this context

1. *Relative rate* -- `((A,B),OG)` and you can test if the branch length leading to `A` is longer that `B`. You can interpret this test because of the outgroup lineage which "polarizes" the tree

2. *Relative ratio* -- you have two *identical* trees, say from two different genes on the same set of species, and you want to compare the overall lengths of the tree, assuming all the branch lengths are proportional (see https://www.ncbi.nlm.nih.gov/pubmed/9136027)

3. Absolute rates if you have timed trees, i.e. in the presence of a molecular clock.

In your situation none of these apply, so it would be helpful to clarify the test you are interested in performing. 

Best,
Sergei
