### ISSUE TITLE
Internal error due to incorrect auto-detection of non-reversible model

### ISSUE THREAD

**Issue by uconneeb** [veg/hyphy#1091]
This is a followup to a question tweeted @hyphy_software (thanks, Sergei, for the fast reply!). I'm trying to change the model for some edges of the tree in a batch file. The minimal example below attempts to swap out the default model (hky1) for a new model (hky2) on edges 113, 9939, and x (using the hiv.nuc data set in Examples/SimpleAnalyses/data). This results in the following error:
```
Internal error
Internal error in ComputeBranchCache (branch t.9939 ) reversible model cached likelihood =   -1209.239486983555, directly computed likelihood =   -1209.800923163494. This is most likely because a non-reversible model was incorrectly auto-detected (or specified by the model file in environment variables).

Function call stack
1 :  Optimize(paramValues, theLnLik);
```
Is this because frequencies are not constant across the tree? Is there any way to inform HyPhy that a non-stationary model is being used?

Here is the batch file that produces the error:

```
DataSet nucleotideSequences = ReadDataFile("hiv.nuc");
DataSetFilter filteredData = CreateFilter(nucleotideSequences,1);

global kappa = 4.;
HKY85RateMatrix = 
		{{     *      ,    beta    ,    beta*kappa  ,     beta    }
		 {    beta    ,     *      ,       beta     ,  beta*kappa }
		 { beta*kappa ,    beta    ,         *      ,     beta    }
		 {    beta    , beta*kappa ,       beta     ,       *     }};

eqfrq = {{.25}{.25}{.25}{.25}};
Model hky1 = (HKY85RateMatrix, eqfrq);
Tree t = (((317,6767),((135,(529,105r)),(719,136))),6760,((113,9939)x,(256,(822,159))));

atrich = {{.3}{.2}{.2}{.3}};
Model hky2 = (HKY85RateMatrix, atrich);
SetParameter(t.113, MODEL, hky2);
SetParameter(t.9939, MODEL, hky2);
SetParameter(t.x, MODEL, hky2);

GetInformation(modelMap, t);
fprintf(stdout, modelMap);

LikelihoodFunction theLnLik = (filteredData, t);
Optimize(paramValues, theLnLik);
fprintf (stdout, theLnLik);

```

**Comment by plewis** [comment]
Sorry, I meant to post this issue as plewis rather than uconneeb.

**Comment by spond** [comment]
Dear @plewis,

Haven't seen this one before, but it has to do with the fact that HyPhy will use computational heuristics that speed up likelihood calculations if the model is time-reversible. I have some code that tries to detect (run-time) if the model is reversible. In this case, each branch model is, but Felsenstein's trick of rooting on any branch you want doesn't apply because one of the models has different stationary frequencies. I'll update the reversibility checking code to also look at the base frequency equality (at the moment it incorrectly determines reversibility in your example). Thankfully, you can override this check completely, by using an environment variable 

```
ASSUME_REVERSIBLE_MODELS = -1;
```

Just place that statement somewhere before you make the `LikelihoodFunction` call, and the error should disappear. I'll keep the issue open for now to remind myself to fix the auto-detect reversibility code. 

Best,
Sergei

**Comment by plewis** [comment]
Many thanks, Sergei!

**Comment by spond** [comment]
Resolved in the dev branch, will be a part of the next release. Thanks @plewis!
