### ISSUE TITLE
Minimum number of sequences for aBSREL

### ISSUE THREAD

**Issue by iss89** [veg/hyphy#1096]
Hello,

I want to do exploratory testing on all core genes of a bacterial genome set with aBSREL. Unfortunately my genomes are not very diverse so that I am left with only somewhere between 3 to 7 unique sequences in most cases. I wonder what the minimum number of unique sequences is for the analysis to give a meaningful result. 

On the datamonkey help page it says: 
"As a rule of thumb, at least 10 sequences are needed to detect selection at a single site (SLAC/FEL/IFEL/REL) with any degree of reliability, while as few as 4 may be sufficient for alignment-wide inference (PARRIS/GA-Branch)"

Does REL here also mean aBSREL?

On the other hand inthe recent book chapter "Evolution of Viral Genomes: Interplay Between Selection, Recombination, and Other Forces" it says:
"Small datasets, i.e., ≤ 10 sequences (especially when coupled with low divergence), are unlikely to yield any sites under selection. Consider using gene-wide methods like BUSTED or aBSREL to look for selection in these cases."

This sounds like aBSREL was ok to use with less than 10 sequences.

Many thanks in advance!

**Comment by spond** [comment]
Dear @iss89,

First of all, we have a newer version of this chapter at http://hyphy.org/resources/tutorial-2017.pdf

For 3-7 sequences I would use:

1. `aBSREL` : it essentially analyzes one branch at a time, and will not be negatively affected by a small tree. In fact,  if you use `aBSREL` for exploratory (all branch) testing on large trees, you are likely to lose power due to multiple testing correction. `aBSREL` will not however overcome low divergence levels. You can still detect selection there, but the effect of selection has to be very strong.

2. `BUSTED` which pools information across all sites and branches. For smaller alignments, I would recommend you override the default settings and use simpler rate distributions, for exampe

```
$hyphy busted --alignment your_file.fas --rates 2 --syn-rates 2
```

Let me know what you find.

Best,
Sergei
