### ISSUE TITLE
core dumped with parallel jobs

### ISSUE THREAD

**Issue by MCH74** [veg/hyphy#1097]
Hi,
I'm running a high number of BUSTED jobs (>5000) on a grid engine. When running them sequentially they work fine and only use ~0.5G. But if I submit multiple jobs in parallel, reserving 10G each, many of them are crashing with the following error message:
   Illegal instruction (core dumped)
Any ideas what is happening and how it can be avoided? I'm using version 2.3.13.
Thank you,
Mark

**Comment by spond** [comment]
Dear @MarkChristianHarrison,

1. Please use version 2.5.x -- there are many **significant** speed and stability improvements. 
2. BUSTED is not very memory intensive (it should not use 0.5G unless you have very large alignments).
3. `Illegal instruction` errors typically have to do with heterogenous CPUs. If you compile HyPhy and a recent CPU which has specific [vector instructions](https://en.wikipedia.org/wiki/FMA_instruction_set), and then run them on compute nodes that don't have the same support, the program will crash on those nodes. You can disable these features during program build using 

```
cmake -DNOAVX=ON ./
```

Best,
Sergei

**Comment by MarkChristianHarrison** [comment]
Hi Sergei,
Thanks for the quick response. I now have the jobs running on version 2.5.5, which we installed with -DNOAVX=ON. I'm now getting the following error on some of the jobs (so far 3 out of 17 jobs):

Error:Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-9139.946292888812] does not match the last recorded LF maximum [-9139.934302391224]
Internal error 
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-9139.946292888812] does not match the last recorded LF maximum [-9139.934302391224]


My command is:
hyphy BUSTED CPU=5 --alignment alignement.fasta --tree tree.file --branches F > outfile

It's running on a grid engine with 1G and 5 cores reserved, looping through a list of 5000 file names, each time creating a new subdirectory.

Thanks,
Mark

**Comment by spond** [comment]
Dear @MCH74,

These errors are meant to indicate that some sort of numerical instability has been detected during the optimization process; when those are encountered, the best course of action is to stop the analysis with an error because the results may be unreliable. In an MP environment these errors could also be stochastic (because floating point computations are not generally commutative, so `t1 + t2 + t3` may not be equal to `t2 + t1 + t3`, for example), so repeated runs on the same data, or single threaded runs (CPU=1) may mitigate the error.

Whenever possible, I would like to ask users for the data that trigger these issues, so that I can improve the code and handle such instabilities (or possible internal optimizer issues) more gracefully. Would you be willing to send me one of the files where an `InternalError` was reported?

Best,
Sergei

**Comment by MCH74** [comment]
thanks Sergei, I'll send you an email
