### ISSUE TITLE
Rules of thumb for aBSREL use

### ISSUE THREAD

**Issue by Edison2021** [veg/hyphy#1100]
Hi 
The 'Rules of thumb for aBSREL use' in the tutorial mentions "we strongly discourage performing multiple separate tests for selection on different branch sets." I am a little confused with the comment, Could you please explain more? 

Best
Edison

**Comment by spond** [comment]
Dear @Edison2021,

What this means (I think:) is:

Assume you have a tree with many branches and you divide them into separate groups: G1, G2 and G3. Then you could run `aBSREL` on G1 first, find, for example, that there is no selection on that set, and then proceed to test G2 in separate run, and so on. 

This approach might not be statistically valid, specifically, it is more likely to find false positive results that would be indicated by the p-value. That's because the multiple hypothesis correction would be applied to each group independently, whereas the valid approach would apply the correction to all groups together, making the test more conservative.

So instead you should decide what you are going to test _a priori_ and run the test **once**

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear Edison, 

Because the number of possible branch sets within a phylogenetic tree is combinatorially large, where and performing an analysis with a different branch set constitutes a new statistical test, you may need to take into consideration multiple testing correction if the number of branch sets you're analyzing is high. 

Best,
Steven

**Comment by Edison2021** [comment]
Hi Sergei and Steven
Thanks for your information!
If I have a tree with four separate groups: G1-G4. May i run absrel separately as follows
Assign the G1 to foreground, G2, G3 and G4 as background
Assign the G2 to foreground, G1,G3 and G4 as background
Assign the G3 to foreground, G1, G2 and G4 as background

Thanks
Edison

**Comment by spond** [comment]
Dear @Edison2021,

There is no concept of foreground or backbiting in aBSREL. You may choose to test only a subset of branches, and ignore the rest. Can you elaborate on what evolutionary hypotheses you are testing?

Best,
Sergei

**Comment by Edison2021** [comment]
Hi Sergei
I have 40 species that can be separated into 4 groups and each group has a specific trait, I suppose some genes are under selection at ancestral node (the node leading to species sharing trait) contributing to origin of the trait. So i would like to know what genes are.

Best
Edison

**Comment by spond** [comment]
Dear @Edison2021,

If I understand you correctly, you want to test for selection along the purple branches of a tree that looks like this

<img width="1164" alt="Screen Shot 2020-03-04 at 7 00 43 PM" src="https://user-images.githubusercontent.com/1018513/75934525-bb3ab880-5e4a-11ea-97cb-712ba4fd5976.png">

There are a few things you could do.

1. Run `aBSREL` **only** on the 4-branch purple set. This will allow you to test whether or not the ancestral branches to your four groups experienced positive diversifying selection.

2. Run `FADE` on each of the four groups separately. This will test for evidence of directional selection in specific clades

3. Run `RELAX` in group mode (see https://mbio.asm.org/content/10/6/e02524-19/article-info for an example) to determine whether or not selective pressures differ between the four clades. The four groups would be each of the colored branch sets. 

Best,
Sergei

**Comment by Edison2021** [comment]
Hi Sergei
Thanks very much for the detailed methods that will be very helpful for my project.

Best
Edison

**Comment by spond** [comment]
Dear @Edison2021,

No worries. Let me know if need further guidance. How many different genes are you testing?

Best,
Sergei

**Comment by Edison2021** [comment]
~2500 genes
