### ISSUE TITLE
Weighted average omega in MEME

### ISSUE THREAD

**Issue by snaketron** [veg/hyphy#1109]
Dear @spond,

Would it be reasonable to estimate the average omega at a site based on the result from MEME (e.g. by computing the weighted average of `omega+` and `omega-` => `omega+*p+ + omega-*p-`)?

For a full description of why I ask:
I am currently studying the degree of selection pressure at different proteins sites as a function of a continuous trait. To be more precise, I have created `N` alignments (each having 50 DNA sequences of different species), such that the species in the 1st alignment have on average the 'lowest' trait, and the species in the `Nth` alignment the 'highest' trait. Then, I use MEME to estimate `alpha`, `omega-`, `omega+`, `p-` and `p+` for each alignment (figure below shows the results for a particular protein site for all alignments=points, 2-mixture components are connected with a gray line, point-size = mixture weights, point-color = `omega` class).

![Selection_pressure](https://user-images.githubusercontent.com/5060977/76331628-adc07b00-62ef-11ea-89a3-eb651489dcb0.png)

I would like to have a simplified version of the above figure (e.g. with average omega per site instead of having separate `omega-` and `omega+`). In the past I have used FUBAR to infer omega, however, with episodic positive selection possible for my data I would like to use a more sophisticated method such as MEME. Any recommendation is welcome.

BTW: Thank you for the Datamonkey server!

Best

**Comment by spond** [comment]
Dear @snaketron,

A couple of thoughts here.

1. If your goal is to obtain a site-level estimate of &omega; it's better to go with FEL or FUBAR. Computing weighted MEME post-hoc estimates is going to be nosier, especially since the precision on &omega;+ could be quite low.

2. I quite like your 2D plot, which shows some marked separation in the &omega;+ category as a function of the trait space -- why don't you use it here?

3. I see there are a number of &omega;- values stuck at 1; this could be a convergence error that I fixed in version 2.5.4, so you might want to download the newest HyPhy and see if the estimate changes (it should also be deployed on Datamonkey.org).

4. If you are going to discretize the trait feature, you could directly test for which sites have differential selection between groups using `Contrast-FEL` http://hyphy.org/methods/other/contrast-fel/

Best,
Sergei

**Comment by snaketron** [comment]
Dear @spond ,

thank you for the very useful comments! 

Best
