### ISSUE TITLE
RELAX - decimal accuracy of log likelihood values

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#1123]
Hi dear team,

I have noticed that when executing RELAX (not via data monkey), the LRT derived from the reported log likelihoods is not consistent with the reported p-value. Since this occurs for high p-values, I suspect the issue stems from low decimal accuracy in the reported log likelihoods. Please find attached an example of this case. 

Based on the example, the reported values are:
null log likelihood (line 169): -3180.10
alternative log likelihood(line 149): -3180.10
p-value (line 180): 0.8998
Although, as the difference between the log likelihoods of both hypothesis is 0, the p-value should be 1. 

[relax_example.txt](https://github.com/veg/hyphy/files/4401900/relax_example.txt)

Best,
Keren

**Comment by spond** [comment]
Dear @halabikeren,

The log likelihood values printed to the screen are rounded to two digits of precision. Look into the `JSON` file for the full precision values (subject to specified optimization precision). It also looks like you are using an old version of HyPhy -- I recommend you move to 2.5.x because RELAX is more accurate, faster, and has better numerical stability in later versions.

Best,
Sergei
