### ISSUE TITLE
Output file is not valid JSON

### ISSUE THREAD

**Issue by migrau** [veg/hyphy#1140]
After running SLAC with HYPHY 2.5.8(MP) for Linux on x86_64 (`hyphy slac --alignment in.fas --tree in.treefile`), I try uploading the JSON (http://vision.hyphy.org/slac) but nothing happens.

If I check the web browser Console messages there is an error:
Uncaught SyntaxError: Unexpected token i in JSON at position 35491947

If I try loading the JSON in a json-viewer program, there is another error "Output file is not valid JSON". JSON is not empty, size is 35MB.

No errors during execution. Last lines from the run log:
```
### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model

* Log(L) = -1359.29, AIC-c = 18535.69 (7885 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) =     -inf, AIC-c =      inf (7892 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.9165

### Performing joint maximum likelihood ancestral state reconstruction

### For partition 1 these sites are significant at p <=0.1

|     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|       2        |       1        |     0.000      |     72.000     |     0.000      |     35.998     |  Pos. p = 0.000   |
|       54       |       1        |     2.000      |     0.000      |     2.146      |     0.000      |  Neg. p = 0.097   |
|       65       |       1        |     0.000      |    108.000     |     0.000      |     48.695     |  Pos. p = 0.000   |
|       70       |       1        |     18.000     |     90.000     |     21.658     |     43.870     |  Pos. p = 0.002   |
|       87       |       1        |     0.000      |    108.000     |     0.000      |     48.656     |  Pos. p = 0.000   |
|      163       |       1        |     35.000     |     0.000      |     82.720     |     0.000      |  Neg. p = 0.000   |
|      176       |       1        |     34.500     |     36.500     |     47.332     |     17.142     |  Neg. p = 0.000   |
|      201       |       1        |     36.000     |     36.000     |     79.115     |     15.281     |  Neg. p = 0.000   |

### Ancestor sampling analysis

>Generating 100 ancestral sequence samples to obtain confidence intervals

Done with ancestral sampling              
Resampling results for partition 1

|     Codon      |   Partition    |    S [median, IQR]    |    N [median, IQR]    |    dS [median, IQR]    |    dN [median, IQR]    |  p-value [median, IQR]  |
|:--------------:|:--------------:|:---------------------:|:---------------------:|:----------------------:|:----------------------:|:-----------------------:|
|       2        |       1        |   6.00 [6.00-7.00]    |  13.00 [13.00-13.00]  |    6.32 [6.32-7.38]    |    6.60 [6.60-6.60]    |    0.57 [0.57-0.69]     |
|       54       |       1        |   2.00 [2.00-2.00]    |   0.00 [0.00-0.00]    |    2.15 [2.15-2.15]    |    0.00 [0.00-0.00]    |    0.10 [0.10-0.10]     |
|       65       |       1        |   3.00 [3.00-3.00]    |  14.00 [14.00-16.00]  |    4.38 [4.38-4.42]    |    6.25 [6.24-7.14]    |    0.41 [0.32-0.42]     |
|       70       |       1        |   7.00 [7.00-7.16]    |  13.00 [11.00-13.00]  |    7.24 [7.24-7.41]    |    6.64 [5.62-6.64]    |    0.67 [0.67-0.80]     |
|       87       |       1        |   0.00 [0.00-0.00]    |   0.00 [0.00-0.00]    |    0.00 [0.00-0.00]    |    0.00 [0.00-0.00]    |    1.00 [1.00-1.00]     |
|      163       |       1        |   4.33 [4.33-8.33]    |  16.67 [14.67-20.67]  |  12.36 [12.36-23.11]   |    7.71 [6.77-9.61]    |    0.22 [0.01-0.40]     |
|      176       |       1        |   9.00 [9.00-9.00]    |  29.00 [25.00-31.32]  |  10.21 [10.21-10.21]   |  14.20 [12.32-15.43]   |    0.84 [0.74-0.90]     |
|      201       |       1        |   7.50 [7.50-7.82]    |  27.50 [25.50-29.82]  |  15.87 [15.33-16.67]   |  11.64 [10.79-12.75]   |    0.29 [0.24-0.38]     |
```

Many thanks,

**Comment by stevenweaver** [comment]
Dear @migrau, 

Thank you, the issue may be difficult to track down without having the actual JSON results file. The error is that the JSON likely has a strange character or other invalid format that was introduced while writing to the file. 

I understand that results can sometimes contain sensitive information. If you'd like to send the results to sweaver@temple.edu, I can take a closer look at what happened. Otherwise we will review results files from SLAC we have on hand to see if there are others with malformed JSON.

Best,
Steven

**Comment by migrau** [comment]
Dear Steven, 
I just sent the JSON to your email. Thanks for your help.
Miguel

**Comment by stevenweaver** [comment]
Dear Miguel, 

Thank you. I received the files. The issue is the same as the one I pointed out in #261 many years ago. Specifically, in your files, there were instances of both. May I ask which version of HyPhy you are running?

Additionally, due to the large size, these results throw an exception at the phylogenetic tree building stage. We're currently working on updating phylotree, but I'm afraid that these results files will need to be processed via a scripting language of your choice. 

Documentation regarding the JSON output can be found [here](https://hyphy.org/resources/json-fields.pdf)

Best,
Steven

**Comment by migrau** [comment]
Thanks for your help Steven, version is HYPHY 2.5.8(MP) for Linux on x86_64.  What is the MAX size for the phylogenetic tree building stage? I guess the result JSON is not corrupted and the issue comes only from http://vision.hyphy , right?
Cheers,
Miguel

**Comment by spond** [comment]
Dear @migrau,

I'll investigate whether or not the issue for `JSON` exporting `NAN` and `Inf` values has re-emerged. Can you e-mail me the input files (and analysis settings) for your analysis so I can recreate the problem?

Best,
Sergei

**Comment by migrau** [comment]
Done, @spond , many thanks! 
Miguel

**Comment by spond** [comment]
Dear @migrau,

I am going to release a new version (pending some testing) to address the issues you were seeing. 

1. There was an issue in handling sequence names that did not conform to HyPhy naming conventions
2. There were several issues that became apparent because there were a large number of identical sequences in your files. Thanks for sending me a test case that provided an example of some conditions that were not handled well by the code.

Instead of analyzing data with duplicate sequences, which causes additional (and often significant) computational burden to "fit" a bunch of zero branch lengths, you will get exactly the same result by keeping only a single copy of each identical sequence. 

Best,
Sergei

**Comment by migrau** [comment]
Excellent, Sergei. Thanks for your help. Looking forward to test it.

**Comment by spond** [comment]
Dear @migrau,

Try 2.5.11. I also added a simple function to prune all identical sequences from an alignment and from the tree (if provided, see https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates)

On your data:

```
 hyphy ~/Development/hyphy-analyses/remove-duplicates/remove-duplicates.bf --msa N_nostop.alg.fas --output N_trimmed.nxh
....
> Loaded an alignment with 3929 sequences and 1260 sites from /Users/sergei/Dropbox/Swap/N_nostop.alg.fas

There are **240** unique sequences in alignment 

```

```
hyphy slac --alignment N_trimmed.nxh --tree neighbor-joining
```

...

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -4624.86, AIC-c =  9785.14 (267 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.7658

### Performing joint maximum likelihood ancestral state reconstruction

### For partition 1 these sites are significant at p <=0.1

|     Codon      |   Partition    |       S        |       N        |       dS       |       dN       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|      128       |       1        |     3.000      |     1.000      |     4.432      |     0.427      |  Neg. p = 0.037   |
|      139       |       1        |     11.000     |     2.000      |     9.829      |     1.072      |  Neg. p = 0.001   |
|      203       |       1        |     32.000     |     33.000     |     50.177     |     14.006     |  Neg. p = 0.000   |
|      204       |       1        |     0.000      |     32.000     |     0.000      |     19.876     |  Pos. p = 0.000   |
|      274       |       1        |     2.000      |     0.000      |     2.973      |     0.000      |  Neg. p = 0.050   |
|      298       |       1        |     2.000      |     0.000      |     2.972      |     0.000      |  Neg. p = 0.063   |
|      341       |       1        |     2.000      |     0.000      |     2.960      |     0.000      |  Neg. p = 0.050   |
|      360       |       1        |     2.000      |     0.000      |     2.960      |     0.000      |  Neg. p = 0.063   |

...
Best,
Sergei

**Comment by migrau** [comment]
Many thanks @stevenweaver , @spond !
