### ISSUE TITLE
Error in processing of FEL, FUBAR and MEME

### ISSUE THREAD

**Issue by thakur855** [veg/hyphy#1156]
The process ran for around 20 days and after that received an email quoting "We're sorry, there was an error processing your job".
Thanks

**Comment by stephenshank** [comment]
Dear @thakur855,

Can you please share the associated URLs for any job that failed? I.e., something of the form:
```
datamonkey.org/fel/$JOB_ID
```

where `$JOB_ID` is an alphanumeric identifier for the particular job that you submitted. If so, I can try to take a look and see at which step the process failed.

If you do not have them, can you please rerun and provide any URLs that result in errors? I will be happy to take a look.

Best,
Stephen

**Comment by thakur855** [comment]
1.http://datamonkey.org/fubar/5e9eb6e517bf5e2e9ffd5eeb
2.http://datamonkey.org/fubar/5ea01caf17bf5e2e9ffdeae
3. http://datamonkey.org/fel/5ea01c7617bf5e2e9ffdea2b

**Comment by thakur855** [comment]
http://datamonkey.org/meme/5e9ebab917bf5e2e9ffd640e
http://datamonkey.org/meme/5e9efff217bf5e2e9ffd8397

**Comment by stephenshank** [comment]
Dear @thakur855,

Thank you very much. An update on your inquiry:

The FUBAR jobs successfully completed, but the system was not aware. I shuffled around some files and database entries, and they may now be found here (note that they take a while to load as the resulting JSON files are > 80 MB):
http://datamonkey.org/fubar/5e9eb6e517bf5e2e9ffd5eeb
http://datamonkey.org/fubar/5ea01caf17bf5e2e9ffdeae6

There is sufficient information for me to rerun the MEME jobs, which I am doing right now.

Unfortunately there is not sufficient information for me to rerun the FEL job. Can you please resubmit, and post the URL here? This way I can track your request.

I will follow up soon with the results from the MEME jobs.

Best,
Stephen

**Comment by thakur855** [comment]
*Dear Sir,*

Thank you so much for your effort to handle the request with positive
outcomes in short span. I appreciate it.
I have resubmitted the FEL job and system generated ticket number is -
*1240512.new-silverback*

*Hope this much information is sufficient to track the job.*


Sincerely,

Bhupender Singh

PhD Aspirant (Bioinformatics).

Lovely Professional University,

Phagwara, Punjab, India, 144411.

**Comment by thakur855** [comment]
Sorry , I forgot to mention the URL for the FEL job.
The URL is-
http://datamonkey.org/fel/5ec87a2b6fa3ed0c9e04695c

Thanks & Regards



Sincerely,

Bhupender Singh

PhD Aspirant (Bioinformatics).

Lovely Professional University,

Phagwara, Punjab, India, 144411.

**Comment by stephenshank** [comment]
Dear @thakur855,

I'd like to provide you with an update. Your first MEME job (http://datamonkey.org/meme/5e9ebab917bf5e2e9ffd640e) seems to encounter an issue with HyPhy's constrained optimization, described here:
```
Error:
Internal error
Constrained optimization failed, since a starting point within the domain specified for the variables couldn't be found.
Set it by hand, or check your constraints for compatibility.
Failed constraint:meme.site_tree_bsrel.HCOV_19_IRAN_MEHR1_2020_EPI_ISL_414516_2020_02_29.beta_2:=1.048367625610227*9999.999999998339 must be in [0,10000]. Current value = 1.490642958252701.
```

Your second MEME job (http://datamonkey.org/meme/5e9efff217bf5e2e9ffd8397) and FEL job (http://datamonkey.org/fel/5ec87a2b6fa3ed0c9e04695c) appear to be timing out. We allocate 32 processors for a maximum period of three days. Both jobs contains 10043 sites and 181 sequences. We [track statistics of jobs that completed for various methods](http://datamonkey.org/stats), and it seems to me that datasets of this size for MEME and FEL are definitely pushing the threshold of what will run with our current configurations.

If it is possible to split up regions of your sequences and run individually, I'd recommend that. Otherwise, we'll need to have some internal discussion about the best way to proceed.

Tagging @spond who may wish to provide additional feedback.

Best,
Stephen

**Comment by thakur855** [comment]
Dear sir,
thanks for your response.
I will discuss the regarding sequence region splitting and will get back to
you.
Thanks

**Comment by spond** [comment]
Dear @thakur855,

For MEME/FEL it is best **not** to run multiple genes in the same analysis. The reason for it is that selection operates on genes/proteins, and combining them may create statistical and computational issues, e.g. if there is recombination, or if the rates of evolution differ between genes. Based on the names of your sequences in the error message, it looks like you are running whole genomes of SARS-CoV-2. I would suggest dividing them up into ORFs and genes (S, N, etc)

I'll look into the constrained optimization issue further.

Best,
Sergei

**Comment by thakur855** [comment]
Dear sir,
Thank you for your valuable reply.
I will positively take your suggestion and will incorporate.
