### ISSUE TITLE
one long branch for aBSREL result - alignment format issue?

### ISSUE THREAD

**Issue by iwinkler** [veg/hyphy#1163]
After trying several gene alignments successfully for aBSREL through the datamonkey site, we had 2 alignments that gave us a similar problem. The phylogeny on the results page showed one very long branch, while all the others were very short. I would expect this kind of result with a frameshift, for example, if an unallowed character was in the alignment and ignored by HyPhy. But, I can't see anything about the sequence file that would cause this problem. This is strange also because the branch selection widget for datamonkey shows a phylogeny with normal branch lengths.

The problem is repeatable if the original file is downloaded from the link on the results page and input back into aBSREL in datamonkey.

Any ideas? (or maybe I'm just missing something obvious?)

Here are the two results:

http://datamonkey.org/absrel/5ed82700d49cd511eec95d4e
http://datamonkey.org/absrel/5ed3e6a2d49cd511eec83f57

**Comment by jzehr** [comment]
Dear @iwinkler,

Thank you reporting this. Can you send along the alignment files you had trouble with?

We will take a look at your jobs, investigate, and get back to you ASAP!

Best,
Jordan

**Comment by iwinkler** [comment]
Here's the files. Thanks for looking at this!

**Comment by spond** [comment]
Dear @iwinkler,

There is no issue with the alignment. Such infinite branch lengths are caused by having infinite &omega; inferred at a proportion of sites in the alignment. 

For example in http://datamonkey.org/absrel/5ed82700d49cd511eec95d4e, the branch `BPUP3066` has a distribution of &omega; like this:

<img width="926" alt="Screen Shot 2020-06-07 at 7 55 12 AM" src="https://user-images.githubusercontent.com/1018513/83968033-41282e80-a894-11ea-9adf-11fea3a386cc.png">

Because there is an "infinite" &omega; component the branch length under the aBSREL model will blow up. For alignments with relatively low divergence, such infinite estimates may arise from multiple nucleotide substitutions occurring within a single codon, e.g. `ACG->AAA` at site 206 for `BPUP3066` (the image is rendered based on a SLAC analysis).

<img width="514" alt="Screen Shot 2020-06-07 at 8 28 28 AM" src="https://user-images.githubusercontent.com/1018513/83968692-f52bb880-a898-11ea-8081-05b4445f1757.png">


You can see that the alignment itself is not at issue, by viewing the tree using branch lengths from the baseline MG94xREV model.

<img width="766" alt="Screen Shot 2020-06-07 at 7 56 36 AM" src="https://user-images.githubusercontent.com/1018513/83968066-7896db00-a894-11ea-91e1-03fb5ddcbd34.png">

Best,
Sergei

**Comment by iwinkler** [comment]
Sergei,
Thanks so much for the explanation and for taking the time to look at this.
Cheers,
Isaac
