### ISSUE TITLE
SLAC Phylogenetic alignment bug

### ISSUE THREAD

**Issue by crs344** [veg/hyphy#1165]
Hi,

Slac itself has been working fine for our group, as are most of the tools in the SLAC vision interface. However, the SLAC phylogenetic alignment tool for viewing amino acid or codon reconstructions across a tree has stopped working for our group (two of us have independently experienced this). When you go to change the amino acid or codon position, either by clicking the arrows or by typing in the number, all of Slac vision glitches and displays the attached error message (attached)
[Apocynaceae_dhshss_slac2.json.zip](https://github.com/veg/hyphy/files/4740606/Apocynaceae_dhshss_slac2.json.zip)
<img width="942" alt="slac_error" src="https://user-images.githubusercontent.com/66136271/83949342-39637e00-a7f1-11ea-84f2-f3cb801e618b.png">

.

This aspect of Slac vision is very useful to us, so I hope this bug is easily fixed. I've also attached one of our Slac json output files, as well.

Best,

Chelsea

**Comment by aglucaci** [comment]
Dear Chelsea,

I am able to replicate the issue on my end and will investigate further. Thank you for sharing this. If possible, could you also provide the alignment file you used for the SLAC analysis?

Best,
Alexander

**Comment by spond** [comment]
Dear @crs344,

Upon closer inspection, it seems like the sites where the viewers break have a particular property: they have ambiguous codons that map to multiple amino-acids (e.g. `G--` which maps to `KN`). For example, you can view sites 3,4,5 etc by typing their coordinates in the box, because they don't have the "multi-amino-acid" codons.

I would like to note here that generally having "broken-up" codons, like what's shown above (`G--`) might indicate that the alignment is not optimally aligned to be in frame. For example, there are some sequences that look like 

> ATGG----N--N--N...

Are you sure this is the correct in-frame alignment?

@stephenshank : since this module was developed by you, could you please take a quick look to see if having multiple amino-acid resolutions breaks the viewer.

Best,
Sergei

**Comment by crs344** [comment]
[Apocynaceae_dhshss_hyphy.fasta.zip](https://github.com/veg/hyphy/files/4740808/Apocynaceae_dhshss_hyphy.fasta.zip)
Here the the alignment used. It *shouldn't* have any broken codons (shouldn't being emphasized because I easily could have missed some). 

Thank you both for responding so quickly.

**Comment by spond** [comment]
Dear @crs344,

Investigating now, there's definitely something wrong happening with your alignment.

Best,
Sergei

**Comment by spond** [comment]
Dear @crs344,

The `--N` is an internal bug that I am going to address, but your alignment **does** have broken codons, e.g. 

```
>Gymnema_sylvestre_TL615_dhs
---------------ATGG------AGC
...
>Beaumontia_murtonii_53_hss
ATGGGTGAA---GCCACCG---
...
```

Best,
Sergei

**Comment by spond** [comment]
Dear @crs344,

The error was caused by the fact that our viewer was not able to properly handle partially gapped codons, which were present in your data (e.g. `G--`). The fix is being tested and will be deployed soon. The other fix (incorrectly reporting `N--` in place of `---` in SLAC results) will be deployed in the next HyPhy release. 

Best,
Sergei

**Comment by spond** [comment]
Dear @crs344,

Both datamonkey and vision.hyphy.org have been fixed, so you should be able to view your `JSON`. The results of SLAC will not be affected by the `N--` bug, but I will keep the issue open until I push a fix to the `hyphy` core. 

Best,
Sergei

**Comment by crs344** [comment]
It's working beautifully, thank you so much!
