### ISSUE TITLE
missing work

### ISSUE THREAD

**Issue by NeverseenAgain** [veg/hyphy#1185]
I requested a job and was wondering how long its been but it is no longer in the job queue and I have not recieved an email saying it's done?

**Comment by spond** [comment]
Dear @NeverseenAgain,

To clarify: you submitted a job to Datamonkey and you never received a completion report? 

Due to technical issues, we had to restart the Datamonkey database server today and some of the jobs that were running at the time may have gotten lost. Do you have the ID of the job that was lost?

It may be easiest to submit it again.

Best,
Sergei

**Comment by NeverseenAgain** [comment]
I do not and I resubmitted it and wrote down the ID this time
thank you

**Comment by spond** [comment]
Dear @NeverseenAgain,

You may actually have it in your browser history (it's the page that appears after the job submission is accepted).

Best,
Sergei

**Comment by NeverseenAgain** [comment]
I do not see it all of the things in my history are just the queue
