### ISSUE TITLE
RELAX LC_ALL Error

### ISSUE THREAD

**Issue by hrluo93** [veg/hyphy#1187]
dear sir,
the job http://www.datamonkey.org/relax/5ea58c29d10c000700369553 
 Error Message
-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")

Check errors.log for execution error details.

**Comment by jzehr** [comment]
Dear @stephenshank,

@hrluo93 is having some trouble with the RELAX job he is running, can you take a peek into his job and see where the error is coming from?

Best,
Jordan

**Comment by hrluo93** [comment]
> Dear @stephenshank,
> 
> @hrluo93 is having some trouble with the RELAX job he is running, can you take a peek into his job and see where the error is coming from?
> 
> Best,
> Jordan

Thanks for your reply!
i have run relax package in my local ubuntu, when in Fitting the null (K :=1) model, program showed Error:Internal error 
 _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1.   -5129.2981314018 / -5042.058465470203.
 Optimization direction: 
{
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{0} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
}
Internal error 
 _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration 1.   -5129.2981314018 / -5042.058465470203.
 Optimization direction: 
{
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{0} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
{-10000} 
}

**Comment by spond** [comment]
Dear @hrluo93,

Let me pull down the files and see what's causing the error. Usually it's due to infinite branch lengths (highly divergent sequences), but I want to confirm.

Best,
Sergei

**Comment by spond** [comment]
Dear @hrluo93,

Seems like your original job (http://www.datamonkey.org/relax/5ea58c29d10c000700369553) was submitted back in April (`Apr 26 09:27`) and experienced a server misconfiguration error which has since been fixed. 

I also confirmed that the current `dev` branch is able to process your analysis with the following results:

---

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -2700.86, AIC-c =  5486.44 (42 estimated parameters)
* non-synonymous/synonymous rate ratio for *Reference* =   0.0351
* non-synonymous/synonymous rate ratio for *Test* =   0.0000

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -2691.31, AIC-c =  5467.34 (42 estimated parameters)
* non-synonymous/synonymous rate ratio for *Reference* =   0.0309
* non-synonymous/synonymous rate ratio for *Test* =   0.0000

### Fitting the general descriptive (separate k per branch) model

### * Log(L) = -2680.61, AIC-c =  5505.25 (71 estimated parameters)
* The following baseline rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   100.000   |                                   |
|        Negative selection         |     0.000     |    0.000    |       Not supported by data       |
|      Diversifying selection       |     1.094     |    0.000    |       Not supported by data       |


 ### Because some of the rate classes were collapsed to 0, the model is likely overparameterized. RELAX will reduce the number of site rate classes by one and repeat the fit now.
----

Fitting the general descriptive (separate k per branch) model
* Log(L) = -2680.61, AIC-c =  5501.14 (69 estimated parameters)
* The following baseline rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   100.000   |                                   |
|      Diversifying selection       |     1.094     |    0.000    |       Not supported by data       |

* Branch-level relaxation or intensification parameter distribution has mean  2.24, median  3.28, and 95% of the weight in  0.00 -  5.22

### Fitting the alternative model to test K != 1
* Log(L) = -2691.31, AIC-c =  5471.41 (44 estimated parameters)
* Relaxation/intensification parameter (K) =    10.05
* The following rate distribution was inferred for **test** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   100.000   |                                   |
|      Diversifying selection       |     1.012     |    0.000    |       Not supported by data       |

* The following rate distribution was inferred for **reference** branches

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.031     |   100.000   |                                   |
|      Diversifying selection       |     1.001     |    0.000    |       Not supported by data       |


### * Potential convergence issues due to flat likelihood surfaces; checking to see whether K > 1 or K < 1 is robustly inferred

### Fitting the null (K := 1) model
* Log(L) = -2692.17, AIC-c =  5471.10 (43 estimated parameters)
* The following rate distribution for test/reference branches was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.029     |   100.000   |                                   |
|      Diversifying selection       |     1.129     |    0.000    |       Not supported by data       |

----
## Test for relaxation (or intensification) of selection [RELAX]
Likelihood ratio test **p =   0.1890**.
>No significant evidence for relaxation (or intensification) of selection among **test** branches _relative_ to the **reference** branches at P<=0.05
----


### Fitting the partitioned descriptive model (completely separate rate distributions for branch sets)
* Log(L) = -2691.31, AIC-c =  5475.48 (46 estimated parameters)
* The following rate distribution was inferred for *test* branches 

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   100.000   |                                   |
|      Diversifying selection       |     1.128     |    0.000    |       Not supported by data       |

* The following rate distribution was inferred for *reference* branches 

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.031     |   100.000   |                                   |
|      Diversifying selection       |     1.128     |    0.000    |       Not supported by data       |

**Comment by hrluo93** [comment]
> Dear @hrluo93,
> 
> Seems like your original job (http://www.datamonkey.org/relax/5ea58c29d10c000700369553) was submitted back in April (`Apr 26 09:27`) and experienced a server misconfiguration error which has since been fixed.
> 
> I also confirmed that the current `dev` branch is able to process your analysis with the following results:
> 
> ### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
> * Log(L) = -2700.86, AIC-c =  5486.44 (42 estimated parameters)
> * non-synonymous/synonymous rate ratio for _Reference_ =   0.0351
> * non-synonymous/synonymous rate ratio for _Test_ =   0.0000
> 
> ### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
> * Log(L) = -2691.31, AIC-c =  5467.34 (42 estimated parameters)
> * non-synonymous/synonymous rate ratio for _Reference_ =   0.0309
> * non-synonymous/synonymous rate ratio for _Test_ =   0.0000
> 
> ### Fitting the general descriptive (separate k per branch) model
> ### * Log(L) = -2680.61, AIC-c = 5505.25 (71 estimated parameters)
> * The following baseline rate distribution for branch-site combinations was inferred
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.000	100.000	
> Negative selection	0.000	0.000	Not supported by data
> Diversifying selection	1.094	0.000	Not supported by data
> ### Because some of the rate classes were collapsed to 0, the model is likely overparameterized. RELAX will reduce the number of site rate classes by one and repeat the fit now.
> Fitting the general descriptive (separate k per branch) model
> 
> * Log(L) = -2680.61, AIC-c =  5501.14 (69 estimated parameters)
> * The following baseline rate distribution for branch-site combinations was inferred
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.000	100.000	
> Diversifying selection	1.094	0.000	Not supported by data
> * Branch-level relaxation or intensification parameter distribution has mean  2.24, median  3.28, and 95% of the weight in  0.00 -  5.22
> 
> ### Fitting the alternative model to test K != 1
> * Log(L) = -2691.31, AIC-c =  5471.41 (44 estimated parameters)
> * Relaxation/intensification parameter (K) =    10.05
> * The following rate distribution was inferred for **test** branches
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.000	100.000	
> Diversifying selection	1.012	0.000	Not supported by data
> * The following rate distribution was inferred for **reference** branches
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.031	100.000	
> Diversifying selection	1.001	0.000	Not supported by data
> ### * Potential convergence issues due to flat likelihood surfaces; checking to see whether K > 1 or K < 1 is robustly inferred
> ### Fitting the null (K := 1) model
> * Log(L) = -2692.17, AIC-c =  5471.10 (43 estimated parameters)
> * The following rate distribution for test/reference branches was inferred
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.029	100.000	
> Diversifying selection	1.129	0.000	Not supported by data
> ## Test for relaxation (or intensification) of selection [RELAX]
> Likelihood ratio test **p = 0.1890**.
> 
> > No significant evidence for relaxation (or intensification) of selection among **test** branches _relative_ to the **reference** branches at P<=0.05
> 
> ### Fitting the partitioned descriptive model (completely separate rate distributions for branch sets)
> * Log(L) = -2691.31, AIC-c =  5475.48 (46 estimated parameters)
> * The following rate distribution was inferred for _test_ branches
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.000	100.000	
> Diversifying selection	1.128	0.000	Not supported by data
> * The following rate distribution was inferred for _reference_ branches
> 
> Selection mode	dN/dS	Proportion, %	Notes
> Negative selection	0.031	100.000	
> Diversifying selection	1.128	0.000	Not supported by data

Thanks for your reply!
the job have successfully in
http://www.datamonkey.org/relax/5f182eb960a5151234ea4bb5

I really appreciate your help!

Best wishes！
