### ISSUE TITLE
having problem with the data size 

### ISSUE THREAD

**Issue by Necla** [veg/hyphy#1188]
Dear Hyphy Team members,

I am trying use datamonkey tools and I don't know why the methods choose the first 41 sequences of my data even though I have 126 sequences with 3822 nucleotide. When I check out the alignment size restrictions apparently there shouldn't be  any problem with my data size. I would appreciate if you could help me?  

All the best,

**Comment by spond** [comment]
Dear @Necla,

Datamonkey will remove identical sequences from a dataset prior to analysis. This is done because identical sequences contribute no signal, but make computations longer. Consequently, 85 sequences in your dataset are identical to one of the 41 sequences that are retained. 

Best,
Sergei

**Comment by Necla** [comment]
Thank you very much for the quick response and helpful information. I should have checked this before!

**Comment by kagningemma** [comment]
Thank you @Necla and @spond . This thread has answered my question
