### ISSUE TITLE
MEME and FEL Internal Error

### ISSUE THREAD

**Issue by DanLesman** [veg/hyphy#1190]
I have downloaded the hyphy package and am running it locally using the command line with the command hyphy -i. I have tried running my alignment and tree with MEME, FEL with dS, and FEL without dS. Every time I have been met with the following error: Likelihood function evaluation encountered a NaN (probably due to a parameterization error or a bug).

This is the output after trying with MEME
![Screen Shot 2020-08-02 at 4 43 50 PM](https://user-images.githubusercontent.com/9941200/89132055-58c01400-d4df-11ea-86cc-ec01581eb688.png)

I am currently using version 2.5.8, anything I can do to fix this?

**Comment by spond** [comment]
Dear @DanLesman,

The first thing I would try is using the current version `2.5.15`. The `NaN` errors, when they occur, usually indicate some data pathology -- highly divergent sequences, alignment issues, etc. I'll be happy to take a look at the specific cause for your alignment, if you share it: alignment, tree, analysis settings.

Best,
Sergei

**Comment by DanLesman** [comment]
Dear Sergei,

Thank you for the advice! There are so many sequences that sharing may be difficult. However, there certainly are sequences with a high percentage of ambiguous bases, Ns, or gaps ("-"). Do you have any suggested parameters for filtering out sequences with over a certain percentage of bases missing?

Best,
Dan

**Comment by spond** [comment]
Dear @DanLesman,

The ambiguity fraction should not be that much of an issue. Do you see the `NaN` error with version 2.5.15 as well?

Best,
Sergei

**Comment by DanLesman** [comment]
Dear Sergei,

Yes, the error is still present in version 2.5.15.

Best,
Dan

**Comment by spond** [comment]
Dear @DanLesman,

That's a bummer. I can't give you more meaningful advice without having more information. Ideally, that would be the alignment (and the tree and analysis options), but if you are reluctant to share, run the analysis with `ENV="VERBOSITY_LEVEL=100"` option (you will see a lot of text dumped in the terminal as you run the analysis), and post the output here.

Best,
Sergei

**Comment by DanLesman** [comment]
Dear Sergei,

I would be happy to share the data with you. Unfortunately, the data is from GISAID so I cannot publicly share it. Attached is the output from setting the ENV variable.

Best,
Dan


<img width="1033" alt="Screen Shot 2020-08-11 at 1 04 06 AM" src="https://user-images.githubusercontent.com/9941200/89859241-8efc3400-db6e-11ea-92ee-65158be0c35f.png">

**Comment by spond** [comment]
Dear @DanLesman,

Unfortunately the error occurs on the first calculation, so it's not very helpful for diagnostics:( I understand your issue with GISAID. If you are comfortable doing so, please upload the file and the tree to https://www.dropbox.com/request/RTHuUgab9DTlQs6qaNfd (this is not publicly accessible for retrieval, and will expire on Aug 12th). I will trouble shoot the analysis, report my findings, and delete the files afterwards.

I have experienced several oddities with our own analyses of GISAID SARS-CoV-2 data, so I am curious what yours is. For example, some of our analyses (SLAC) were breaking because sequences contained ambiguous stop codons (`TAR`). 

Best,
Sergei

**Comment by DanLesman** [comment]
Dear Segei,

Thank you so much, I will share the data. I found the same issue with internal stop codons and ambiguous stop codons, which I bypassed by substituting ambiguous bases and stop codons with 'N' although I am not sure if this is a good practice or would alter the results.

Best,
Dan

**Comment by spond** [comment]
Dear @DanLesman,

Thanks for reporting this issue. It led me to make a number of improvements and speed-enhancements to HyPhy core, packaged into release 2.5.16. The `NAN` issue has been resolved, but for your specific case, I have the following recommendation.

Your dataset comprises >44,000 sequence, **but most of them are identical (exactly or up to gaps) to at least one other sequence**. In fact, there are about **3000** unique sequences there. For all of the common HyPhy analyses, including several identical sequences will provide no information for the inference (log likelihoods will be exactly the same with and without the duplicates), but it will slow down the execution, often dramatically. 

I wrote a [simple script](https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates) that you could use to take your larger alignment and the tree it comes with and prune it down to only unique sequences; one of the speedups prompted by your report (included in 2.5.16, which I will release today), benefits this analysis. You should then input this smaller alignment, which contains all the useful information for selection analyses, to `fel` or `meme`.

Best,
Sergei

**Comment by DanLesman** [comment]
Dear Sergei,

Thank you again for all the help. So I ran hyphy 2.5.16 on the resulting nxh file from trimming and MEME returned the following error:

![Screen Shot 2020-08-14 at 4 18 29 PM](https://user-images.githubusercontent.com/9941200/90289400-cbb77c00-de49-11ea-9392-10daa8b68696.png)

Do you know what might be causing this issue?

Best,
Dan

**Comment by spond** [comment]
Dear @DanLesman,

Let me look into it. It's possible that the changes in 2.5.16 created a new/regression bug for large trees (we don't have the most exhaustive test suite for these cases, unfortunately). I'll report what I find shortly. 

Best,
Sergei

**Comment by spond** [comment]
Dear @DanLesman,

OK, I found a newly introduced bug in 2.5.16 -- thanks again for reporting. I am going to fix it and release 2.5.17 (and delete 2.5.16 from releases...) after a bit more testing.

Best,
Sergei

**Comment by spond** [comment]
Dear @DanLesman,

I released 2.5.17 that addresses some of the issues, and was able to run FUBAR on your alignment (MEME should work as well, but see comment below). It seems like for these trees (which are large and have short branches), a few highly variable sites create numerical instability in likelihood function calculations that have previously not been exposed. I have not been able to fully resolve them, since debugging for these large datasets is slow, but these issues occur only early in optimization, when parameter values are far from the optimal values, so it should not affect results. To run your data please use the following additional flag:

```
hyphy fubar --alignment compressed.fas ENV="TOLERATE_NUMERICAL_ERRORS=1;"
```

This environment variable will allow HyPhy to continue past some numerical errors and report them to the console as warnings.

Here's the outcome of the FUBAR analysis, for example (warning messages not included)

Best,
Sergei

----

### Deleted 1 zero-length internal branches: `NODE_0016381`
* Log(L) = -36033.90, AIC-c = 83847.97 (5887 estimated parameters)
* Tree length (expected substitutions/site) for partition 1 :    0.834

### Computing the phylogenetic likelihood function on the grid 
* Determining appropriate tree scaling based on the best score from a  20 x 20 rate grid
* Best scaling achieved for 
	* synonymous rate =  1.227
	* non-synonymous rate =  0.857
* Computing conditional site likelihoods on a 20 x 20 rate grid

### Running an iterative zeroth order variational Bayes procedure to estimate the posterior mean of rate weights
* Using the following settings
	* Dirichlet alpha  : 0.5

### Tabulating site-level results
|     Codon      |   Partition    |     alpha      |      beta      |Posterior prob for positive selection|
|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------------------------:|
|       5        |       1        |        0.912   |       16.986   |       Pos. posterior = 1.0000       |
|       95       |       1        |        0.613   |        6.518   |       Pos. posterior = 0.9776       |
|      142       |       1        |        0.747   |        4.395   |       Pos. posterior = 0.9051       |
|      367       |       1        |        0.877   |        4.193   |       Pos. posterior = 0.9051       |
|      583       |       1        |        0.777   |        6.805   |       Pos. posterior = 0.9709       |
|      622       |       1        |        0.586   |        6.924   |       Pos. posterior = 0.9919       |
|      655       |       1        |        0.739   |        6.503   |       Pos. posterior = 0.9621       |
|      675       |       1        |        0.731   |        7.768   |       Pos. posterior = 0.9922       |
|      677       |       1        |        1.561   |       12.379   |       Pos. posterior = 0.9723       |
|      694       |       1        |        0.460   |        2.154   |       Pos. posterior = 0.9381       |
|      769       |       1        |        0.788   |        7.781   |       Pos. posterior = 0.9886       |
|      845       |       1        |        1.206   |        6.744   |       Pos. posterior = 0.9471       |
|      1118      |       1        |        0.504   |        2.120   |       Pos. posterior = 0.9127       |
|      1124      |       1        |        0.748   |        4.380   |       Pos. posterior = 0.9048       |
|      1260      |       1        |        0.510   |        2.633   |       Pos. posterior = 0.9474       |
----
## FUBAR inferred 15 sites subject to diversifying positive selection at posterior probability >= 0.9
Of these,  0.68 are expected to be false positives (95% confidence interval of 0-3 )

**Comment by DanLesman** [comment]
Dear Sergei,

Thank you so much for all your help! The FUBAR results are certainly useful and interesting. 

Should the program theoretically run if I were to switch "fubar" with "meme" or "fel" or should I make additional changes? Running the data as described above replacing only "fubar" has been giving me errors.

Best,
Daniel

**Comment by spond** [comment]
Dear @DanLesman,

Same errors or different errors? We are running weekly GISAID screens, and they have been hitting edge cases like crazy, so I am patching them as we go. I was able to run analyses on ~8000 unique `nsp3` sequences (looks like you have `S`) with FUBAR in about ~1 hour on my laptop. `FEL` and `MEME` also run (on our cluster), but now take a day on 64-128 nodes, because the datasets have become large.

Best,
Sergei
