### ISSUE TITLE
aBSREL choose p-value

### ISSUE THREAD

**Issue by lisajq** [veg/hyphy#1193]
Dear developers,

I used GARD to do the recombination analysis. according to the breakpoints in its result , I separated the whole alignment into some parts and ran on the aBSREL.  

every part has its own aBSREL's result. 
when I check which branches had selection,  Is it correct that I  integrate the results of divided parts?

I also confused about which should I refer to between test p-value and  Uncorrected p-value .
Can I choose all the branches that their  Uncorrected p-value <0.05 in firsr run to do the second run? then I choose the branches with test p-value <0.05?

which way is accurate and better  between directly choose branch with  test p-value<0.05  and   choose all branches with uncorrected p-value to do the second run?

Best,
lisajq

**Comment by spond** [comment]
Dear @lisajq,

If GARD indicates that you have recombination in your alignment **and** different partitions have different tree topologies, then you need to interpret `aBSREL` results carefully.

This is because `aBSREL` operates on branches, and if you have different topologies, some of the **internal** branches may exist in one tree but not the other. The only branches that are guaranteed to exist in all these topologies are **leaf** branches. For example, the blue branches highlighted in the each trees below do not have a match in the other tree.

<img width="189" alt="Screen Shot 2020-08-11 at 9 47 47 AM" src="https://user-images.githubusercontent.com/1018513/89905180-dbb82d00-dbb7-11ea-915b-351a337d0295.png">
<img width="201" alt="Screen Shot 2020-08-11 at 9 46 32 AM" src="https://user-images.githubusercontent.com/1018513/89905257-f25e8400-dbb7-11ea-8e0c-bdc1b965fe22.png">

Regarding p-values. Our recommendation is that you use `p-values` because they are corrected for multiple testing. `Uncorrected p-values` are provided for your reference only, and if you use them directly, it is likely that the test will return too many **false positives**.

My recommendation would be to run `aBSREL` on individual partitions **separately, and without selecting branches to test in one partition based on the results in the other** (this would induce a testing bias, calling HARK : hypothesizing after results are known). You may then identify branches that appear to be under significant positive selection in both partitions, assuming they exist in both partitions: this may be limited to terminal branches only, depending on what the topologies look like.

Best,
Sergei

**Comment by lisajq** [comment]
Dear @Sergei,

Thank you for your detail reply.
when I ran aBSREL, I chose "select all the leaf nodes". someone told me this way . but you helped me understand the more knowledge about aBSREL.  

Best,
Lisa

**Comment by lisajq** [comment]
Dear @sergei,

Thank you for your detail reply.
when I ran aBSREL, I chose "select all the leaf nodes". someone told me this way. you helped me understand the reason why I did this for.

Best,
Lisa
