### ISSUE TITLE
How to understand the non-synonymous/synonymous rate from BUSTED ?

### ISSUE THREAD

**Issue by JinqunHuang** [veg/hyphy#1194]
Dear developers of Hyphy,

I run hyphy BUSTED(version 2.2) as below:

hyphy BUSTED --alignment 2289.cds.muscle --tree 2289.cds.muscle.treefile --output 2289.cds.muscle.BUSTED >2289.cds.muscle.log

The input file “2289.cds.muscle ” was a single-copy gene Family(contain 7 genes) and aligmented by muscle-3.8.3.
I got thousands of familys.
I would like to calculate the dN/dS value of each family, and recognize which gene family was positive selection.

It is strange that(shown as below), the "p =   0.0001", and the "non-synonymous/synonymous rate ratio for *test* =   0.8171".
As far as I know, the non-synonymous/synonymous value >1 would be recognized as "positive selection".

So, how can I get the dN/dS value ? If the "on-synonymous/synonymous rate" does not larger than 1, could it be recognized as "positive selection"?

Thanks a lot for your advice
Best,
JinQun Huang

### Branches to test for selection in the BUSTED analysis
* Selected 11 branches to test in the BUSTED analysis: `DK118_V008936_DK118, DK119_V002634_DK119, DK130_V006449_DK130, DK139_V002103_DK139, Node6, DK023_V008945_DK023, Node5, DK016_V002634_DK016, Node4, DK017_V005679_DK017, Node3`

### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) = -4087.45, AIC-c =  8212.95 (19 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) = -3970.15, AIC-c =  7992.59 (26 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.8201

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -3969.09, AIC-c =  7990.46 (26 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.8171

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -3777.03, AIC-c =  7624.57 (35 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    7.932    |                                   |
|        Negative selection         |     0.000     |   52.317    |       Collapsed rate class        |
|      Diversifying selection       |     3.884     |   39.751    |                                   |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.000               |    70.119     |                                   |
|               3.268               |     0.000     |       Not supported by data       |
|               3.347               |    29.881     |       Collapsed rate class        |

### Performing the constrained (dN/dS > 1 not allowed) model fit
* Log(L) = -3785.27, AIC-c =  7639.02 (34 estimated parameters)
* For *test* branches under the null (no dN/dS > 1 model), the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   39.918    |                                   |
|        Negative selection         |     1.000     |    8.835    |                                   |
|         Neutral evolution         |     1.000     |   51.247    |       Collapsed rate class        |

* The following rate distribution for site-to-site **synonymous** rate variation was inferred

|               Rate                | Proportion, % |               Notes               |
|-----------------------------------|---------------|-----------------------------------|
|               0.000               |    75.197     |                                   |
|               4.032               |    24.803     |                                   |
|               4.695               |     0.000     |       Not supported by data       |

----
## Branch-site unrestricted statistical test of episodic diversification [BUSTED]
Likelihood ratio test for episodic diversifying positive selection, **p =   0.0001**.

**Comment by spond** [comment]
Dear @JinqunHuang,

BUSTED fits a **distribution** of dN/dS values to your alignment. Using a single dN/dS is suboptimal since very few genes have **on average** dN/dS > 1 (see section 1.4.2 in http://hyphy.org/resources/hyphybook2007.pdf). In your case, refer to the following part of the results:

-----

### Performing the full (dN/dS > 1 allowed) branch-site model fit
* Log(L) = -3777.03, AIC-c =  7624.57 (35 estimated parameters)
* For *test* branches, the following rate distribution for branch-site combinations was inferred

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    7.932    |                                   |
|        Negative selection         |     0.000     |   52.317    |       Collapsed rate class        |
|      Diversifying selection       |     3.884     |   39.751    |                                   |

-----

The analysis tells you that while about 60% of your gene is under very strong **purifying selection** (dN/dS = 0), the remaining ~40% evolve under **diversifying selection**. This is where the significant test result comes from. It is also quite instructive to note that the **mean** dN/dS (inferred under a simple model) of 0.82, is **not** the same as the distributional mean of the BUSTED analysis (~0*0.6 + 3.88 * 0.4 = 1.55), because the models weigh the contributions of individual sites very differently.

Take a look at the BUSTED section (page 6) in http://hyphy.org/resources/tutorial-2017.pdf for more background.

Best,
Sergei

**Comment by JinqunHuang** [comment]
Dear Sergei,
Thanks for your information !! It help me a lot !
I build the conding sequence tree by iqtree(version 1.6.6) with  or without "-b 1000"(with "-b 1000" the confidence was very low, shown as below)，and I got different result form BUSTED results.

I try to figure out which software and which type or parameters would be recommended to build the tree before Hyphy. Do I need to build the protein sequence(may be the protein sequence tree will get more confidence) tree as the input for Hyphy?
Would you have any advice ? 

Best,
JinQun Huang

![image](https://user-images.githubusercontent.com/47139043/89970402-5ef68300-dc8b-11ea-83fa-3215d5f45fd8.png)

**Comment by spond** [comment]
Dear @JinqunHuang,

I don't understand your question: which results are different? Whatever tree topology you supply to `BUSTED` (e.g. via the `--tree` argument), will be taken as is. The output topology may be **rooted** differently, but that doesn't change the results.

Best,
Sergei

**Comment by JinqunHuang** [comment]
Dear @spond Sergei,

Thanks again for you response.

I supply two tree (with and without "-b 1000") to BUSTED, and I get different results from BUSTED(shown as below).

The "dN/dS and Proportion" was different. The rest of the information is the same in both files.

From the information you repley yestday, I can get the positive selected gene family from BUSTED instead of the DN/DS value.
Under this goal, I wonder are there any problems in the logs(show as below) and should  I get a more confidence tree to supply to BUSTED ?

Best,
JinQun Huang

[with-b1000-BUSTEDResult.log](https://github.com/veg/hyphy/files/5061049/with-b1000-BUSTEDResult.log)
[without-b1000-BUSTEDResult.log](https://github.com/veg/hyphy/files/5061050/without-b1000-BUSTEDResult.log)

[1.cds.muscle.phy.txt](https://github.com/veg/hyphy/files/5061056/1.cds.muscle.phy.txt)
[IQtreeMFP-with-b1000.contree.txt](https://github.com/veg/hyphy/files/5061062/IQtreeMFP-with-b1000.contree.txt)
[IQtreeMFP-without-b1000.contree.txt](https://github.com/veg/hyphy/files/5061063/IQtreeMFP-without-b1000.contree.txt)

**Comment by spond** [comment]
Dear @JinqunHuang,

The log likelihoods and the p-value from are the same for both trees (no selection); the estimates come out different because you have a small **low information** dataset (e.g. the branch lengths in your tree are minuscule), meaning that the individual rates are estimated imprecisely. One option is to reduce model complexity by specifying the `--rates 2` option when you execute the analysis, but for data with such low diversity/divergence, you are not going to obtain **precise** estimates.

Best,
Sergei
