### ISSUE TITLE
Masked sequences in aBSREL

### ISSUE THREAD

**Issue by markcharder** [veg/hyphy#1200]
Dear authors,

I'm sorry if I missed this anywhere in the documentation.

I've been running and comparing tests from PAML and HyPhy. I am most interested in using aBSREL. 

To use PAML, I masked poor quality alignment sections using a program called 'SWAMP' ([https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4251194/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4251194/)). This masks part of some sequences in the alignment that may be problematic with 'N's.

I was just wondering if I could get a feel for how this might affect the results of analyses in HyPhy, such as aBSREL? Is it advisable to just forget about any alignments with problematic sequences in them?

Many thanks.
Mark

**Comment by spond** [comment]
Dear @markcharder,

The ultimate decision is up to you, but `N`s are basically missing data, so the worst that should happen is loss of power. One caveat you should be aware of is that if there are too many `N` characters, HyPhy will autodetect FASTA and some other files as amino-acid data (since `N` is a valid amino acid). To get around it, you may need to save your files as NEXUS as specify the datatype as `DNA`:

```
BEGIN CHARACTERS;
	FORMAT
		DATATYPE = DNA
		GAP=-
		MISSING=?
	;
....
```

My personal recommendation would be to conduct a sensitivity analysis with and without masking to see how much of the signal is driven by "problematic" sites. Alignment maskers sometimes do more harm than good or have little effect (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4137709/)

Best,
Sergei
