### ISSUE TITLE
Not all the sequences make it into the analysis

### ISSUE THREAD

**Issue by ThomasDesvignes** [veg/hyphy#1203]
Dear developers,

I have been trying to run some analyses using aBSREL and RELAX on the Datamonkey webserver and all went totally fine, but now that I'm looking at the results in detail I'm realizing that often one sequence (or even up to 10 out of 40 for one file

) doesn't get analyzed, as if it doesn't get loaded for analysis. For example (attached) I have 28 sequences in my dataset but the results report the analysis of only 27 sequences (one sequence Akarotaxis_nudiceps is not analyzed). I've carefully verified my files and everything looks fine (FASTA sequential with the tree at the end in txt format with all leaf names matching the sequences names). Is there something wrong in the way I prepared my files?

Thanks a lot in advance,
Thomas

**Comment by spond** [comment]
Dear @ThomasDesvignes,

See issue #1181. Check to confirm that the "missing" sequences are identical to others in the alignment file.

Best,
Sergei

**Comment by ThomasDesvignes** [comment]
Dear Sergei,

Thanks a lot for your reply. Yes, indeed, the missing sequence(s) are identical to other sequences in the alignment file. However, they originate from different species so shouldn't they be kept for the analysis because two identical sequences in two related species could potentially inform on strength of selection at these branches with aBSREL or in a subtree vs another subtree with RELAX? I understand the removing of internal branches that have a zero length but I'm not sure I see the point with removing leafs. Is there a way to bypass that filtering?

Thank you!
Thomas

**Comment by spond** [comment]
Dear @ThomasDesvignes,

There are two assumptions made for filtering sequences

1. Identical sequences in an alignment **should** appear as a cherry (or a subtree of all identical sequences). This would happen with any sensible inference approach. For example, `C` and `D` in the following tree.

```
((A,E),B,(C,D))
```

2. For **any** model that is currently available in Datamonkey, the maximum likelihood estimate of branch length on C and D will be 0, meaning that the tree above is equivalent to 

```
((A,E),B,C) 
```
or
```
((A,E),B,D)
```

3. Because of this keeping additional sequence is not in any way informative.

If identical sequences are **not** together in the tree (say A and D), then the assumptions do break down, but then the question becomes: why are A and D not together? You can probably see something like this happening if you use species trees for gene evolution and you have convergence/homoplasy, but that's quite rare.

Are identical sequences together in your tree?

Best,
Sergei

**Comment by ThomasDesvignes** [comment]
Thanks for these extra details. Yes, indeed, in the few cases I just looked at right now, each time the identical sequences would be closely related in the tree, although not always exactly sister-species.

I can imagine that for aBSREL this shouldn't be an issue, but I'm wondering if removing leafs for the RELAX test could modify the signal we would be able to detect. For example, in one case I have a tree like this:
((A,G),B,(C,(D,(E,F)))) and the sequences for C, D, E and F are identical so the tree gets reduced to ((A,G),B,C). But if I what I want to test with RELAX is the evolution in C, D, E and F subtree compared to A, G, and B, then reducing the tree would leads to loss of signal, wouldn't it? If I keep the original tree, then I may have for ex that purifying selection was strong among C-F compared to A, G and B, but if I have the reduced tree then I will likely loose this phylogenetic signal because the test doesn't know anymore that actually C represents 4 species and that evolution occurred at the branch between B and C and not on the terminal branch to C, or does it?

Thanks a lot!
Thomas

**Comment by spond** [comment]
Dear @ThomasDesvignes,

Any zero-length branch contributes exactly 0 information to the estimate of substitution rates (dN/dS etc), other than to the fact that those branch lengths are 0. Because no evolution occurred along a zero-length branch, there is no information about the substitution process there. It's conceptually like "phylogenetically uninformative" sites. The only useful information there is that branch lengths are exactly 0.

You should get exactly the same likelihood (and exactly the same estimates) with the 4 identical sequences or a single collapsed sequence. 

Best,
Sergei

**Comment by ThomasDesvignes** [comment]
Dear Sergei,
Thank you for the precision! Indeed a branch length of 0 can't be used to estimate any dN/dS. I guess it's then on me to notice that some sequences have been collapsed and potentially interpret this.
Thank you so much for all these information!
Best,
Thomas

**Comment by spond** [comment]
Dear @ThomasDesvignes,

Happy to help. We should provide feedback to the user about collapsed sequences though (Datamonkey classic used to do that...). Tagging @stevenweaver and @stephenshank .

Best,
Sergei

**Comment by ThomasDesvignes** [comment]
That would be a great idea. Especially it might also be possible (if the user provides their own tree) to see whether the sequences that are collapsed are sister species or not, which would then allow you to flag potential cases of convergent evolution you were mentioning earlier.
Thanks again. The HyPhy tests are really useful!
Best,
Thomas

**Comment by stevenweaver** [comment]
Dear @ThomasDesvignes, 

Having this kind of feedback is rare and valued. That's a great design idea. Technically, it should be relatively straight-forward to implement. 

Best,
Steven

**Comment by ThomasDesvignes** [comment]
Glad to be able to help back!
