### ISSUE TITLE
aBSREL "test not run" on some leaf 

### ISSUE THREAD

**Issue by moveAFs** [veg/hyphy#1207]
1. I am running aBSREL analysis on a series alignment with "--branches" set to default (all branches to test), but in some case most the leaves in the tree were "test not run", did this influence the final conclusion of which node were under positive selection? Here I attached my json file.  [1.zip](https://github.com/veg/hyphy/files/5127184/1.zip)

2. In my case, positive selection were always detected in internal node (infer as "parent node"), while terminal leaves under this parent were not labeled as significant. So if I can say the terminal leaves under this branch were also positive selected?

**Comment by spond** [comment]
Dear @moveAFs,

Would it be possible to share the input file/tree and the exact command (how you called HyPhy) you used to generate the `JSON`? None of the leaf branches are showing as being tested, even though they seem to be selected in the branch partition record. I am not entirely sure why, so would like to investigate further.

Best,
Sergei

**Comment by moveAFs** [comment]
cause I have had cds and pep sequences, I called hyphy as below:
```shell
# generate pep alignment using mafft
mafft --auto --anysymbol AT4G23700.2_ath.asterids.pep > AT4G23700.2_ath.asterids.pep.mafft

# build gene tree based on pep alignment using iqtree2 software
iqtree2 -s AT4G23700.2_ath.asterids.pep.mafft --prefix AT4G23700.2_ath.asterids.pep.mafft -m MFP  
# here generate tree file named AT4G23700.2_ath.asterids.pep.mafft.treefile

# align cds sequences based on pep alignment
/share/app/software/hyphy-2.5.17/hyphy \
    LIBPATH=/share/app/software/hyphy-2.5.17/res /share/app/software/hyphy-analyses/codon-msa/post-msa.bf \
    --protein-msa AT4G23700.2_ath.asterids.pep.mafft \
    --nucleotide-sequences AT4G23700.2_ath.asterids.cds \
    --output AT4G23700.2_ath.asterids.cds.msa.fas \
    --compress No

# do absrel test on these files
/share/app/software/hyphy-2.5.17/hyphy \
    LIBPATH=/share/app/software/hyphy-2.5.17/res absrel \
    --alignment AT4G23700.2_ath.asterids.cds.msa.fas \
    --tree AT4G23700.2_ath.asterids.pep.mafft.treefile
```
input files as well as other generated files are attached here [all_files.zip](https://github.com/veg/hyphy/files/5133654/all_files.zip)

**Comment by spond** [comment]
Dear @moveAFs,

This is a subtle issue with name mapping. Internally, `HyPhy` converts sequence names that contain dots and some other characters into valid identifiers, e.g. : `evm.model.chr9.757_AV.off` to `evm_model_chr9_757_AV_off`. Normally you don't have to worry about this because scripts take care of it behind the scenes. What is happening here is that your **tree** (generated in step 2) has names like `evm.model.chr9.757_AV.off`, but your codon-aware alignment (generated in step 3), does not. When you feed discordant names (one set in the alignment, another in the tree), leaves with `.` in their names are skipped from analysis. A simple solution is to swap steps 2 and 3 in your pipeline (run `iqtree` on the output of `post-msa`).

Best,
Sergei
