### ISSUE TITLE
GARD recombination test - alignment with 3bp del

### ISSUE THREAD

**Issue by marisoldominguez** [veg/hyphy#1231]
Hi all,

I am trying to run (and interpret the results) selection and recombination tests (in https://www.datamonkey.org) for a group of codifying nucleotide sequences. Most of the sequences are 276 bp long but four out of 23 have a 3-bp deletion (that does not produce a frame shift) so they are 273 nt long. This means that my alignment translates in sequences of 92 or 91aa. I was wondering if having sequences of different lengths could be a problem but the selection tests (SLAC, FEL, FUBAR and MEME) run beautifully. 
When I test for recombination I got an error and it does not run. It  runs when I erase those 4 nucleotidic sequences with the deletion (it has been running now for 1h30m). I would like to make it run with the complete set of sequences... so my question is: Is it possible to run GARD when some sequences have a deletion? I prepared the fasta file containing the alignment in Bioedit... should I change the code for the gap (currently ---) in order to be recognized as a deletion by HyPhy? 

I would really appreciate some light here...
Thanks in advance,

Marisol

**Comment by marisoldominguez** [comment]
job running in https://www.datamonkey.org/gard/5f7ee8509adf224520f94e38

**Comment by spond** [comment]
Dear @marisoldominguez,

I recommend that you run these data through GARD as nucleotides. GARD will recognize gaps (`-`) and handle them appropriately. What error did you see?

Best,
Sergei 

PS the results on 19 sequences run as nucleotides are here https://www.datamonkey.org/gard/5f8068049adf224520f98b95

**Comment by marisoldominguez** [comment]
Dear @spond ,

Many thanks for your response. Indeed I was running a nucleotide alignment. I found what the problem was: apparently the symbol **~** that BioEdit uses to determine the site of a deletion was not being recognized. So I changed it to **-** and saved it again as a fasta file in MEGA. 

Would you please help me interpret this results? This is avian MHC-I gene data and I am checking if there are recombination fragments before doing selection tests to avoid false positives.


![Result](https://user-images.githubusercontent.com/69967644/95612514-ccdce200-0a63-11eb-80a1-e3dd94c0712b.jpg)

there seems to be recombination but I can not access any test or p-value? (the topological incongruence report is empty). It divides the three in 2 segments (1-164 and 165-276) but how can I know which alleles correspond to those segments?

I ran the program under the following options: 
Data type: nucleotide
Genetic code: Universal
Site-to-Site Rate Variation: none
Rate classes: 2

Many thanks again for your time.
Kind regards,
Marisol

**Comment by spond** [comment]
Dear @marisoldominguez,

The topological incongruence report is not empty -- it gives you specific explanation of what the test result is (a two partition model is preferred to a one-partition model). 

If you wish to see which sequences may be involved in the recombination events (something GARD is not really designed to do), you may want to look at RDP4, or inspect the trees that GARD produces. 

The standard way to utilize GARD results is to take partitioned data and supply them as input to selection analyses, so that recombination does not confound selection analyses.

Best,
Sergei

<img width="207" alt="Untitled" src="https://user-images.githubusercontent.com/1018513/95620495-46fa7000-0a3e-11eb-9eb6-4973ac8aa61d.png">
