### ISSUE TITLE
Unable to load whole genome nt. in FEL

### ISSUE THREAD

**Issue by takim27** [veg/hyphy#1243]
HI 
Im trying to find out positive selection at certain sites of  Corona virus whole genome. As I aligned less then 10 whole genome sequence based on their codons and tried to load it in the FEL .But It states as follows :

 "The number of nucleotide columns in the data set must be divisible by 3 - had 30362 sites. Please check that the reading frame is aligned with the beginning of the data set and that no trailing sites are extraneous." 

and another question is If I find stopcodons between sequences how can I clean it without using any command line .
 thanks in advance .

**Comment by spond** [comment]
Dear @takim27,

You need to perform a codon-aware alignment (https://bioinformatics.stackexchange.com/questions/997/which-sequence-alignment-tools-support-codon-alignment). What did you use to align the genomes?

Best,
Sergei

**Comment by takim27** [comment]
I used MEGA X

**Comment by spond** [comment]
Dear @takim27,

There are two possibilities where the stop codons may be sneaking in.

In step 2, if you translate nucleotide sequences that **have** stop codons into amino-acids, they will probably be still be in the sequences as `X` and propagate all the way down into your final alignment. You might want to check for that. 

In step 4, how are you mapping codons **back** onto amino-acids?

Additionally, for nCoV you also have a frameshift due to polymerase slippage between ORF1a and ORF1ab, so you need to account for that during the alignment. 

We have our own workaround described in https://github.com/veg/hyphy-analyses/tree/master/codon-msa which you could try.

Best,
Sergei
