### ISSUE TITLE
Is it necessary to use TrimAI before import the alignment?

### ISSUE THREAD

**Issue by HamletShaoE** [veg/hyphy#1255]
Hi, I was using MAFFT to do the multiple sequence alignment on protein level and reverse translate the alignment into CDS. However, since the divergence of my sequence is a little bit wide, there are many gaps among the alignment. This means that some sites are only consists of a small proportion of sequences and some sequences are aligned in a small proportion of 'well-aligned' sites (this is defined by TrimAI). I suppose that a trimmed alignment would be a better input, because it consist of those sites with most of the sequences overlapped and only those sequences that overlap with most of the others. Here is the trimAI command I used. 
`trimal -automated1 -in ${gene}.cds.picked.mafft.fasta -resoverlap 0.75 -seqoverlap 85 -out ${gene}.cds.picked.mafft.trimal.fasta  -htmlout ${gene}.cds.picked.mafft.trimal.html -colnumbering > ${gene}.cds.picked.mafft.trimal.col`
However, I wonder whether this TrimAI pre-process is necessary? 
Could Hyphy deal with those gapped sites and sequences? Do those gapped sites and sequences inclufluence the results? 
If so, is it making it more sensitive or just noise-sensitive? Which result is more like making sense?
I am now using FEL, FUBAR and SLAC. Are they affected by this pre-process step? How about other methods?

**Comment by spond** [comment]
Dear @HamletShaoE,

There are no general guarantees when it comes to the effect of alignment quality. HyPhy treats gapped columns as partially missing data: if you have 100 sequences but only 5 have non-gaps at a particular column, the information content at that column is ~5 sequences. Correspondingly, you will not be able to make precise inferences and lose power. The expected result is that you will find very little selection signal at "gappy" sites. 

Poor quality alignments can also sometimes bring characters that are not homologous together -- this is a more dangerous situation for selection analyses, because it will create false signal of diversification.

I would recommend, in your situation, to perform a simple sensitivity analysis, where you feed raw and trimmed (with different settings) alignments through selection tools, and see if you obtain dramatically different results. If not, then you can stick with using untrimmed alignments as input. 

Best,
Sergei

**Comment by HamletShaoE** [comment]
Thank you
