### ISSUE TITLE
HIV-Trace does not work

### ISSUE THREAD

**Issue by mariya-vs** [veg/hyphy#1256]
Hi, I want to use HIV-Trace in my research project, but keep getting an error: 502 Bad Gateway. All other tools (at datamonkey.org) work fine for me. Can someone assist me?

**Comment by jzehr** [comment]
Dear @mariya-vs,

Thank you for your interest in our tools. We are aware of the HIV-TRACE issue, and are working to resolve it. 

I will keep you posted with updates/progress with these efforts. 

Best,
Jordan

**Comment by spond** [comment]
Dear @mariya-vs,

Due to research prioritization, we currently don't have developer resources to quickly address the issue (HIV-TRACE application has a memory leak issue which affects all Datamonkey.org services), hence we have taken it offline temporarily. 

You can run **all** of your HIV-TRACE analyses using a command line tools (http://github.com/veg/hivtrace) and visualize the results using http://github.com/veg/hivtrace-viz. If you need help with how to use those, please let us now.

Best,
Sergei

@stevenweaver @stephenshank
