### ISSUE TITLE
pairwise sequence dN dS values

### ISSUE THREAD

**Issue by bioinfowheat** [veg/hyphy#1273]
Hello,

I'm looking for a quick and accurate way to just estimate dN and dS for two sequences of CDS sequence.

I have 9000 of these fasta files (one per locus), from orthologs of two species. I want to estimate evolutionary distance between 2 species for each sequence, so I can compare a focal group to the global distribution. If you have better suggestions, I'm totally open. Before I code all this through PAML, which is rather clunky, I was hoping there was a more straight forward command line approach I could use in hyphy, which might be something like 

hyphy -i pairwise.bf --alignment human_chimp.fasta --code Universal --output human_chimp.out

**Comment by spond** [comment]
Dear @bioinfowheat,

If you have an alignment with two sequences, the simplest way to get pairwise estimates would be using the `FitMG94.bf` analysis from https://github.com/veg/hyphy-analyses/tree/master/FitMG94 

```
hyphy /path/to/FitMG94.bf --alignment /path/to/2.fas --tree neighbor-joining --output /path/to/2.json
```

`/path/to/2.json` will have a lot of details on the fit result and is a `JSON` file. In particular you will see something like 

```
"Standard MG94":{
     "AIC-c":3069.060099885265,
     "Confidence Intervals":{
       "non-synonymous/synonymous rate ratio":{
         "LB":0.05932492302024387,
         "UB":0.09858175408945982
        }
      },
     "Log Likelihood":-1517.976078455871,
     "Rate Distributions":{
       "Substitution rate from nucleotide A to nucleotide C":1.654785163501859,
       "Substitution rate from nucleotide A to nucleotide G":1,
       "Substitution rate from nucleotide A to nucleotide T":0.4123593781163388,
       "Substitution rate from nucleotide C to nucleotide G":0.920591030862722,
       "Substitution rate from nucleotide C to nucleotide T":1.083971553866486,
       "Substitution rate from nucleotide G to nucleotide T":0.4226548876413209,
       "non-synonymous/synonymous rate ratio":0.07708666449963816
      },
     "display order":1,
     "estimated parameters":16
    }
  }
```

The point estimate of dN/dS is `"non-synonymous/synonymous rate ratio" : 0.07708666449963816` and the confidence interval is reported in 
```
"Confidence Intervals":{
       "non-synonymous/synonymous rate ratio":{
         "LB":0.05932492302024387,
         "UB":0.09858175408945982
        }
      }
```

You can read `JSON` with Python/R etc or you can use `jq` (a very powerful command line tools to extract values). For example if you all you care about is the dN/dS estimate for a bunch of files you can do something like (with pathnames adjusted of course)

```
hyphy FitMG94.bf --alignment /Users/sergei/Desktop/2.txt --tree neighbor-joining --output pairwise.json >/dev/null; jq '.["fits"]["Standard MG94"]["Rate Distributions"]["non-synonymous/synonymous rate ratio"]' pairwise.json
```

Best,
Sergei

**Comment by bioinfowheat** [comment]
yes yes YES!!!!

wonderful …. feels like Christmas! thanks a ton for the excellent details on the command and json parsing.

is only the ratio estimated, or is it possible to also extract the dN and dS values independently?

**Comment by spond** [comment]
Dear @bioinfowheat,

Not quite `dN` and `dS`. HyPhy estimates the ratio directly. You can compute dN and dS after the fact. Would you like me to add that option to `FitMG94.bf`?

Best,
Sergei

**Comment by bioinfowheat** [comment]
morning Sergei,

yes please

being able to have dN and dS does help with studies of evolutionary rate, and assessing saturation, etc. 

This would be useful for more people than just me. The current script plows through 9000 alignments very quickly.

**Comment by spond** [comment]
Dear @bioinfowheat,

Will ping when ready. Currently the analysis can output synonymous and non-synonymous branch lengths, but this is not quite what you are after: they need to be normalized by the synonymous and non-synonymous site counts/expectations.

Best,
Sergei

**Comment by spond** [comment]
Dear @bioinfowheat,

With release 2.5.27 and an update to `FitMG94.bf` you will now see `dS` and `dN` estimates in the output JSON:

```
 "branch attributes":{
   "0":{
     "1":{
       "original name":"1"
      },
     "2":{
       "Nucleotide GTR":0.03495399697273924,
       "Standard MG94":0.03831987926385826,
       "dN":0.01730356559140539,
       "dS":0.1080116852362222,
       "nonsynonymous":0.01329447397375527,
       "original name":"2",
       "synonymous":0.02502540529010305
      },
    ...
    },
```

Best,
Sergei

**Comment by ts-dangelo** [comment]
I am having trouble running this command in v2.5.65. I copied the template batch file from https://github.com/veg/hyphy-analyses/blob/master/FitMG94/FitMG94.bf.  When I run i get this error:

Error:
Could not read command file from 'libv3/all-terms.bf' (expanded to '/home/tdangelo/libv3/all-terms.bf') in call to LoadFunctionLibrary("libv3/all-terms.bf", /home/tdangelo/);

I created that directory and copied batch files in to it and could not find them because it was adding another libv3 directory to the address.

I then manually changed the location of the TemplateBatchFiles in the bf to where they are located on the remote server I am using and I get a similar error:

LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/all-terms.bf"); 
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/UtilityFunctions.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/IOFunctions.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/tasks/estimators.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/tasks/alignments.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/tasks/trees.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/models/codon/MG_REV.bf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/SelectionAnalyses/modules/io_functions.ibf");
LoadFunctionLibrary("/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/SelectionAnalyses/modules/selection_lib.ibf");


Error:
Could not read command file from 'libv3/UtilityFunctions.bf' (expanded to '/mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/libv3/UtilityFunctions.bf') in call to LoadFunctionLibrary("libv3/UtilityFunctions.bf", /mnt/modules/bin/hyphy/2.5.64/share/hyphy/TemplateBatchFiles/libv3/);

It seems the LoadFunctionLibrary is not merging the directories correctly, as there are two libv3 directories in that address, though those files do exist in the directory the LoadFunctionLibrary is pointed to. 

I tried setting the LIBPATH variable and that did not change anything.

Thank you

**Comment by spond** [comment]
Dear @ts-dangelo,

Did this behavior emerge with `2.5.65` only?

What are you setting your `LIBPATH` value to and where do the files actually exist. Make sure they are readable as well, e.g. `cat /path/to/.../libv3/all-terms.bf`?

`libv3` is expected to exist inside `{LIBPATH}/TemplateBatchFiles/` 

Best,
Sergei

**Comment by ts-dangelo** [comment]
Hi Sergei,Thank you for your quick response. Version 2.5.65 is the only version I’ve used. It was downloaded off anaconda earlier today. Setting the libpath location does not solve the problem. It seems that the library loading function is not receiving the libpath variable from the command line. This issue is on a remote Linux server and the IT department at my institution also could not get the libpath variable to change.Regards,TimOn Dec 18, 2024, at 3:57 PM, Sergei Pond ***@***.***> wrote:﻿
Dear @ts-dangelo,
Did this behavior emerge with 2.5.65 only?
What are you setting your LIBPATH value to and where do the files actually exist. Make sure they are readable as well, e.g. cat /path/to/.../libv3/all-terms.bf?
libv3 is expected to exist inside {LIBPATH}/TemplateBatchFiles/
Best,
Sergei

**Comment by spond** [comment]
Dear @ts-dangelo,

What is the exact command that you are using to call `hyphy`, and what is the exact path where `TemplateBatchFiles/libv3` is located?

Best,
Sergei

**Comment by ts-dangelo** [comment]
Hi Sergei,

Here is the information you requested, thank you.

hyphy --version
HYPHY 2.5.64(MP) for Linux on x86_64 x86 SSE4 SIMD zlib (v1.3.1)

template files location:

 /mnt/modules/bin/hyphy/2.5.64/share/hyphy/

 ls

drwxrwxr-x  2 tkc tkc  4096 Dec 18 13:07 data
drwxrwxr-x 12 tkc tkc 12288 Dec 18 13:07 TemplateBatchFiles
drwxrwxr-x  7 tkc tkc  4096 Dec 18 13:07 SubstitutionModels
drwxrwxr-x  6 tkc tkc  4096 Dec 18 13:07 SubstitutionClasses
drwxrwxr-x  2 tkc tkc  4096 Dec 18 13:07 GeneticCodes


FitMG94.bf copied directly from:
https://github.com/veg/hyphy-analyses/blob/master/FitMG94/FitMG94.bf

command:

hyphy /home/tdangelo/FitMG94.bf --alignment long_comp_all.codon.fna --tree
neighbor-joining long_comp_FitMG94.json
LIBPATH=/mnt/modules/bin/hyphy/2.5.64/share/hyphy/

Analysis Description
--------------------
Fit an MG94xREV model with several selectable options frequency
estimator and report the fit results including dN/dS ratios, and
synonymous and non-synonymous branch lengths. v0.2 adds LRT test for
dN/dS != 1. v0.3 adds LRT test support for dN/dS != 1 for local models.
v0.4 adds the lineage option

- __Requirements__: in-frame codon alignment and a phylogenetic tree

- __Written by__: Sergei L Kosakovsky Pond

- __Contact Information__: ***@***.***

- __Analysis Version__: 0.4

rooted: No
type: global

>code => Universal
/home/tdangelo/EPC_prelim/big_aerophobota_cluster_work/neighbor-joining
neighbor-joining

>Loaded a multiple sequence alignment with **2** sequences, **271217**
codons, and **1** partitions from
`/home/tdangelo/EPC_prelim/big_aerophobota_cluster_work/long_comp_all.codon.fna`
Error:
Failed to dereference 'fitter.filter.default.site_map'

Function call stack
1 :  [namespace = ZKxpKjHs]
this_filter[utility.getGlobalValue("terms.data.coverage")]=utility.DictToArray(utility.Map(utility.Filter(^(this_filter[utility.getGlobalValue("
terms.data.name
")]+".site_map"),"_value_","_value_%3==0"),"_value_","_value_$3"));
Standard input redirect:
000000000001 : long_comp_FitMG94.json

-------
2 :  [namespace = fitter]
filter_specification=alignments.DefineFiltersForPartitions(partitions_and_trees,datasets,"`prefix`.filter.",codon_data_info);
Standard input redirect:
000000000001 : long_comp_FitMG94.json

-------
3 :  [namespace = fitter]
load_file({utility.getGlobalValue("terms.prefix"):"fitter",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"selection.io.SelectAllBranches"}});
Standard input redirect:
000000000001 : long_comp_FitMG94.json

-------
4 :  namespace

Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf",
/home/tdangelo/);

Step 1.Branch under condition 'model_type==^"terms.fitter.partitioned"'
to
load_file({utility.getGlobalValue("terms.prefix"):"fitter",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"selection.io.SelectAllBranchSets"}});
else
load_file({utility.getGlobalValue("terms.prefix"):"fitter",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"selection.io.SelectAllBranches"}});

Step
2.load_file({utility.getGlobalValue("terms.prefix"):"fitter",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"selection.io.SelectAllBranchSets"}});

Step 3.Go to step 5

Step
4.load_file({utility.getGlobalValue("terms.prefix"):"fitter",utility.getGlobalValue("terms.settings"):{utility.getGlobalValue("terms.settings.branch_selector"):"selection.io.SelectAllBranches"}});;
Standard input redirect:
000000000001 : long_comp_FitMG94.json

-------


contents of error file:

Error:Failed to dereference 'fitter.filter.default.site_map'
Failed to dereference 'fitter.filter.default.site_map'


At Step 0.LoadFunctionLibrary("SelectionAnalyses/modules/shared-load-file.bf",
/home/tdangelo/); it seems that it is not recieving the LIBPATH argument
from the command line,
because it is referencing my home directory, not the LIBPATH

Thanks,
Tim

**Comment by ts-dangelo** [comment]
Hi Sergei,

I found additional information from your responses on github to this issue,
I have added ENV="USE_MEMORY_SAVING_DATA_STRUCTURES=1e10", and it now
works. Sorry for not doing more troubleshooting before emailing!

Thank you for your quick responses, Hyphy is a great program !

Tim
