### ISSUE TITLE
 Do we need to check for recombination in selection analysis, if we have already species tree available? #78 

### ISSUE THREAD

**Issue by AswinSSoman** [veg/hyphy#1275]
I want to do a selection analysis using hyphy. Since I have a species tree available from the literature, I don't need to build a tree using any phylogenetic methods.
Since the effect of recombination is in the phylogenetic tree inference methods from MSA if we have a species tree available (independent of MSA), will the presence of recombination still affect the selection inference? 

regards,
Aswin

**Comment by spond** [comment]
Dear @AswinSSoman,

Take a look at https://www.sciencedirect.com/science/article/abs/pii/S0169534701022030 

You typically analyze a gene for positive selection, whereas the species tree refers (loosely) to the genome-wide tree. Many or even most genes will follow the species tree, but there are also many that don't.

In addition, you can have recombination events that occur within individual genes (e.g. due to gene conversion, etc).

Short answer: you should always consider inferring a gene-specific tree for selection analysis **and** screen for recombination, unless your organism doesn't recombine (e.g. mtDNA is thought to the recombination free etc).

Best,
Sergei

**Comment by AswinSSoman** [comment]
Thank you @spond 

Finally, I want to that know if we assume that:

1. The MSA has recombinant sequences.
2. But we have an accurate phylogeny for the entire alignment.
3. However, we haven't checked the MSA for recombination and no further splitting the sequences for separate selection inference.  

Will the presence of recombination in the MSA affect the estimation of 'ω'?
