### ISSUE TITLE
Repetitive error with absrel

### ISSUE THREAD

**Issue by QiaoyiLiang** [veg/hyphy#1278]
Dear all,

I'm new to the datamonkey tools and tried to run a few jobs with the similar alignment on the absrel webserver. Unfortunately I kept encountering this "HYPHYMPI terminated" error and it was not so intuitive to for me troubleshoot. Could anyone give me some help? This is the link to the error message of my job - 

http://datamonkey.org/absrel/601aee9ed83df369d29ac698

Thanks a lot!

Qiaoyi

**Comment by stevenweaver** [comment]
Dear @QiaoyiLiang, 

If you click on [Download Log](http://datamonkey.org/absrel/601aee9ed83df369d29ac698/log.txt), it will display the error from HyPhy. 

The error here seems to be a core error within HyPhy's Optimize function. 

```
Error:

Master node received an error:Internal error 
 
	ERROR: [_LikelihoodFunction::LocateTheBump (index 90) current value   -148446.0239738932 (parameter =   0.9993584395344067), best value   -148446.0239738932 (parameter =   0.9993584395344067)); delta = 2.91038304567337e-11, tolerance = %20.16]



Parameter name RWqniejL.tree_0.ORYZIAS_LATIPES_T1R1_NM_001104722_1.omega2

Function call stack
1 :  Optimize(absrel.null.mles, ^absrel.likelihood_function_id);

-------
```

We will investigate shortly. 

Best,
Steven

**Comment by QiaoyiLiang** [comment]
Dear @stevenweaver,

Thank you so much for your quick response and taking your time to look into it!

I have also checked the log files of other runs and they all encountered issues at the same spot. I also checked this sequence and it seems fine to me. 

Best,
Qiaoyi

**Comment by spond** [comment]
Dear @QiaoyiLiang,

Unable to replicate your issue in command line HyPhy (2.5.27). Results for the analysis attached (decompress and view at vision.hyphy.org/absrel). We will check to see if the issue you are seeing is due to an older version of HyPhy deployed to Datamonkey.

Best,
Sergei

[seqs.fasta.ABSREL.json.zip](https://github.com/veg/hyphy/files/5928490/seqs.fasta.ABSREL.json.zip)

**Comment by QiaoyiLiang** [comment]
Dear @spond ,

Thank you for testing this issue! I am a bit confused with your analysis result because the one I tried to run has 81 sequences but not 26. Was it a subset of sequences or a different run?

Many thanks,
Qiaoyi

**Comment by spond** [comment]
Dear @QiaoyiLiang,

The results are for 81 sequences. **26** is the number of branches where some signal for selection was found.

Best,
Sergei

**Comment by QiaoyiLiang** [comment]
Hi @spond,

I have installed hyphy 2.5.29 on our cluster and ran absrel with new sets of alignments but it always failed when calculating likelihood. Could you help to check what's the problem and how I can troubleshoot this?

Thanks a lot!
Qiaoyi
[Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.ABSREL.log](https://github.com/veg/hyphy/files/6050171/Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.ABSREL.log)
[Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.txt](https://github.com/veg/hyphy/files/6050180/Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.txt)

**Comment by spond** [comment]
Dear @QiaoyiLiang,

Thanks for reporting the issue. I was able to reproduce it. This is caused by high numerical rounding errors that occur for some data; looks like it may be due to some long branches in the alignment (near saturation).

In any case, I made a change in the `develop` branch that allows you to get around the issue (you can download the branch and use it right away) with the following command

```
/hyphy absrel --alignment /path/to/file  ENV="TOLERATE_NUMERICAL_ERRORS=TRUE;"
```

The results for the `aBSREL` analyses are attached as well.

Best,
Sergei

[Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.txt.ABSREL.json.zip](https://github.com/veg/hyphy/files/6051863/Batch5_T1R12A2Ssharkcf_Additions_MAFFT_wtree_poly.txt.ABSREL.json.zip)

**Comment by QiaoyiLiang** [comment]
Dear @spond ,

Thank you so much and the change you made has solved my problem!

To better understand this issue, could you explain a bit more or point out where I can look into how the long branches affect absrel? Did it cause by the branch length which I artificially set to 1? But the same issue occurred even if there is no branch length given. Or did it cause by the alignment itself?

Thanks again!

Qiaoyi

**Comment by spond** [comment]
Dear @QiaoyiLiang,

The alignment itself; HyPhy always optimizes branch lengths -- it will take whatever values you set as initial guesses.

Best,
Sergei

**Comment by QiaoyiLiang** [comment]
Dear @spond,

Thanks for your quick reply. Does this alignment issue which affect the absrel result? If so could you give me any suggestion which I can use to check my alignments?

Best,
Qiaoyi

**Comment by spond** [comment]
Dear @QiaoyiLiang,

That's not necessarily a problem, but if you look at your data, seems like two sequences are on a very long branch (which could be saturated); this could be due to alignment issues or sequences that are too distantly related. 

Best,
Sergei

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1018513/110851327-e2f30680-827e-11eb-8437-1412908f01fe.png">

**Comment by QiaoyiLiang** [comment]
Dear @spond,

Thanks for the clear answer! I will look more into these sequences in my alignment.

Best,
Qiaoyi
