### ISSUE TITLE
RELAX group mode 

### ISSUE THREAD

**Issue by Edison2021** [veg/hyphy#1285]
Hi Sergei

I have four groups that were labeled as FG1, FG2, FG3 and FG4, and want to test if selection shift occurs among them (6 comparison pairs).

I suppose the invocation possibly looks like:
hyphy relax --alignment test.fas --tree test.tre  --mode Group test mode --test FG1, FG2, FG3, FG4 --reference-group FG1, FG2, FG3, FG4 

Is the invocation correct?

Best
Edison

**Comment by spond** [comment]
Dear @Edison2021,

The command as you specify is not going to run (because the `test` and the `reference` mode have to be different). You have two options.

1. Run the command `hyphy relax --alignment test.fas --tree test.tre --test ID1 --reference ID2` for each unique pair `(ID1,ID2)`; this will perform pairwise tests, one pair at a time.

2. Run the command `hyphy relax --alignment test.fas --mode "Group test mode" --tree test.tre --reference-group FG1` to perform an omnibus test. This means that the test if for any differences between groups, not any particular pair. In your case the null is that `K(FG1)=K(FG2)=K(FG3)=K(FG4)=1`, vs the alternative where  `K(FG2)` `K(FG3)` and `K(FG4)` are estimated separately.

There is no option that will execute pairwise analyses automatically within a single run.

Best,
Sergei
