### ISSUE TITLE
prrti model failing on newick string

### ISSUE THREAD

**Issue by lcwheeler** [veg/hyphy#1287]
Hello, 

I am running into an issue trying to run the pairwise ratio comparisons for a list of alignments. I want to determine if there is support for different dN/dS ratios between genes (i.e. like the models C and E in PAML/CODEML). I am using a newick format tree file (along with a set of alignments) that I have used for several other analyses with HyPhy including aBSREL and estimation of dN/dS with a single rate across all branches. For those analyses there was no issue. However, in this case I am getting the following error: 

Error:
Unexpected ',', in the following string context 9869719, <ERROR HERE> BRCU:0.00561034376158269909):0.0

I have tried reformatting the tree, including converting to nexus, but I continue to get these errors. I have also tried using a different tree generated in a different manner, with the same result. Interestingly, the supposed error is not always in the same part of the newick string. I don't think there is actually anything wrong with the formatting of the newick string, but I am not sure what else might be causing this problem. 

Thank you,

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Sorry, I am not sure what the `prrti` model is. Can you elaborate? What is the command line you are calling `HyPhy` with?

I probably will also need the input data (alignment / tree) to fully debug. 

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond,

Thanks for the quick response. I was actually calling this from the interactive command line application. It looks like the command line equivalent is given by hyphy prrti. "prrti 	Given a list of files (and optinally genetic code tables), perform relative ratio tests on all possible pair of the data files."

The sequence I have been running is: enter HYPHYMP on command line -> (17) Relative Ratio -> (2) Given a list of files (and optinally genetic code tables), perform relative ratio tests on all possible pair of the data files. -> (2):[Codon] Codon (several available genetic codes). -> (1):[Same Code] All files use the same genetic code. The index file contains file names only.  -> (1):[Universal] Universal code. (Genebank transl_table=1). -> enter the index file as requested, which yields the message "** All data files were read successfully **" -> enter tree file as requested   -> (MG94):Muse-Gaut 94 codon model. Local or global parameters. Possible Rate heterogeneity (and HM spatial correlation). -> (2):[Global] Model parameters are shared by all branches, branch lengths are estimated independently. -> enter output file name as requested.  

The error then arises immediately. 

If you need the alignments and trees, can I send them to you via a private email message? Also, it's worth noting that if I run this on a single pair of alignment files by choosing option "(1) Use relative ratio test on 2 datasets and a variety of standard models" under "(17) Relative Ratio" it does not throw this error, so it seems to be something going on only in the method that takes a list of files as input. However, it's not throwing an error related to the file list, but rather only to the tree file format. 

Thanks, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Ah, thanks for the clarification. It would be helpful if you could send me the test files to spond at temple edu

Some of these older analyses (like the one you are using) have not been updated in years, and may expose edge cases that are not compatible with the current HyPhy core. I appreciate your error report, and will take this opportunity to review the relative ratio analysis.

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond,

Thank you for looking into this issue. I sent a zip file with the test data to your email. 

Best, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Thanks very much for reporting this issue. It revealed several issues which I fixed in version 2.5.29 (currently in the `develop` branch, to be released later today).

The analysis runs on your example file. I am not sure that the analysis does what you want though.  Relative ratio tests ask a very specific question: are branch lengths in the trees of Gene1 and Gene2 proportionally related, so that

```
Tree1.node.length = C x Tree2.node.length
```

where `C` is estimated. It does **not** test for dN/dS ratio differences. You may want to take a look at  https://github.com/veg/hyphy-analyses/tree/master/BUSTED-compare for a direct test of difference in dN/dS.

For your four example genes, here's what you find.

#### Inferred gene-level distributions of dN/dS (BUSTED)

##### Gene 1

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |    1.396    |                                   |
|        Negative selection         |     0.086     |   97.800    |                                   |
|      Diversifying selection       |    12.712     |    0.804    |                                   |

##### Gene 2

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   15.981    |                                   |
|        Negative selection         |     0.076     |   73.068    |                                   |
|      Diversifying selection       |     3.030     |   10.951    |                                   |

##### Gene 3

|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.000     |   42.461    |                                   |
|        Negative selection         |     0.511     |   56.811    |                                   |
|      Diversifying selection       |    16.331     |    0.728    |                                   |

##### Gene 4


|          Selection mode           |     dN/dS     |Proportion, %|               Notes               |
|-----------------------------------|---------------|-------------|-----------------------------------|
|        Negative selection         |     0.049     |   84.217    |                                   |
|        Negative selection         |     0.327     |   15.714    |                                   |
|      Diversifying selection       |    116.799    |    0.070    |                                   |

##### Pairwise comparisons

Here, low p-values mean that the two genes have **different** dN/dS. High p-values mean we fail to reject the hypothesis that dN/dS are different (see [here](https://www.evidentlycochrane.net/teapots-and-unicorns-absence-of-evidence-is-not-evidence-of-absence/), for example). This does not mean that they are the same, just not detectably different with this test.

Looks like everything is quite different except for Gene1-Gene4 (no evidence) and Gene3-Gene4 (weak/marginal evidence, especially once you correct for multiple testing).

| File 1 | File 2 | p-value | 
|------|-------|--------|
|Gene1|Gene2| << 0.001|
|Gene1|Gene3|<< 0.001|
|Gene1|Gene4| 0.348    |
|Gene2|Gene3| 0.03|
|Gene2|Gene4| << 0.001|
|Gene3|Gene4| << 0.001|

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thank you very much for looking into this and also for explaining the ratio test. I definitely misunderstood what that test was doing. I really appreciate you pointing me to the BUSTED analysis and running the test too! That definitely looks like what I was trying to accomplish. I will go ahead and try it out on the full dataset. 

Best, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Great. This is only one hypothesis test you can do (fully equal vs fully unrestricted). You can also test for something more specific, e.g., only comparing components where dN/dS > 1 (or < 1), imposing proportional constraints, enforcing means to be the same, etc. Depends on the biological question you are asking. 

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thanks for the information. That's great. My main interest at the moment is in testing whether there is evidence for overall differences between the genes within this set I am studying. But, I may turn to asking some of these other questions too. 

Thank you, 

Luke
