### ISSUE TITLE
An error with absrel about non-reversible model and remove-duplicates.bf

### ISSUE THREAD

**Issue by wook2014** [veg/hyphy#1298]
Dear @spond 
I am doing a absrel analyse with sars-cov-2. An error occurs:
```
Error:
Internal error 
Internal error in ComputeBranchCache (branch UTUfRZZm.tree_0.hCoV_19_France_CVL_9321_2020_EPI_ISL_593936_2020_10_01, eval #526017 ) 
reversible model cached likelihood =   -8950.512629710634, directly computed likelihood =   -8950.351680482452. 
This is most likely because a non-reversible model was incorrectly auto-detected 
(or specified by the model file in environment variables; for smaller errors, this could be due to numerical instability of calculations for larger alignments).

Function call stack
1 :  Optimize(absrel.null.mles, ^absrel.likelihood_function_id);

-------

Check errors.log for execution error details.
```
The file is attatched behind. 

I also tried remove-duplicates.bf to remove some dup seqs but another error occurs with remove-duplicates.bf. The error file is big so it is attached behind. 

There are 3 main problems I have:
1. How to solve the problem on non-reversible model was incorrectly auto-detected?
2. What is the biggest data scale that hyphy could handle?
3. When I use remove-duplicates.bf to remove dup seqs, is the topology of the tree changed?

[align.txt](https://github.com/veg/hyphy/files/6099516/align.txt)
[tree.txt](https://github.com/veg/hyphy/files/6099517/tree.txt)
[errors.log](https://github.com/veg/hyphy/files/6099510/errors.log)

**Comment by spond** [comment]
Dear @wook2014,

1. The issue is due to numerical instabilities. Add the `ENV` command line argument like follows to ignore it (change file paths as needed, obviously)
```
hyphy absrel --alignment ~/Dropbox/hyphy-issues/1298/align.txt --tree ~/Dropbox/hyphy-issues/1298/tree.txt ENV="TOLERATE_NUMERICAL_ERRORS=1;"
```

2. Depending on the analysis. For FUBAR, MEME and FEL we've run upwards of `50,000` sequences. I don't recommend very large data for `aBSREL` (1,000 is about the practical limit). The main reason is loss of statistical power.

3. Yes. Whatever duplicates are removed from the sequence file, the corresponding branches will also be removed.

Best,
Sergei

PS The result on the compressed file (no duplicates) is attached. 

[compressed.fas.ABSREL.json.zip](https://github.com/veg/hyphy/files/6101865/compressed.fas.ABSREL.json.zip)
