### ISSUE TITLE
How to interpret MEME and FEL in light of the "uncertainty principle"

### ISSUE THREAD

**Issue by matthewnicotra** [veg/hyphy#1314]
I have a general question about how to run MEME and FEL and interpret the results when restricting the analysis to a subset of branches.

In several papers, you point out there is a kind of "selection inference uncertainty principle" because you can't simultaneously infer both a branch and a site is subject to diversifying selection. This is because you only have n = 1 in this case. My question is, what if you have an alignment & tree in which a site underwent mutations along many branches, but you restrict MEME or FEL to only test the branches of one clade with only one mutation at that site (because you have a specific hypothesis about that clade). From reading other posts, it seems that restricting MEME/FEL in this way is asking the question "what sites are under positive selection within this group".  But there is only only one mutation at this particular site in the group. So if MEME/FEL predict this site to be under positive selection, does that mean you can say that ***this specific site within this specific branch*** was under positive selection? That seems to contradict the uncertainty principle. I am sure I am misunderstanding something.

As you might guess, we have run into this situation in our own work. I would be happy to provide details in case it helps. The biological question we are studying is whether there is evidence of positive selection driving the evolution of binding specificities in a cnidarian self-recognition protein. We expect that this protein is under negative frequency-dependent selection (rare allele advantage)

**Comment by spond** [comment]
Dear @matthewnicotra,

It is definitely **possible** to identify selection at a specific site in a restricted setting like you describe. In the extreme case, you could limit the FEL/MEME test set to a single branch. In many cases, this signal will be driven by substitution along a very short branch, including multi-hit changes (the situation discussed at length in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6093625/). 

Technically, if you test a specific clade, the test uses information from the entire clade; lack of change is informative as well (for example, this will constrain the relative synonymous rate at a site). If you infer selection from a clade, it is not entirely "kosher" to then further reduce it to a single branch in a post-hoc manner, statistically speaking, because of this observation.

Best,
Sergei

**Comment by matthewnicotra** [comment]
Dear Sergei,

Thanks for the quick response, which clears things up!

Best,

Matt
