### ISSUE TITLE
GARD on Transposable Elements - Part 2

### ISSUE THREAD

**Issue by eliasprim** [veg/hyphy#1319]
Dear Hyphy Team,

Thank you for the new way to depict the results of GARD, it is really informative. This is my second post here, my first one has the tittle "GARD on Transposable Elements". Now I think I have a better understanding of how GARD works, and I have a couple of questions regarding some unfinished or possibly crashed GARD runs, and the analysis time that GARD requires with a higher number of sequences. In my GARD runs so far, I have used alignments that contain maximum 200 sequences and the average length of them is around 1.2 Kb. The alignments are of good quality.

1. The last month I have submitted many GARD runs, but for some of them I have not received any e-mail regarding their results or their status. I assume that these runs crashed because for all the other runs I received the results e-mail within 3-4 days. Is there always a notification e-mail when a run crashes (which means that, in any case, I will have to wait for either the results or the crash e-mail)?

2. As I mentioned above, I have a better understanding now of how GARD works and its results based on my sequences; so I would like for my final tests to submit alignments with >200 sequences, as I have realised that a higher number of sequences is certainly producing more consistent results. The quality of the alignments and the average length of ~1.2 Kb will remain the same. Can you advise me on how many sequences should I go for, without risking a crash or having to wait for a month for the results to come through?

Thank you very much in advance for your time.

Kind regards,

Elias

**Comment by spond** [comment]
Dear @eliasprim,

1. We had a number of intermittent issues with the server and had to be restarted a few times. This means that long-running jobs get knocked out. Do you have job IDs by chance?

2. GARD is best powered to detect "large" tree changes due to recombination. If you have one recombinant sequence in an alignment of 4-10 sequences, GARD will typically find it. If you have a recombinant sequence in a background of 200, then it is **not** likely to be found. Another way to think about it is that the number of sequences strongly influences model complexity. If you add a breakpoint to the alignment, this immediately adds 2N-3 parameters to the model (`N`= number of sequences). For 200 sequences, this is 397 parameters. `N` also influences the **minimum** partition size; loosely speaking you need a minimum number of sites to infer a tree for that partition. For example, a partition with 10 sites on 200 sequences does not make sense. For 200 sequences, and 1.2Kb, GARD will only consider at most 3 partitions (minimum partition size is 2N-3).

My general suggestion would be as follows

1. Prior to running GARD **thin out** closely related sequences. For example if among 200 sequences there are several that form a strongly supported monophyletic clade (or pairwise distances), replace the clade with a single representative. You can use `tn93-cluster` from https://github.com/veg/tn93 to "pre-cluster" the sequences for example. 

2. The "sweet" spot for GARD is 20-30 sequences in terms of computational performance/detection power. 

Hope this helps,
Sergei

**Comment by eliasprim** [comment]
Dear @spond,

Thank you very much for the clarifications and your suggestions.

1. I did not keep any job IDs, because they were trial runs.

2. I will follow your suggestions in order to get more meaningful and qualitative results.

Thank you very much for all your help.

Kind regards,

Elias
