### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by biozhangzhou** [veg/hyphy#1322]
Hello.
I'm using Hyphy 2.5.14 . The sequences I input can be divided by 3 and have no stop codons. But it the error "Error:
The input alignment must have the number of sites that is divisible by 3 and must not contain stop codons in call to assert(absrel.codon_filter.sites*3==absrel.codon_data.sites, error_msg);" still happened.

**Comment by spond** [comment]
Dear @biozhangzhou,

1. HyPhy is at version 2.5.31 -- it's worth upgrading for many reasons (speed is one big reason)
2. HyPhy may be having issues reading the file you are providing due to format differences between programs (e.g. a common issue is files that include the `~` character for gaps). Can you share your alignment file so that I can try to figure out what the problem is? Also, what analysis are you running?

Best,
Sergei

**Comment by biozhangzhou** [comment]
Thank you Very much for your timely reply!!!

I'm running aBSREL analysis. I have tried in many way. Its behavior is so strange.
Here is my alignment.
![Screen Shot 2021-04-22 at 9 49 31 PM](https://user-images.githubusercontent.com/42492970/115725660-a1dd2e80-a3b4-11eb-9410-6687fe0e8ed9.png)

![Screen Shot 2021-04-22 at 9 45 18 PM](https://user-images.githubusercontent.com/42492970/115725019-0cda3580-a3b4-11eb-85bf-f4e0d5ed0f7e.png)

**Comment by spond** [comment]
Dear @biozhangzhou,

The third line of your Ana-001 sequence includes `TAG` (stop codon). Are these sequences something different than the Universal genetic code?

Best,
Sergei

**Comment by biozhangzhou** [comment]
I'm so sorry for the careless. Thank you for your patients .

**Comment by biozhangzhou** [comment]
Sorry for be here again. I have tried to install hyphy 2.5.31 mannually or by conda. It's so difficult. 
The conda defaultly install 2.5.8 but not the 2.5.31.  When I use command " conda install hyphy=2.5.31" will bring many inconsistant error.
