### ISSUE TITLE
Global estimates of dN, dS, and dN/dS with the FitMG94.bf analysis

### ISSUE THREAD

**Issue by lcwheeler** [veg/hyphy#1328]
Hello, 

I am fitting the MG94 model with a global value for dN/dS using the FitMG94.bf. One thing I was hoping to do was to get a global estimate of dN and dS separately, equivalent to the "tree length for dS" and "tree length for dN" values returned by the equivalent analysis in PAML/CODEML. However, it seems there is not a single dN or dS value in the json output of FitMG94.bf. So, I simply iterated over all the branch values in the json and added them together, thinking that would give me what I'm looking for. However, I did a quick sanity check of dividing the summed dN value by the summed dS value to get an estimated dN/dS for the whole tree and these are not the same as the global dN/dS estimates returned by the model the fit. Some of them are very close, but others are reasonably different. In fact, extracting just the tip dN and dS values and taking the mean gives an estimate much closer to the global estimate. So, I have two questions: 

1) What is the appropriate way to get an overall estimate for dN and dS using FitMG94.bf with HYPHY? 

2) Why are the values from my summing-and-dividing procedure not equal to the global dN/dS estimates? Are those calculated in a different way or is it possible there is a bug somewhere or that I'm just doing something wrong? 

I have attached an example json output where the difference between ways of calculating dN/dS is particularly notable. Global estimate from fit = 0.615278, sum-and-divide branch values = 0.529321 

Thanks, 

Luke 

[MYBFL.1omega.json.txt](https://github.com/veg/hyphy/files/6400878/MYBFL.1omega.json.txt)

**Comment by spond** [comment]
Dear @lcwheeler,

&omega; is not quite the same as dN/dS (although it is used interchangeably often). I really encourage you to read [Spencer Muse's](https://academic.oup.com/mbe/article-pdf/13/1/105/11168217/11muse.pdf) paper from 1996 to understand the subtle differences 

If you fit the global model, dN/dS will be the same for all non-zero length branches (you don't need to sum; any branch ratio will be the same).  

The reason that you sometimes get different estimates between dN/dS and &omega; is that the denominator of dN (and dS) is not defined cleanly.

dN := expected # of non-synonymous substitutions / # of non-synonymous sites.

How do you estimate the "# of non-synonymous sites"? It turns out that depending on how you do it, the results might differ. We estimate them here using codon equilibrium frequencies from the codon model (which depends on the data). The &omega; ratio estimated directly by MG94 does not require this normalization (it's baked into the model directly, since you comparing **rates**, not **normalized counts**).

&omega; is a more appropriate estimate of the ratio of these rates when you use the MG94 model. `dN` and `dS` include additional assumptions. On guess I may offer about the differences you see is that this particular dataset may have sequences that don't all share the same base frequencies (you should be able to simply count A,C,G,T fractions by sequence and see if there are outliers for example).

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thank you very much for the clarification on this matter. I will take a look at that 1996 paper to better understand the difference. And sorry for opening an issue for something that turned out not to be an actual problem! 

Best, 

Luke

**Comment by spond** [comment]
Dear @lcwheeler,

Not a problem at all. Happy to discuss any and all kinds of questions.

Best,
Sergei

**Comment by lcwheeler** [comment]
Dear @spond, 

Thank you. I appreciate your help! 

Best, 

Luke
