### ISSUE TITLE
ERROR WHILE LOADING INPUT SEQUENCE ALIGNMENT 

### ISSUE THREAD

**Issue by Abhishek7Nayak** [veg/hyphy#1332]
Hello Thanks for this cool program 

Which I was loading my sequence alignment file of protein sequences I get this error 

Error:
Too many ambiguous states in call to 'long int _TranslationTable::MultiTokenResolutions(const _String&, long int*, bool) const'

Function call stack
1 :  DataSetFilter ^datafilter_name = CreateFilter(^dataset_name, 3, , , data_info[terms.stop_codons]);

-------
2 :  return alignments.LoadCodonDataFile(dataset_name,datafilter_name,alignments.ReadCodonDataSet(dataset_name));
-------
3 :  [namespace = absrel] codon_data_info=alignments.PromptForGeneticCodeAndAlignment(prefix+".codon_data",prefix+".codon_filter");
-------
4 :  [namespace = absrel] load_file("absrel");
-------
5 :  namespace 

Step 0.LoadFunctionLibrary("modules/shared-load-file.bf", /home/internal/Sys_Bio/group_kritika01/anaconda3/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/);

Step 1.load_file("absrel");;
-------

Please help me in resolving this issue.
Thanks

**Comment by Abhishek7Nayak** [comment]
Hello 
I guess the error is because I was used a protein sequence alignment. I came to know that absrel requires a protein coding sequences. FADE can be used for protein sequences. 
Is there a way were I  can run absrel method on my dataset?
Thanks

**Comment by stephenshank** [comment]
Dear @Abhishek7Nayak,

Thanks for your interest in HyPhy! You are indeed correct that aBSREL requires a codon alignment. Since the method requires information from synonymous substitutions to measure selective pressures, it cannot be adapted to run on a protein alignment.

You should be able to run FADE on your dataset, just be aware that it is still under development and will require a rooted tree.

Best,
Stephen

**Comment by Abhishek7Nayak** [comment]
@stephenshank 

Thank you for the reply.  I have a protein concatenated alignment. Is there a way where i can covert my protein alignment to a codon alignment.

Thank you

**Comment by spond** [comment]
Dear @Abhishek7Nayak,

If **all** you have is a protein alignment, then no (because many codons map to some amino-acids, so you don't know which one to use). If you also have the underlying nucleotide sequences, then yes. Use `pal2nal` (a 3rd party tool) or one of ours https://github.com/veg/hyphy-analyses/tree/master/codon-msa

Best,
Sergei

**Comment by Abhishek7Nayak** [comment]
@spond @stephenshank 
Thank You very much for the help

Abhishek
