### ISSUE TITLE
Estimating local dN/dS

### ISSUE THREAD

**Issue by LeebanY** [veg/hyphy#1336]
Hi, 

First of all thank you for the great software!

I would like to estimate local dN/dS across a phylogeny for a rather large dataset (~8000 genes). By searching the issues tab of hyphy and having a bit of read, I realised there were two ways to go about this: (a) using the standalone FitMG94 analyses or (b) using the program on hyphy called 'acd' and then fitting MG94. For the former, part of the installation is not working for me and I'm not completely sure why, so I tried the second approach. This works well when testing on a single alignment, but it doesn't provide any command-line flag options, so I'm having trouble automating this for all genes. I was wondering what the flags for the 'acd' program are? Also, separately, I'm wondering what the difference is between these two approaches are? 

EDIT: I managed to figure out how to automate the analysis for 'acd'...but I'm still wondering what the difference is between the standalone and the 'acd' program is. Additionally, I've been wondering how MG94 is being calculated here and particularly why it's so much faster than a 'free ratio model' in PAML, which also computes local omega? 

EDIT2: Sorry, one more question! I've just been looking through some of the results, and I noticed branch-specific estimates from MG94 (via acd) give much lower omega values compared to the M0 model in PAML -- is this expected too?

Thanks,
Leeban

**Comment by spond** [comment]
Dear @LeebanY,

I would suggest you use the standalone `FitMG94.bf` since it gives you many more options and is a "modern" analysis, whereas `acd` is a legacy analysis. 

You should be able to `git clone` the `hyphy-analyses` repository and then simply call 

```
hyphy /path/to/FitMG94/FitMG94.bf
```

Regarding your other questions.

1. `FitMG94` and `acd` are very similar; FitMG94 gives you more options in terms of estimating confidence intervals, dN and dS separately and so on.
2. `how MG94 is being calculated here` Don't understand the question. HyPhy performs standard ML fitting using the pruning algorithm.
3. HyPhy is generally much faster than PAML for a variety of technical reasons having to do with tuning and optimization algorithms
4. Where do you get branch specific estimates from `acd`? What's written in the tree string are branch lengths, so you may be looking at different quantities.


Best,
Sergei
