### ISSUE TITLE
results issues

### ISSUE THREAD

**Issue by SticaC** [veg/hyphy#1352]
I am having issues with a few of my runs resulting. I have used the exact same datasets with other methods and have received results. I have submitted them a few times over the last couple of days and keep getting a standard error message. Here are the most recent submission urls:

http://datamonkey.org/meme/60e25e767c8781112a3d7b25
http://datamonkey.org/slac/60e25e9e7c8781112a3d7d0d
http://datamonkey.org/absrel/60e25ed27c8781112a3d7ef5
http://datamonkey.org/meme/60e25f107c8781112a3d80df
http://datamonkey.org/meme/60e25f347c8781112a3d81ed
http://datamonkey.org/slac/60e25f637c8781112a3d83e1
http://datamonkey.org/absrel/60e25f9c7c8781112a3d85d5

Any assistance as to the reason for the error is greatly appreciated.

Thanks
Caleb

**Comment by stevenweaver** [comment]
Dear @SticaC, 

Thank you for reporting your issues. After digging deeper, node is failing silently at a step when results files are larger than `50MB`. Will work on implementing a fix shortly. In the meantime, I'll send results to you for these runs tomorrow during standard business hours.

Best,
Steven

**Comment by SticaC** [comment]
Hi Steven,

Just checking on the status of these runs. It seems as if they have not completed and errored out. Should I resubmit?

Thanks
Caleb

**Comment by stevenweaver** [comment]
Hi @SticaC, 

I implemented a fix over the past two days, but have not released it quite yet. I am planning to do that within the next 24 hours after additional testing. You helped reveal a bug that was silently erroring so I appreciate this issue report. I am not sure how long it would have taken to notice otherwise. I'm also working to add additional backend administrative tools to reveal these types of errors in the future. 

Your results are located here, http://data.hyphy.org/web/sticac/. Your aBSREL job, 60e25f9c7c8781112a3d85d5, experienced an error during maximum likelihood estimation, which will require further debugging. 

Best,
Steven

**Comment by SticaC** [comment]
HI Steven,

Thanks so much for your assistance.

Caleb
