### ISSUE TITLE
GARD error, large file?

### ISSUE THREAD

**Issue by mliannholland** [veg/hyphy#1356]
Ticket Number 1562436.new-silverback
I am trying to run GARD recombination detection but when I tried running the test online (normal run time)there was an error message (errorcode 1) and signal 15. My file contains more than 190 sequences.

Prior runs of GARD on my smaller files (<40sequences) completed but only processed 27-29 sequences. Why are some sequences being cut?

**Comment by stephenshank** [comment]
Dear @mliannholland,

Upon clicking `Download log`, you can see the following error message:

`Master node received an error:The alignment is too short to permit c-AIC based model comparison. Need at least 584 sites for 145 sequences to fit a two-partiton model. in call to assert(gard.minExpectedSites<=gard.numSites, error_msg);`

There needs to be a sufficient amount of data for the inference to be reliable, and apparently your dataset falls below the required threshold.

Regarding dropped sequences, are there any duplicate sequences contained in your dataset? Datamonkey will strip out identical sequences since they result in 0 branch lengths that add no information to the inference, but increase computational burden.

Best,
Stephen
