### ISSUE TITLE
Model test

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#1359]
Hi,

I'm running `mt` (4 cat and 'AIC Test') to execute the `acd` analysis, I was wondering if I should exclude `I` from the analysis to avoid over-parameterization, is that the case, how I can do it?

Thanks a lot
F

**Comment by spond** [comment]
Dear @francicco,

I would not worry too much about model over-parametrization in this context. We have long since defaulted to using MG94xREV for codon analyses. 

The issue of rate variation is a lot more complex (see https://pubmed.ncbi.nlm.nih.gov/32068869/ for example); and model test (which runs on nucleotide data) does not provide any sensible testing for what is going on in the codon space.

You may also take a look at 

https://pubmed.ncbi.nlm.nih.gov/20808876/ and 

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0011587

for some codon-specific background.

Can you tell me a bit more about what the object of your inference was?

Best,
Sergei

**Comment by francicco** [comment]
Hi Sergei,

Thanks for your explanations. I'm performing the modeltest to subsequently run the overall omega `hyphy acd`.
Cheers
F
