### ISSUE TITLE
absrel speed problem

### ISSUE THREAD

**Issue by 12suiyue** [veg/hyphy#1398]
The speed of absrel processing, my file is a bit big, it has been allowed for more than ten days, and it has not been run. I want to ask how long it will take for more than 900 sequences. I am eager to get the results. Is there a quick way? The first one in the attachment is the comparison file, and the next one is the tree file
Code:
mpiexec --oversubscribe -n 28 HYPHYMPI absrel --alignment /gss1/home/tangcm01/yajizumimazibidui1/ABCGhyphy/ABCGpal1.phy --tree /gss1/home/tangcm01/yajizumimazibidui1/ABCGhyphy/ABCGpal1.phy.treefile --output ABCG. ABSRELduozuihouzuihou12.json
[ABCGpal1.txt](https://github.com/veg/hyphy/files/7182358/ABCGpal1.txt)
[ABCGpal1.phy.treefile.txt](https://github.com/veg/hyphy/files/7182359/ABCGpal1.phy.treefile.txt)

n

**Comment by spond** [comment]
Dear @12suiyue,

Your example is interesting, thanks for bringing it up. aBSREL does **not** scale well with the size of the tree. This is for three reasons

1). The execution is mostly sequential, so you can't parallelize it. The model selection step is written in a way when one branch has to be examined after another.

2). Model fitting time scales non-linearly as a function of the number of branches. 

3). You will lose nearly all statistical power if you test too many branches, because of multiple testing correction.

Your tree seems to have some pretty clear clade structure and **a lot** of short branches in individual clades 

<img width="554" alt="Screen Shot 2021-09-18 at 10 08 48 PM" src="https://user-images.githubusercontent.com/1018513/133913159-b25f43fd-dc46-49dd-873e-e136731864df.png">

These short branches almost never have any signal for selection, but they will slow down execution and dilute statistical power. I would suggest that you "trim" your tree by effectively selecting a few sequences per clade (tagging @aglucaci who worked on this area some).

Here's a simple command to do that.

```
tn93-cluster -c any  -t 0.1 /Users/sergei/Downloads/ABCGpal1.txt | jq -r '.[]["centroid"]' > subset.fas
```

This uses the [tn93-cluster](https://github.com/veg/TN93) program to "cluster" all sequences that are within 10% (nucleotide distance) of each other, and passes it through the [jq JSON manipulator](https://stedolan.github.io/jq/) to create a FASTA file. I also used the attached HyPhy script to reduce the tree you provided only to the sequences in `subset.fas`

```
hyphy label-tree.bf --tree ABCGpal1.phy.treefile.txt --msa subset.fas --list list.txt --output subset.nex
```

The resulting alignment (`subset.nex`) is also attached and the tree that it includes has lost all the "shallow" branches.

<img width="764" alt="Screen Shot 2021-09-18 at 10 14 55 PM" src="https://user-images.githubusercontent.com/1018513/133913233-e3760de1-fa27-4901-958a-9fca996da3f2.png">

For reference purposes, the sequences kept in the smaller tree are also shown here on the original (full tree)
<img width="631" alt="Screen Shot 2021-09-18 at 10 17 19 PM" src="https://user-images.githubusercontent.com/1018513/133913262-0c54a4fa-c453-4eff-8164-fd466d38fb21.png">

This smaller file runs in a few hours on my laptop (via `hyphy absrel --alignment subset.nex`) yielding the results which can be viewed [here](http://vision.hyphy.org/absrel?resultsUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fspond%2F3427f2186a410c4bd54181baab0e9222%2Fraw%2F8d553875b7bb2dac74acc4b1993f7480d7d4f8c4%2FaBSREL.json)

 Best,
 Sergei

[Archive.zip](https://github.com/veg/hyphy/files/7190898/Archive.zip)

**Comment by 12suiyue** [comment]
Thank you, the problem that has been bothering me is finally solved

**Comment by 12suiyue** [comment]
Hello, I have a problem when using your method to prune my evolutionary tree. The following error occurred when using the attached HyPhy script. My hyphy version is 2.5.32. I wondered if I can rebuilds a new evolutionary tree with iqtree by clustering tree use with tn93-cluster  I don’t know if you can solve it, I look forward to your reply!
Code: hyphy label-tree.bf --tree ABCBpal.phy.treefile --msa ABCBguolv.fas --list ABCBlist.txt --output ABCBguolv.nex

Analysis Description
--------------------
 Read a tree and (optionally) a list of sequence names, and annotate
branches for subsequent analyses that accept branch partitions.

-__Requirements__: An MSA and, optionally, a tree

-__Citation__: TBD

-__Written by__: Sergei L Kosakovsky Pond

-__Contact Information__: spond@temple.edu

-__Analysis Version__: 0.1


Error:
'RPN:"labeler.file"|"labeler.filter"|alignments.PromptForGeneticCodeAndAlignmentWarnStops|*' evaluated with errors Unconsumed values ​​on the stack
[2]------------------
0
[1]------------------
0
[ABCBguolv.txt](https://github.com/veg/hyphy/files/7191219/ABCBguolv.txt)
[ABCBpal.phy.treefile.txt](https://github.com/veg/hyphy/files/7191218/ABCBpal.phy.treefile.txt)


Function call stack
1: labeler.info=alignments.PromptForGeneticCodeAndAlignmentWarnStops("labeler.file","labeler.filter");

Keyword arguments:
{
"list":"ABCBlist.txt",
"msa":"ABCBguolv.fas",
"output":"ABCBguolv.nex"
}
-------

Check errors.log for execution error details. 
与此原文有关的更多信息要查看其他翻译信息，您必须输入相应原文

**Comment by spond** [comment]
Dear @12suiyue,

Can you please update to the latest HyPhy version (or maybe even the `develop`) branch? The `alignments.PromptForGeneticCodeAndAlignmentWarnStops` library function is not available in your version.

Best,
Sergei

**Comment by 12suiyue** [comment]
thank you for your reply!I just downloaded the latest version and still report an error. I found RequireVersion ("2.5.15") in the label-tree.bf file. Do I need to download hyphy 2.5.15?

**Comment by 12suiyue** [comment]
hi Sergei,I just found out that there is no alignment.PromptForGeneticCodeAndAlignmentWarnStops library in the hyphy I installed, and the latest version I just downloaded is not available. Can I take the liberty to ask what version you have installed? Looking forward to your reply?

**Comment by spond** [comment]
Dear @12suiyue,

Check out and install the `develop` branch and you'll be able to run it (see README for this [repo](https://github.com/veg/hyphy-analyses/))

Best,
Sergei

**Comment by 12suiyue** [comment]
ok,thank you for your reply!
