### ISSUE TITLE
HyPhy and saturation 

### ISSUE THREAD

**Issue by skaul31** [veg/hyphy#1411]
Hello, 

I had some questions regarding RELAX and aBSREL and how saturation is dealt with in these molecular evolution tools. I am working with a set of 17 genes currently and have run both RELAX and aBSREL on each gene. For each gene I have about 25-27 coding sequences from different _Caenorhabditis_ species. The biggest problem we have within our set is that there is a lot of substitution saturation in this system due to large divergence times between different species. The questions that I have are: 

1. How robust are aBSREL and RELAX in terms of dealing with substitution saturation? Is it appropriate to use these tools in a system that experiences high levels of saturation? 

2. I wanted to run RELAX by keeping one species as the test and the rest of the species as reference but was informed that this would be inappropriate as the sample size of the test or reference groups should not be 1. I therefore decided to look at k-values generated under the General Descriptive model to determine a distribution for each gene. What I find under the General Descriptive model for each gene is that some of the species within my sample set have very high k-values, going all the way up to 49.99. I am having a hard time interpreting this. Is this value indicative of the high saturation levels or that selection intensification is very strong in the species with such high values? 

3. Would the saturation problem be alleviated if the number of species used in the analyses is reduced to only include those species that are part of closely related subgroups (in _Caenorhabditis_ we have an _elegans_ subgroup that includes about 9-11 species). 

4. Are there any ways to deal with saturation before running molecular analyses on a set of coding sequences? 

I am attaching two json files as examples from the RELAX analyses that I ran to show the high k-values under the general descriptive model. Thank you so much for reading through and answering my questions!
[JSON_files.zip](https://github.com/veg/hyphy/files/7287585/JSON_files.zip)

**Comment by spond** [comment]
Dear @skaul31,

Saturation, classically defined, simply means that you can no longer reliably estimate branch lengths, or that they will be systematically underestimated. From the standpoint of `aBSREL` and `RELAX`, when you have sequences that are highly divergent, the issues may arise because of "infinite" branch lengths. When you have those, HyPhy may suffer from numerical instability and convergence problems in some cases, while in others, you will simply lose statistical power. Some HyPhy methods even include warnings to that effect (these commonly indicate alignment issues).

1. I have not extensively tested the methods with "saturated" data. There are some internal checks in the methods with regards to convergence -- if you see warning to that effect, you may have an issue. Generally, you should be OK.
2. `k ~ 50` simply means that you have extreme distributions of &omega; -- 0 and infinity. You will usually see those along **short** branches (e.g. a short branch that only experienced non-synonymous changes). It is somewhat abnormal, but not pathological _per se_
3. Saturation will typically affect specific branches; for example if you have two subtrees separated by a very long branch, then evolutionary inference for one subtree will be essentially "independent" of the other subtree. Reducing your data sets is almost always a bad idea, because you are reducing information content. 
4. Not really; you may use more complex models (e.g. https://pubmed.ncbi.nlm.nih.gov/21705379/)

For the two examples you include it would be helpful to see

1. `aBSREL` results on the same data.
2. `SLAC` results on the same data.

I don't see anything particularly abnormal about these, however.

Best,
Sergei
