### ISSUE TITLE
Suitability of aBSREL and MEME for small dataset

### ISSUE THREAD

**Issue by nfwhite** [veg/hyphy#1424]
I have a dataset with only 7 sequences. From the help manual I see my best choices for detecting selection are BUSTED and then FEL, with a bootstrap step. I can't find information on the suitability of MEME or aBSREL for a dataset of this size - can anyone advise me on whether I could trust the results of these tests for my data please? 

Many thanks.

**Comment by stephenshank** [comment]
Dear @nfwhite,

I think you can certainly trust the results, as they are based on principled statistical tests. However, they do need to be interpreted correctly. I think such a small sample size will limit statistical power, and therefore your ability to detect modest amounts of selection. In this scenario, a method will report that it was unable to find statistically significant negative/positive selection which may be acting on the gene in small amounts, but avoids detection due to underpowering.

@spond may want to elaborate or amend the above.

Best,
Stephen

**Comment by spond** [comment]
Dear @nfwhite,

@stephenshank is entirely correct; MEME should have little power. MEME has a option to do bootstrap as well (`--resample N`). Because aBSREL does not rely on site-level inference, a small number of sequences does not affect it directly. If anything, aBSREL has **more** power in small to medium samples for "scan all branches" tests, because you have to correct for fewer hypotheses testing.

Best,
Sergei

**Comment by nfwhite** [comment]
Dear Stephen and Sergei, 

This is very helpful! Thank you both for your time.

Best wishes,
Nina
