### ISSUE TITLE
Adding a labeled branch tree to my gene files

### ISSUE THREAD

**Issue by Indoleant** [veg/hyphy#1427]
Hi, I am currently a student trying to add a labeled branch tree I made in HyPy/phylotree.js to the gene I took from mesquite(as a .txt file). Because the tree shown in datamonkey for the aBSREL does not match the tree I labeled in mesquite that I took the gene from, nor the tree I made on phylotree.js.

All in all, I really want the tree to match, and I thought the easiest way was adding a labeled tree but that doesn't seem to work.

**Comment by spond** [comment]
Dear @Indoleant,

Can you elaborate? There are a couple of reasons the tree may _look_ different

1. Datamonkey/HyPhy will unroot the tree (since all models are reversible).
2. Datamonkey/HyPhy may "reroot" the tree, i.e. pick a midpoint somewhere to speed up fitting.
3. If you have identical sequences in your alignment, Datamonkey will remove them from your alignment for efficiency (so they will also disappear from the tree).

You may want to check whether the Datamonkey tree is equivalent to the input tree after these possible changes.

Best,
Sergei

**Comment by Indoleant** [comment]
@spond How would I prevent the "unrooting" of the tree? It doesn't seem to change the midpoint, but rather the actual species on the branches. Where if S and W were a branch, in datamonkey S and N would be in it's place, and W would be on a completely different branch.

**Comment by spond** [comment]
Dear @Indoleant,

It is also possible that Datamonkey does not recognize the tree you include in the alignment and infers its own neighbor joining tree.

Can you provide the entire alignment file you are trying to upload?

Best,
Sergei
