### ISSUE TITLE
input tree into aBSREL is unrooted, output tree is rooted

### ISSUE THREAD

**Issue by laura-win** [veg/hyphy#1433]
Dear Hyphy Team, 

I have a question regarding the tree that I can download from Hyphy Vision (from an aBSREL analysis). When I read this tree in R, I can see that the tree is rooted, the input tree however was unrooted. But how does aBSREL root the tree?   Thank you so much!

Best, 
Laura

**Comment by spond** [comment]
Dear Laura,

`aBSREL` does not root trees in any way. Can you please provide a more detailed explanation of what you are seeing and how you are able to get a rooted tree from aBSREL. There is a possibility that `R` may be rooting the tree as well. What happens when you load the Newick file into phylotree.hyphy.org?

Maybe include some screenshots?

Best,
Sergei
