### ISSUE TITLE
Analysing <10 sequences

### ISSUE THREAD

**Issue by nfwhite** [veg/hyphy#1442]
I have a set of 7 sequences that I'd like to test for selection using the datamonkey server. I understand that with this number, the power to detect site-specific selection is reduced. Ideally, I'd run FEL, MEME, SLAC and FUBAR and cross-validate findings between the methods. My problem is in choosing the right alpha level before comparing the results. From reading "Not So Different After All: A Comparison of Methods for Detecting Amino Acid Sites Under Selection" I see that one option is setting the alpha-level to 0.25 and then identifying a consensus between the methods (though this refers to FEL, SLAC and REL, not mentioning MEME or FUBAR). 

My questions are: 
- does the principle of setting an alpha level of 0.25 still apply to MEME? 
- would I use a posterior probability of 0.75 to FUBAR? Or, due to its reliance on Bayesian estimation like REL, should I keep the alpha level higher here to avoid false positives?
- Do you have any other recommendations for this situation?
 
Any help here would be very much appreciated, many thanks.

**Comment by spond** [comment]
Dear @nfwhite,

My recommendation at the moment, for small samples, would be to run FEL with parametric bootstrap enabled (https://hackmd.io/dmQwH39xTbWfIyIbTZFSOA). MEME has the same options.

SLAC and FUBAR will have very little power on small sample sizes. The main issue with smaller sample is other or not the asymptotic apply (they may not). So using the site-level parametric bootstrap is a way around.

Regarding significance level you can do one of three things:

1). You can run BUSTED to determine whether or not there's evidence of selection in the entire alignment, and then run FEL/MEME if you find significance with BUSTED (this the Nielsen Yang type approach).

2). You can run MEME and FEL as is and use your standard p-values (e.g. 0.05). The risk here is that if your data are close to neutral (very rare), you expect 5% or so of false positive results.

3). You can calibrate p-values by simulating null data with your tree (branch lengths, base compositions etc) and seeing where you need to set the p-value to control false positives (this is a laborious and tedious approach).

Because MOST codons in MOST genes are negatively selected, test performance generally speaking will be conservative (or very conservative). The easiest way to go is (1)=> you get a p-value based on alignment wide tests (so you have power), then run site level detection.

Best,
Sergei

**Comment by nfwhite** [comment]
Dear Sergei,

Thank you for your helpful response. I'm sorry, do not see an option to add parametric bootstrap to the MEME job submission page on datamonkey. Is this something only available on the command line?

Best wishes

**Comment by jzehr** [comment]
Dear @nfwhite, 

As of right now, the parametric bootstrap option is only available for the command line version of MEME . 

Once HyPhy is installed, you can use something like: 

`HYPHYMP MEME --alignment data.fas --tree data.tree --resample 100 --output data.MEME.json`

The `--resample` flag will perform parametric bootstrap resampling to derive site-level null LRT distributions up to X many replicates per site (in the above case we chose 100 replicates per site to derive the site-level null LRT distribution). 

Best,
Jordan

**Comment by nfwhite** [comment]
Many thanks Jordan!
