### ISSUE TITLE
SBP on DataMonkey Classic

### ISSUE THREAD

**Issue by katherinermartin** [veg/hyphy#1448]
I previously ran this same dataset on HyPhy classic in late 2019.
I'm currently getting the error "This job appears to have expired" whenever I try to run SBP on DataMonkey classic; here's the job URL: [http://classic.datamonkey.org/cgi-bin/datamonkey/mpiJobStatus.pl?fileName=upload.14317175862847.1&task=sbp](url)

It's my understanding that SBP is not offered on the new Datamonkey; however my dataset is 126 sequences and has a length of 159 bp, so I don't have the option of running GARD since the alignment is too short to permit c-AIC based model comparison.
Link to GARD results on new DataMonkey: [https://www.datamonkey.org/gard/61d87c0f961ae956fe92ccee](url)

Is there a way to get SBP to run on Classic? Or is my only option to infer recombination to use GARD on the new DataMonkey and prune sequences so that c-AIC can be inferred?

Thank you!

**Comment by spond** [comment]
Dear @katherinermartin,

We no longer fully support the classic instance of Datamonkey due to personnel availability. I'll leave this issue open for now, maybe @stevenweaver can comment further. 

Regarding your current dataset, I would suggest that you trim it down and then run GARD. The one-breakpoint stage of GARD is equivalent to SBP. The reason I suggest that is because if you have N sequences, you effectively need a minimum number of sites to infer any sensible phylogeny (in the information theoretic sense); something like 2N-4 sites.

What I typically do for these situations is run `tn93-cluster` from the GitHub.com/veg/TN93 suite, using variable cutoffs until you get down to a desired set of sequences. Increase `-t` in the command below  

```
tn93-cluster -f -t 0.01 -a resolve -m json input.fasta > clusters.json
```

You can then convert the `clusters.json` file into a FASTA file using the `jq` utility: 

```
jq -r '.[]["centroid"]' clusters.json  > forGARD.fas

```

HTH,
Sergei

**Comment by katherinermartin** [comment]
Thank you very much for the help, @spond! I will give it a try.

**Comment by spond** [comment]
Dear @katherinermartin,

No problem at all. Let me know how it goes.

Best,
Sergei
