### ISSUE TITLE
GARD not working on datamonkey.org

### ISSUE THREAD

**Issue by cadhlaf** [veg/hyphy#1456]
Hi, I'm trying to run GARD but can't seem to get anything to work. I've attached screenshots of what's happening. Basically as soon as I select Run Analysis, the file name disappears but no other actions take place. It doesn't matter what run options I select or what type of file (fasta, nexus) I upload. Thanks for your help!

![Screen Shot 2022-02-12 at 3 45 47 pm](https://user-images.githubusercontent.com/80365832/153698762-c9ced686-ac31-4683-af39-489c88adefce.png)
![Screen Shot 2022-02-12 at 3 45 54 pm](https://user-images.githubusercontent.com/80365832/153698764-3e824293-4560-4a5d-a2f9-c89dd7f7bedd.png)

**Comment by jzehr** [comment]
Dear @cadhlaf, 

Make sure to uploading a codon-aware alignment to GARD.

I was just able to upload a codon aware alignment and see my job in the queue. 

Best,

**Comment by cadhlaf** [comment]
Does this mean I have to analyze each ORF separately and can't run GARD on a full genome sequence?

**Comment by spond** [comment]
Dear @cadhlaf,

You should be able to use full genomes and non-coding alignments. Can you please provide the alignment you are trying to upload so that I can debug the issue?

Best,
Sergei

**Comment by cadhlaf** [comment]
Thanks so much @spond! 
I can't seem to attach anything with a .fas or .nex file format, so I've just changed the extension of my fasta file to .txt for the upload, but otherwise it's the same. I should note that I also tried running FEL with this same file and it worked perfectly (although I really only need to run GARD), so it seems to be a GARD-specific issue. 
[BetaCoVs HKU9 ORF1ab.txt](https://github.com/veg/hyphy/files/8060308/BetaCoVs.HKU9.ORF1ab.txt)

**Comment by spond** [comment]
Dear @cadhlaf,

The issue arises because 

1). Your dataset  (~30,000 sites) exceeds our limits on GARD in Datamonkey. We limit the length of the alignment to 12,000 sites because otherwise these jobs might take too long

2). Datamonkey generates an error behind the scenes but does not display it to the user (this is a bug, which we will fix). Thanks for pointing this out.

I'm running your dataset through HyPhy locally and will post a result when its available.

Best,
Sergei

**Comment by cadhlaf** [comment]
Thanks so much @spond, I appreciate it!
