### ISSUE TITLE
The number of tree tips in 'HjHeWosw.tree_0'(3501) is not equal to the number of sequences in the data filter associated with the tree (494).

### ISSUE THREAD

**Issue by NickShanyt** [veg/hyphy#1466]
```
### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
Error:
The number of tree tips in 'HjHeWosw.tree_0'(3501) is not equal to the number of sequences in the data filter associated with the tree (494).

```
/HYPHY 2.5.36(MP) for Linux on x86_64\ 
/HYPHY 2.5.32(MP) for Linux on x86_64\
**they all reported this error.**

In my tests, this error occurred in the SLAC, MEME, FUBAR, and FEL models.
---
### Detailed input file and corresponding error file can be obtained [here](https://github.com/NickShanyt/Temp/tree/main)

Phylogenetic trees are constructed based on sequences from multiple lineages, but the input sequence is only a protein from one of the lineages.

And I don't know what each of the two trees mentioned above refers to. And what do (3501) and (494) correspond to, respectively?
3501 is fixed, but in different proteins, 494 will change.

**Comment by spond** [comment]
Dear @NickShanyt,

HyPhy expects that there is a one to one relationship between sequences in your alignment and tips in your phylogeny. This is required for defining and computing the likelihood function. If you have more tips in your phylogeny that sequences in the alignment, the error you see is the expected behavior.

A solution to this issue is to **trim** your larger tree to only include the sequences that are in the alignment, or to rebuild the tree from the alignment directly.

I attach a simple HyPhy script (`reduce-tree.txt`) which you can run to do this.

```
$hyphy reduce-tree.txt --msa Temp/A.msa --tree Temp/tree.nwk --output Temp/A.nwk
$hyphy fel --alignment Temp/A.msa --tree Temp/A.nwk --branches Internal

....

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -2531.09
* non-synonymous/synonymous rate ratio for *background* =   0.5972
* non-synonymous/synonymous rate ratio for *test* =   1.7505

### For partition 1 these sites are significant at p <=0.1

|     Codon      |   Partition    |     alpha      |      beta      |      LRT       |Selection detected?|
|:--------------:|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------:|
|       12       |       1        |        0.000   |      125.423   |        4.248   |  Pos. p = 0.0393  |
|       13       |       1        |        0.000   |       74.533   |        5.158   |  Pos. p = 0.0231  |
|       67       |       1        |        0.649   |      100.151   |        5.261   |  Pos. p = 0.0218  |
|      202       |       1        |        0.000   |      228.398   |        9.996   |  Pos. p = 0.0016  |
|      270       |       1        |        0.000   |       82.624   |        3.555   |  Pos. p = 0.0594  |
|      343       |       1        |        0.000   |      115.227   |        5.184   |  Pos. p = 0.0228  |

### ** Found _6_ sites under pervasive positive diversifying and _0_ sites under negative selection at p <= 0.1**


```

Best,
Sergei


[reduce-tree.txt](https://github.com/veg/hyphy/files/8352672/reduce-tree.txt)

**Comment by monopsia-mammosa** [comment]
Hi, I have exactly the same problem BUT it doesn't make sense as both my tree and alignment have an equal amount of sequences. The error says that one leaf doesn't find its match in the alignment. There is no misspelling in this particular taxon, on both trees and in the alignment they are named exactly the same after all the tree was constructed based on an alignment, files are in a good format, alignment in fasta, tree in Newick and i really don't understand where the issue lies.
I am new to hyphy and the magic world of genomics so maybe the explanation is easy?

> The leaf of the tree nucTree labeled '_A_3_36A_SKELETONEMA_DOHRNII_WR65_02572_R1_' had no match in the data filter. Please make sure that all leaf names correspond to a sequence name in the data file.

i would appreciate any help!

**Comment by stephenshank** [comment]
Dear @monopsia-mammosa,

Are you able to share the files and how you are running your analysis (i.e. which HyPhy method, using the command line or Datamonkey, etc.)? This would help us to troubleshoot. If you are a using Datamonkey, a URL associated to the job should suffice.

Best,
Stephen
