### ISSUE TITLE
Which module of this software we should use for calculation.

### ISSUE THREAD

**Issue by ld9866** [veg/hyphy#1477]
Hello software developers!
I am a newcomer to use HYPHY, and I found that there is very little detailed method introduction to this software on the Internet. I will describe to you the analysis we want to do at present, and I hope you can tell us which module of this software we should use for calculation.
We have newly assembled a mammalian genome with some excellent properties and annotated it. Of course, this species has a reference genome. We currently hope to know the genes that have been specifically selected in our genome with excellent properties. We want to use your software for calculations, but we don't know where to start and hope you can give us some advice.
good luck!

**Comment by spond** [comment]
Dear @ld9866,

Take a look at http://hyphy.org/getting-started/ and http://hyphy.org/tutorials/CL-prompt-tutorial/.
We wrote a fairly comprehensive introduction to selection detection with HyPhy which you can find here http://hyphy.org/resources/tutorial-2017.pdf

Best,
Sergei

**Comment by ld9866** [comment]
Hello software developers!
A common approach to ensuring that this criterion is met is to perform alignment on the translated amino-acid data, and
then back-translate to the original nucleotides.
I saw this sentence in your tutorial, I am currently using orthofinder and the Single_Copy_Orthologue_Sequences file in there seems to meet what we need, how do I go to the original nucleotides?

**Comment by spond** [comment]
Dear @ld9866,

Yes, you need a multiple sequence alignment which produces in-frame (codon-aware, no frameshifts) alignment. It is very important to make sure that your alignment is done well, otherwise selection analyses may produce meaningless results.

One approach is to align translated amino-acid sequences using a standard MSA program (e.g. MAFFT), and then back-translate them to codons, using http://www.bork.embl.de/pal2nal/pal2nal.pdf or a similar tool.

We have a simple workflow for doing something like that with HyPhy scripts, see https://github.com/veg/hyphy-analyses/tree/master/codon-msa

You can also take a look at https://isu-molphyl.github.io/EEOB563/chapter3.pdf 

Best,
Sergei

**Comment by ld9866** [comment]
Thanks for your reply, l twill test if this works.

**Comment by ld9866** [comment]
Hello software developers!
As I told you before, we currently have 11 species of cds in fasta format. If we use cat to execute the reference document you gave us, the size of this fasta file is about 2G, and it seems that it takes a long time to execute the software. .
I saw in the literature that we can use "coding sequences of all "Single copy orthologous genes (SCOGs)" for alignment, we can currently get aligned Single copy orthologous fasta files in Orthofinder software, but what can we do to get the coding sequences that encode these amino acid sequences?
I feel that our difficulty is that we don't know how to compare the cds files of 11 files with MSA, which makes me very confused, I hope you can give me some help.

**Comment by vappiah** [comment]
Hi @ld9866 I have the same challenge. If you were able to solve the problem, I would be grateful if you can show me how to do it.

PS: I have also run orthofinder and have the results.

Thanks
