### ISSUE TITLE
aBSREL: species trees or gene trees?

### ISSUE THREAD

**Issue by Emilyaoc** [veg/hyphy#1484]
Hello,
Thank you for all the helpful advice on this site! I am a little unsure over whether it is more appropriate to use a species tree or a gene tree when running aBSREL. I have dataset of 50 species, and I am looking for evidence for variation between particular lineages in selection on immune genes. There is a good phylogeny for the 50 species, so I have a reliable species tree. However, it is likely that the genes I am looking at may not always follow the species tree. Is it better to use the species tree in the analyses or to generate gene-specific trees to feed into aBSREL for each analysis?
Many thanks for any guidance!
Emily

**Comment by spond** [comment]
Dear @Emilyaoc,

Generally it is better to use gene trees, because using a potentially incorrect species tree could have a similar effect to not modeling the effect of recombination: inflated false positive (or possibly false negative rates).

There's one caveat for lineage/branch based tests, like aBSREL. If you trees differ from gene to gene, tracking the identity of a specific branch (e.g. MRCA of some species) becomes gene-specific and more fiddly. This depends on what kind of aBSREL testing you want to do. If you always screen all the branches, it's not that much of an issue, since you can deal with the gene-to-gene variation during post processing/result tabulation.

Of course, you could always run aBSREL with the species tree *and* the gene trees; you could then compare and contrast the findings. Hopefully, for the majority of genes, the results will be largely congruent, but the genes where deviations are detected could, indeed, be instructive to look at.

Best,
Sergei
