### ISSUE TITLE
effect of gaps and multiple nucleotide substitutions

### ISSUE THREAD

**Issue by Suirotras** [veg/hyphy#1489]
I am running hyphy aBSREL for a lot of multiple sequence alignments to try to detect positive selection in a branch. It has been working greatly, but I just have some questions that I am unsure about. 

There are some alignments with a lot of large gaps or many smaller gaps. Would it be advantageous to remove these gaps before running hyphy aBSREL, or would it not have that much of an effect? if yes, do you know efficiënt programs that could do this for automatically in a script for many alignments.

Also, in a previous issue (https://github.com/veg/hyphy/issues/1119), you are describing that aBSREL can now account for MH rates with the options **--multiple-hits Double** or **--multiple-hits Double+Triple**. However, it is an old closed post and I can't find any other information about these aBSREL options. Are these options still available to use in the current version? If I don't specify anything, will it automatically incorporate MH rates or only single instantaneous nucleotide substitutions?

Thanks you for your time!

**Comment by aglucaci** [comment]
Hello Suirotras,

aBSREL with multiple-hits is still available. You can run it with aBSREL using the --multiple-hits Double or --multiple-hits Double+Triple command-line options. I recommend running the traditional aBSREL analysis, then running the analysis with Double, or Double+Triple hits as comparison. 

Gaps in the alignment at a reasonable level should have negligible effects on your results, however at high levels could pose an issue by forcing codons together into alignment sites, or at sites which contain mostly gaps, the ability to resolve selection.

Best,
Alexander

**Comment by spond** [comment]
Dear @Suirotras,

Generally I recommend keeping the gaps, since HyPhy treats gaps as fully missing data, and makes full use of partial information at individual sites. Of course, one concern with overall "gappy" alignments is whether or not they capture real homology are they are just a figment of MSA programs' imagination. Obviously, if there are out-of-frame or partial indels, this is an indication that something could be wrong with the alignment, something like...

```
C-T
C-T
CAT
C-T
```

Best,
Sergei
