### ISSUE TITLE
busted-mh using single and multiple species as foreground

### ISSUE THREAD

**Issue by MariangelaIannello** [veg/hyphy#1499]
Hi Sergey,
I am having troubles in interpreting some results I found with busted-mh, so I hope you can help me with that.
I am working on 30 species and I am interested in inferring signatures of positive selection in 4 of those. So I am using busted-mh (since I understand that not taking into account for multinucleotide mutations could give false positives), tagging as foreground these 4 species. I find that 40 out of 3000 genes have a significant pvalue for episodic positive selection in these 4 species. Anyway, if I try to run busted-mh tagging as foreground only one of these 4 species, I find only one gene with statistic support for signature of positive selection. I expected to find in this single species "rougly" the same genes found in the previuos analysis plus an additional set of genes with species-specific positive selection. Is it normal a result like this?
Thank you!
Mariangela

**Comment by spond** [comment]
Dear @MariangelaIannello,

Yes, this is normal, because you significantly reduce the power of the test by looking at fewer branches (4=>1). Generally speaking, using BUSTED on a single branch is always going to be quite underpowered (because this is like asking to detect selection from 2 sequences, effectively). 

Best,
Sergei

**Comment by MariangelaIannello** [comment]
Thank you very much Sergei!
