### ISSUE TITLE
Two questions about selection analysis

### ISSUE THREAD

**Issue by biozhajie** [veg/hyphy#1508]
Dear @spond

The first question: I got the individual k values among the selected branches (as the test set) estimated using general descriptive model are range from 0 to 2.5 with average equal to 0.77, but the k value from the hypothesis test (the selected branches as foreground  while the other unselected as background) are equal to 1.54 with the p value equal to 0.055.  Why the k values are so different from the two methods, and which should I used.

The second question: do the overall substitution rates have some relationships with the selection, i.e. may a change of the rates be correted with a change of selection?

Best,

Jie

**Comment by spond** [comment]
Dear @biozhajie,

(1). General descriptive `k` are NOT the same as the `K` estimated by the RELAX test. This is because they are not estimated relative to the same reference. In fact, the general descriptive rates are best viewed as pairwise relationships: if `k` for branch 1 > `k` for branch 2 then branch 1 is "intensified" relative to branch 2. You should use the `K` derived from the RELAX test in general

(2). Not really. More substitutions => better statistical power, but only to a point. Once exception (and why we recommend synonymous rate variation) is **hypervariable* sites, i.e. sites with many syn AND non-sys substitutions; these can trigger false positive selection signal (see Figure 2 in https://academic.oup.com/mbe/article/22/12/2375/1009535 for an example).

Best,
Sergei

**Comment by biozhajie** [comment]
Dear @spond 

Thanks your reply very much! 

Best,
Jie
