### ISSUE TITLE
site-level selection for highly divergent sequences

### ISSUE THREAD

**Issue by skyungyong** [veg/hyphy#1510]
Hi,

I am working with a set of highly divergent paralogous sequences I collected with HHsearch. BLAST fails to detect meaningful sequence similarities for many pairs of these sequences (sequences identity may go down below 15%), and homology is found only with more sensitive similarity search tools like hmmer. 

I've run FEL and MEME to detect site-level positive/negative selection on the alignment to mainly see whether structurally important sequences are under purifying selection pressure. But I am concerned that the sequences are too divergent, and this may be violating any important assumptions on the hypothesis testing.

Would there be any concerns on running hyphy on divergent paralogs?
Thank you!

**Comment by spond** [comment]
Dear @skyungyong,

You can run FEL and MEME on divergent sequences. There are two main concerns

1). Your alignment does not recover correct homology, in other words individual alignment columns bring together codons which are not related by descent. This might lead to false positives. This is **always** a danger with aligning such data. I strongly recommend doing amino-acid alignment (perhaps you already are) and then mapping back to codons. Sometimes even this may not be sufficient.

2). Loss of signal due to saturation -- the aligned positions **are** homologous, but they are too distant for reliable inference. Fortunately, in most cases, this leads to a "fail-safe" situation, where selection analyses will simply not find anything.

HyPhy has some built-in diagnostics (checking for infinite branch lengths), and if you see warning messages to that effect shown in console output, I would be cautious.

Best,
Sergei

**Comment by skyungyong** [comment]
Thank you for the clarification, @spond!
