### ISSUE TITLE
Positive selection analysis

### ISSUE THREAD

**Issue by ufuomababatunde** [veg/hyphy#1521]
Hello.

I'd like to do a positive selection analysis but can't find the `MFPositiveSelection.bf` template. Is there a workaround or a new template for this one?

Thank you for anyone who can help.

**Comment by spond** [comment]
Dear @ufuomababatunde,

The analysis you refer too is very old and hasn’t been maintained since ‘00s. Can you elaborate on what type of selection analysis you wish to run? You may want to look at http://hyphy.org/resources/tutorial-2017.pdf for an overview of available options. There are other analyses available as well. 

Are you specifically interested in a particular functionality of MFPositiveSelection, such as the ability to jointly analyze several alignment files at once?

Best,
Sergei

**Comment by ufuomababatunde** [comment]
Hello @spond,

I've skimmed through the link you shared and I think this is it. I will try this out.
Thank you for your quick response.

Best,
Ufuoma
