### ISSUE TITLE
Reviews requesting multiple hypothesis testing corrections when using BUSTED-PH and RELAX

### ISSUE THREAD

**Issue by mbarkdull** [veg/hyphy#1523]
Hello all, 

I am working on a project using BUSTED-PH and RELAX to assess whether there are differences in (1) the genome-wide proportion of genes under positive selection in a group of species with a focal trait vs. the proportion under positive selection in the species lacking the trait, and (2) whether the presence of the focal trait is associated with a shift towards relaxed or intensified selection genome-wide. 

One of the reviewers has asked about multiple hypothesis testing corrections, since I am testing ~10,000 orthogroups for positive selection and selection intensity. I know that this issue has been briefly addressed elsewhere for other uses of these methods, but I'm hoping to check that my understanding is correct in responding to this review. 

Is it appropriate to simply use the p-values from BUSTED-PH and RELAX when categorizing a gene as _positively selected in the foreground/positively selected in the background_, or as _under relaxed selection/under intensified selection_? To me, these appear to be independent tests, as you have previously pointed out when the issue of multiple hypothesis testing correction is raised. 

I greatly appreciate your input!
- Megan

**Comment by spond** [comment]
Dear @mbarkdull,

For a discovery-type analysis, where you are screening a large number of genes and **inferring** attributes, something like false discovery rate (FDR) correction would be my recommendation. A p-value of 0.05 for an individual test would imply that if all genes were neutral (the worst case), you would expect 500 false positives / 10,000 comparisons, which is not acceptable. Doing a very strict family-wise error rate correction (to which Bonferroni belongs for example), is an overkill because it would attempt to limit the rate of ONE OR MORE false positives to some level, e.g. 0.05. You are likely to remove a lot of true positives with such a stringent correction.

False  Discovery Rate controls the fraction of your positive tests that are false positives, so with say 1000 positive tests and q-value of 0.10, you could argue that no more that 100 of those are false positives.

Real data almost never have strictly neutral genes, meaning that the worst case scenario is very unlikely, so you are likely going to overcorrect for multiple testing even with FDR, but I would suggest you do it, and then see if the results change. 

Even with FDR, though you need to have p-values on the order of 0.05/10000 to get ANY positives, so if you have a smaller dataset, you may end up with no signal, or very few selected genes. 

Would you mind attaching the list of your raw p-values here? I might be able to give you better advice based on what they look like.

Best,
Sergei

**Comment by spond** [comment]
Dear @mbarkdull,

GitHub strips out attachments if you respond via e-mail. Could you please attach them while responding to the message directly through a web form?

Sorry,
Sergei

**Comment by mbarkdull** [comment]
Yes, absolutely-my apologies. They are attached here. 

Thank you!
Megan 

[workerPolymorphismRelax.csv](https://github.com/veg/hyphy/files/9617125/workerPolymorphismRelax.csv)
[workerPolymorphismBustedPH.csv](https://github.com/veg/hyphy/files/9617126/workerPolymorphismBustedPH.csv)

**Comment by spond** [comment]
Dear @mbarkdull,

Take a look at https://observablehq.com/@spond/evaluate-different-forms-of-multiple-testing-correction

As expected, you get **very** conservative results for FWER (Bonferroni, Holm-Bonferroni) corrections, but for RELAX, uncorrected p-values are roughly equivalent to 15% FDR (typical q-values you see used are .1-.2)

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/1018513/191536895-ba5b9d58-1e88-4152-bed6-06b76b1356a6.png">

For BUSTED-PH it also also very similar:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1018513/191537285-d9e25135-8780-43fa-8b39-0d13435a0049.png">

My advice would be to state in your response that you can update the manuscript by presenting significant results as those that have Benjamini-Hochberg FDR of somewhere between 0.1 and 0.2.

Best,
Sergei

**Comment by mbarkdull** [comment]
Thank you so much for this feedback- this is really useful. 

I do have one more question about applying Benjamini-Hochberg FDR to the BUSTED-PH results. Since BUSTED-PH returns three p-values, how would you go about correcting these results? Simply apply the Benjamini-Hochberg FDR to each of the three tests independently? Or somehow correct for both the number of genes being tested and the number of tests applied to each gene?

Thank you so much!
-Megan

**Comment by spond** [comment]
Dear @mbarkdull,

BUSTED-PH does a Holm-Bonferroni correction for each set of 3 p-values it reports (i.e. per gene correction). So you don't need to **further** correct them. You can apply BH to each of the three sets separately. 

Best,
Sergei

**Comment by mbarkdull** [comment]
Wonderful- that is what I suspected, but I am glad to confirm. 

Finally- in this project, I am also testing a small set of specific candidate genes with known functions in my traits of interest. In these cases, do you think it would be appropriate to use the raw p-values from RELAX/BUSTED-PH, or should I stick with FDR corrections as well?

Thank you!
-Megan

**Comment by spond** [comment]
Dear @mbarkdull,

Well, it's a bit tricky. 

I would run FDR but with a correction for the smaller set of test (N = the number of a priori candidate genes), if your genes were defined **a priori** without looking at any of the test results. In this case you don't need to do the full correction (N = total number of genes tested).

Best,
Sergei

**Comment by mbarkdull** [comment]
I see- that latter case described what I did. I'll correct according to that approach. 

I very much appreciate your assistance; this has been hugely helpful. 

Best, 
-Megan

**Comment by spond** [comment]
Dear @mbarkdull,

No problem. Happy to do it, especially since these types of questions are quite common. Good luck with responding to reviewers. I would be content with the proposed response as a reviewer, especially since it's not likely to alter your downstream conclusions.

Best,
Sergei
