### ISSUE TITLE
BUSTED outfiles vs Hyphy Vision Data

### ISSUE THREAD

**Issue by bob100077** [veg/hyphy#1578]
I'm looking for the best way to interpret the results of BUSTED.
I am running BUSTED on Hyphy 2.5.36 via conda. The main result seems to be a table of Selection, dN/dS, Proportion, and Notes.
If I upload the .json file to Hyphy Vision, I can easily see the number of sites with ER>=10 for positive selection, the p-value, and other information like the number of sequences or the total codon sites in the alignment. 
Is there a way to access this type of information directly from the BUSTED outfiles? I am working with a couple of hundred gene families, and uploading each to Hyphy Vision is not feasible. Is there a way to get this information from the .json file?
I'm likely missing something, but any help would be greatly appreciated :)

Best,
Chris

**Comment by stevenweaver** [comment]
Dear Chris, 

Sure. Please see @sjspielman's excellent documentation of the JSON results files. There is an entire section on BUSTED. 

https://hyphy.org/resources/json-fields.pdf

If you have any additional, specific questions on how to obtain what you are looking for from the `json` file, I'd be able to help. Command line tools like `jq` might prove useful when working with `json`. Otherwise, JSON support is usually available in the programming language of your choice.

Best,
Steven
