### ISSUE TITLE
Selection analysis input tree

### ISSUE THREAD

**Issue by filonico** [veg/hyphy#1579]
Dear @spond, I've been using HyPhy to test selection hypothesis for several months and I'm still debating with my collegues about several aspects regarding the input phylogenetic tree:
1. first of all, in your opinion, is it better to use the species tree or the gene tree? I think both of them may be informative in selection analyses, but I tend to use the species tree, which is more logical in my mind.
2. assuming I'm using the species tree as the input tree, what is the influence of the given branch lengths on the analyses? I mean, is there any significative difference if I use the species tree without branch lengths (i.e., the cladogram) or if I use the species tree with branch lengths optimized on the gene tree (i.e., the corrected gene tree)? I know HyPhy re-compute the branch lengths of the user-specified tree, but are the user-specified branch lengths taken into account at all?

Thanks a lot anyway for this set of tools!

**Comment by spond** [comment]
Dear @filonico,

1. This question comes up **all the time** :) I don't usually worry about it to much in my practical applications because we either study single genes or viruses with short genomes. My "stock" answer is to use gene trees (see https://github.com/veg/hyphy/issues/1558 for example). It may be worth just running both options and see what the difference is.

2. User-specified branch lengths for MOST analyses (all commonly used selection analyses) are taken as starting values for the optimization step. They are not used for anything else. Providing "reasonable" branch lengths can slightly reduce run times.

Best,
Sergei
