### ISSUE TITLE
Datamonkey: FEL figure1 = RuntimeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by eibnerg** [veg/hyphy#1583]
Hi HyPhy/DM Team,

I'm receiving this error: "figure1 = RuntimeError: Cannot read properties of undefined (reading '0')" on any of the available  FEL Plot types.
The plot does not generate and it just shows the error message.
This happens with various input files which don't cause problems with any other methods.

Regardless, thank you very much for providing such excellent tools for research!

Best,
Georg

**Comment by spond** [comment]
Dear @eibnerg,

I'll tag @stevenweaver who does most DM development. I am not sure what the issue is on Datamonkey. You can download the JSON results by appending `/results` to the URL and feed them into the FEL visualization notebooks on Observable (which is where DM pulls the code from). Both of your results files display just fine there, so something must be happening because of notebook embeddeding.

https://observablehq.com/@spond/fel?url=https://www.datamonkey.org/fel/641b5cde56793b5e1e6168e7/results

https://observablehq.com/@spond/fel?url=https://www.datamonkey.org/fel/641bf91656793b5e1e6185c4/results

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

I'm using https://observablehq.com/@hyphy_software/fel-analysis-result-visualization?url=https://www.datamonkey.org/fel/641b5cde56793b5e1e6168e7/results for Datamonkey. 

I can update the notebook. I'm not dynamically including the notebooks because 1) Observable may change their API at any time and 2) freedom to update notebooks without fear of repercussion on the production site. 

Best,
Steven

**Comment by stevenweaver** [comment]
Fix has been deployed.

**Comment by eibnerg** [comment]
Amazing! Let me know when you're in Berlin so I can buy you a beer =)
