### ISSUE TITLE
GARD Internal error in _LikelihoodFunction::ConjugateGradientDescent

### ISSUE THREAD

**Issue by tbigot** [veg/hyphy#1594]
Hi,

I’m having a problem running HYPHY with GARD. I have this kind of error:

`Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-6227879.055521984] does not match the last recorded LF maximum [-5227974.756559206]`

My command: `mpirun HYPHYMPI gard --type nucleotide --rv GDD --model JTT --rate-classes 4 --mode Faster --alignment nt.aln.fasta --output nt.aln.json`

I can provide data or more complete logs if needed.
Thanks in advance,
Thomas

**Comment by spond** [comment]
Dear @tbigot,

Can you please let me know which HyPhy version you are using (`hyphy --version` or `HYPHYMPI --version`)?

Try adding `ENV="TOLERATE_NUMERICAL_ERRORS=1;" to your comman line call and see if that lets the job run to completion.

Would you be filling to share the input files with me (privately if needed) so that I could reproduce the error and try to resolve it more systematically?

Best,
Sergei

**Comment by tbigot** [comment]
Thanks! I’m using the last GIT commit (`41306280822033d0b6d9432cee8f7ed4051ee4d5`) `HYPHY 2.5.48(MPI) for Linux on x86_64`.

It is public data, you’ll find them at:
https://dl.pasteur.fr/fop/8NIIUfny/nt.aln.fasta.gz

**Comment by tbigot** [comment]
I can also provide the intermediate file generated by Gard, with the checkpoint data, it makes the software end a lot faster (because it re-uses the already computed results), if it helps! 🙂

**Comment by spond** [comment]
Dear @tbigot,

Sorry for letting this drop; can you please re-share the data.

Best,
Sergei
