### ISSUE TITLE
The non-synonymous/synonymous rate ratio for test in datamonky represents the dn-ds of the entire gene ?

### ISSUE THREAD

**Issue by douluojiaofu** [veg/hyphy#1607]
Dear doctor, Thank you for watching this question!

I'm using datamonky-slac to detect positive selection site,and I get a result.

I have seen in some articles that some researchers believe that the red content below is the dN-dS of the whole gene. I am not sure whether this index is the dN-dS of the whole gene?? If it can not represent the dn-ds of the entire gene ,how can i get the dN-dS of the whole gene by hyphy ?

I would really appreciate it if i could get your help!
![dbe481676c2d8710258acd5355ed852](https://github.com/veg/hyphy/assets/105349016/29b2d70a-6e14-4b2f-94f5-2d896c47613e)

**Comment by spond** [comment]
Dear @douluojiaofu,

The number you circled is the `dN/dS` ratio estimated from the entire gene (which is what you usually see reported). I don't recommend reporting gene-level `dN-dS`. The reason SLAC uses site-level `dN-dS` is because using the difference instead of the ratio allows you to handle `dS = 0` cases.

Best,
Sergei

**Comment by douluojiaofu** [comment]
Dear doctor, Thank you for your help!

**Comment by douluojiaofu** [comment]
Dear doctor, Thank you for your help!
I will report the dN/dS  of the positive sites in my article.
Thank you again for your help!
