### ISSUE TITLE
Effect of tree size on the power to detect diversifying selection at a single branch?

### ISSUE THREAD

**Issue by Suirotras** [veg/hyphy#1635]
Hi,

I have a question about the effect of decreasing tree size on the positive selection detection in one branch (aBSREL).

I have a large tree (and alignment) representing 241 mammalian species. Personally, I am only interested in (episodic) diversifying selection in a single branch of this tree. Because of the large computational load of running aBSREL with this huge tree, I was planning on decreasing the size of this tree and alignment to just 100 mammalian species. I am planning to primarily remove the shortest branches, while keeping the diversity of the tree as large as possible.

My question is, would this change have a large effect on the power to detect diversifying selection in my branch of interest? Or is this dependent on many different aspects of the sequences in the alignment?

Here is what I plan to do:
The large unpruned tree (with 241 species):
![image](https://github.com/veg/hyphy/assets/91290224/5b5a5131-72b2-49c7-a78f-3c9c52eb7ee3)

The pruned tree (with 100 species):
![image](https://github.com/veg/hyphy/assets/91290224/97daa4a8-c328-417b-a4ab-1bfa0f84c53c)

Many thanks for your help and your work on HyPhy!

Sincerely,
Jari

**Comment by spond** [comment]
Dear @Suirotras,

If you are interested in a single branch, I would say you should keep that branch and its local neighborhood (nearest taxa) intact, and prune more distant clades.

It depends on taxonomic sampling, but one of the strongest predictors of `aBSREL` performance is branch length. If you look at the salient figure in the original manuscript you will notice that the power to detect selection climbs as the branch length increases, a certain "saturation" point (~1 sub/site).

<img width="324" alt="image" src="https://github.com/veg/hyphy/assets/1018513/a02baed3-89e9-401d-84b7-d3a933778bdc">

So when you prune the tree, focusing on a single branch, be careful to not "merge" this branch with those you delete.

For example, if the focal branch of the "complete" tree is like this (this is the data from `tests/data/yokoyama.rh1.cds.mod.1-990.nex` in the HyPhy distribution).

<img width="333" alt="image" src="https://github.com/veg/hyphy/assets/1018513/0b247680-04a9-42a6-9029-32cd70450094">

Then a good way to subsample would be like this ("bubbles" here mean : replace clade with one representative sequence).

<img width="294" alt="image" src="https://github.com/veg/hyphy/assets/1018513/08b31729-9126-4bfa-b76a-f94d8249a121">

You do NOT want to delete branches around the focal branch (like in the following picture), because you might subsume their evolutionary content into the "combined" branch, and thus conflate selection that might be happening up or down the tree.

<img width="329" alt="image" src="https://github.com/veg/hyphy/assets/1018513/edfb27cc-d0f3-4742-b742-10df14a5904f">

All of the above applies (largely unchanged) to internal test branches, except for those you want to prune the tree in a way that maintains the clade which radiates from the internal node.


Best,
Sergei

**Comment by Suirotras** [comment]
Hi @spond,

This is very useful. Thanks for the detailed answer!

Best,
Jari
