### ISSUE TITLE
How does hyphy deal with branch lengths? 

### ISSUE THREAD

**Issue by siribi** [veg/hyphy#1637]
Hi, 

I'm slightly confused about how hyphy treat branch lengths when running aBSREL and RELAX: 

1) Are the branch lengths in the tree file used, or are new branch lengths calculated based on the alignment?
(I'm used to running codeml in PAML, and there you have the option to ignore branch lengths in the given tree and recalculate them from the data).

2) If the branch lengths from the tree are used , should they be defined as the expected number of nucleotide substitutions per nucleotide site, or as the expected number of nucleotide substitutions per codon? 

The reason why I'm asking is because I'm interested in using a species tree from timetree.org, but the branch lengths are given in million years. 

Thank you!

**Comment by spond** [comment]
Der @siribi,

1. If branch lengths are provided, HyPhy will use them as **starting guesses** for optimization. In every common analysis, including `aBSREL` and `RELAX`, branch lengths are re-estimated, usually progressively: first with a simple nucleotide model, then a simple codon model, then a more complex codon model, then the final model for the analysis. 

2. HyPhy expects branch lengths to be specified as expected subs/nucleotide site. 

If branch lengths are given in millions of years, then all that is likely to happen is that the initial optimization will start in a bad spot (since the guesses are in wrong units), and might take longer to complete.

Best,
Sergei

**Comment by siribi** [comment]
Dear Sergei, 
Thank you so much for your quick answer! That made things much clearer. 
Good to know that it should be possible to use the species tree from timetree.org even if the units of the branch lengths are wrong. 
Best, 
Siri

**Comment by Buckaroo1** [comment]
Dear @siribi

Consider delecting the branch length while using a tree from timetree.org.
See [If the branch lenghth in species tree are necessary in my analysis using hyphy? #1690
]{https://github.com/veg/hyphy/issues/1690#issuecomment-1960642875)

Sincerely,
Buckaroo
