### ISSUE TITLE
aBSREL - understanding output

### ISSUE THREAD

**Issue by mlcossette9224** [veg/hyphy#1655]
Hello, 

I ran aBSREL between single-copy orthologs of 20 different species to test for selection. I was wondering how to interpret positive selection at a node but not found in the descendants or only some of the descendant. In the first scenario would that mean that all descendants have the same mutations at a specific area compared to all other species making the ancestor come out as having significant selection but because all of the descendants share it they technically don't come out as significant in them? My data is good and the alignments look good so it doesn't seem like there is an issue with incomplete data or bad alignments. 

Thanks,
Marie

**Comment by stevenweaver** [comment]
Dear @mlcossette9224, 

Please see this excellent [post](https://github.com/veg/hyphy/issues/1224#issuecomment-697327350) by @spond answering a similar question in 2020. 

Specifically, 
>  For example, you can have episodic selection occurring at an internal branch followed by neutral evolution or negative selection. This is actually quite common.

For your possible explanation, no selection being found due to descendants inheriting the advantageous mutation from the ancestor and no longer mutating is a plausible scenario, but might require confirmation by viewing the alignment itself instead of wholly relying on aBSREL. 

Best,
Steven

**Comment by spond** [comment]
Dear @mlcossette9224,

If you have a specific a priori hypothesis, i.e. "I am looking at the clade with shrews", then you will get better statisitcal power to detect selection if you *restrict* the analysis only to those branches. This requires some tree annotation, which can be done manually (e.g. if you are using a single species tree); see http://hyphy.org/tutorials/phylotree/; or programmatically (you have lots of trees, e.g. gene trees), see https://github.com/veg/hyphy-analyses/tree/master/LabelTrees

Also, you may want to run BUSTED on the entire clade of shrews -- you will get more power to detect selection on the entire clade (as opposed to on individual branches).

Best,
Sergei
