### ISSUE TITLE
GC-biased gene conversion busted

### ISSUE THREAD

**Issue by Apis-DeLorian** [veg/hyphy#1657]
Hello,

I would like to run BUSTED on several genes for a group of insect species. Many of these species have high genome-wide recombination rates, with crossovers not relegated to hotspots. Also, there is widespread evidence of GC-biased gene conversion in many of these species. If I understand correctly, to account better account for the effect recombination, I should first run GARD, and provide that output to BUSTED. For BUSTED, am I correct in thinking that allowing for synonymous rate variation will in part prevent false positives of selection that GC-biased gene conversion events can cause? Are there additional parameters that I could apply to better account for GC-biased gene conversion when running BUSTED?

Thank you for your time,

Tim

**Comment by spond** [comment]
Dear @Apis-DeLorian,

GARD will help with gene conversion (recombinant like signal), but not with GC bias variation.

If I understand you correctly, you have variable GC bias across taxa in a single tree. In that case, depending on how bad it is, and how many sequences are involved, you may potentially obtain biased results due to the fact that the models used by BUSTED assume that base frequencies don't change (much) across the tree.

It's hard to say what the effect would be but you could try some sensitivity analyses where you see if BUSTED results change a lot if you remove some of the sequences with different GC content.

You should always (by default) include synonymous rate variation as well.

Best,
Sergei
