### ISSUE TITLE
aBSREL foreground lineages

### ISSUE THREAD

**Issue by JuliaLopezDelgado** [veg/hyphy#1669]
Hello,

I am planning on using aBSREL to identify signatures of positive selection across seven foreground lineages, which are composed of individual species and also internal nodes with all descendants. As per the image attached, I want to test for selection in 1 (including A-J), 2 (including A-D), 3 (including B-D), A, B, C, and D. 

![Foreground nwk](https://github.com/veg/hyphy/assets/63849203/4689188c-75bd-48aa-a1e3-9bbf9cde450a)

Would I need to label seven foreground lineages with https://github.com/veg/hyphy-analyses/tree/master/LabelTrees and then run aBSREL seven times for each ortholog (I have >6,000 genes)? Would you recommend aBSREL over BUSTED for my analysis?

Thanks in advance!

**Comment by spond** [comment]
Dear @JuliaLopezDelgado,

1. If you are using a species tree (as opposed to a gene tree), you can label all 7 branches with one tag (for aBSREL and BUSTED), and then pass `--branches tag` (replacing `tag` with whatever you use) on the command line.
2. `BUSTED` and `aBSREL` will answer different questions. `BUSTED` will generally have more power (because it uses all 7 branches together), but you won't be able to tell which branch(es) are driving the signal. `aBSREL` will resolve individual branches (if possible), but may lose power because each branch is considered in isolation and will also be subject to multiple testing correction.


HTH,
Sergei

**Comment by JuliaLopezDelgado** [comment]
Hello,

Thanks for your quick response!

I am using gene trees, so for each ortholog I have a nucleotide fasta alignment and a gene tree. I guess this means I have to label the foreground lineages and run them separately? Also, do I still need to specify the `--branches tag` if I have previously labelled the foreground lineages in each gene tree?

For my analysis, I would need to know which branches are driving the signal. Since (I think) I will need to run each foreground lineage separately, then it might make more sense to use `BUSTED`?

Best,
Julia

**Comment by spond** [comment]
Dear @JuliaLopezDelgado,

1. There is a way to label trees programmatically. Take a look at https://github.com/veg/hyphy-analyses/tree/master/LabelTrees

2. `aBSREL` is the way to go based on what you describe, and yes, you need to specify the `--branches` argument, because otherwise the analysis will test **all** branches. This will take longer **and** will reduce power (because more tests will be done). Youl could also consider using the `--srv Yes` option to enable support for site-to-site rate variation.

Best,
Sergei

**Comment by spond** [comment]
Dear @JuliaLopezDelgado,

1. It is highly inefficient to run `aBSREL` 7x to test 7 branches. You will be redoing 90+% of the work in each run, and also not applying the right multiple testing correction. You should instead label all the branches as the same group (e.g. `test`) and run `aBSREL` with that group selected.
2. Can you please elaborate on your labeling issues? Why are looking to have multple labels per branch? Could you please provide an example tree and the desired labeling?

Remember, that `aBSREL` tests for selection on individual branches. In your example tree above I would simply select the following subset of branches and test them in `aBSREL`. Then you can draw conclusions about lineages (paths), based on what the constituent branches return.

<img width="326" alt="image" src="https://github.com/veg/hyphy/assets/1018513/653c78a2-b52d-4312-b8b4-ec2ee80379f5">

Alternatively, you could use `BUSTED` to test for selection jointly on a group of branches (one group = one test), for example for Group 3 above 
<img width="308" alt="image" src="https://github.com/veg/hyphy/assets/1018513/42f0b9d1-7124-4861-92d0-dbb2572c31d3">

Best,
Sergei

**Comment by JuliaLopezDelgado** [comment]
Hi @spond,

Thanks for letting me know! 

I need to test for positive selection at different levels: species (A, B, C, D), genus (B-D) and family (A-J). I thought I needed to set different foreground lineage labels to specify this (eg. the fact that I want to test D as a species but also as part of the genus B-D and the family A-J. Can I test this by specifying the family A-J as the foreground lineage (as you highlighted in the first figure) but still identify species-level and genus-level selection?

Best,
Julia

**Comment by JuliaLopezDelgado** [comment]
Dear @spond,

Great! I am running aBSREL with the family set as the foreground lineage. 

Thanks so much for all your help, I really appreciate it. 

Best,
Julia

**Comment by spond** [comment]
Dear @JuliaLopezDelgado,

`aBSREL` (and most HyPhy analyses in general) require that there be a 1-1 match between the tree and the alignment. In your situation you may want to use something like `trim-tree.bf` from https://github.com/veg/hyphy-analyses/tree/master/LabelTrees to take an alignment and a "master" tree with all the species, and write out a `NEXUS` file with the alignment + trimmed tree.

Best,
Sergei

**Comment by JuliaLopezDelgado** [comment]
Dear @spond,

Thanks for clarifying! I have already been using pruned species trees that only contain the representatives present in each alignment but just wanted to check. 

Best,
Julia

**Comment by JuliaLopezDelgado** [comment]
Dear @spond,

LabelTrees hasn't labelled one of the nodes I need to test. Here is a snippet of a tree that has 20 species, although I am only interested in testing for selection on the four species shown, as well as Node1, Node 31 and Node33:
![image](https://github.com/veg/hyphy/assets/63849203/3d187242-f574-4cb0-9c12-0347ed2822b4)

I labelled the foreground lineage with LabelTrees as follows (gal.txt lists the four species):
$hyphy $LabelTrees --tree tree.nwk --list gal.txt --output out.nwk

However, Node1 doesn't appear labelled as Foreground (as shown above) and aBSREL hasn't tested this node either. Is there any way to specify this lineage as foreground?

Many thanks,
Julia

**Comment by spond** [comment]
Dear @JuliaLopezDelgado,

Is `Node1` the root or are there nodes more ancestral to it?

`HyPhy` in general and `LabelTree` in particular will assume unrooted trees, because all of the selection models in common use are time reversible. You can override it at the labeling stage (add `ENV="ACCEPT_ROOTED_TREES=1" to the command line), but this won't make any difference at the selection screening stage, where the trees will be unrooted automatically.

Best,
Sergei

**Comment by JuliaLopezDelgado** [comment]
Dear @spond,

There are other nodes more ancestral to Node1. 

I just tried the following command but I get the same labels as in the image attached above, with Node1 not being labelled as foreground: 
`$hyphy $LabelTrees --tree tree.nwk --list gal.txt --output out.nwk ENV="ACCEPT_ROOTED_TREES=1"`

Is there anything else I could try?

Many thanks,
Julia
