### ISSUE TITLE
MEME errorcode1 repeated message issues

### ISSUE THREAD

**Issue by cmariencheck** [veg/hyphy#1692]
Hi, 

I have been trying to run MEME with several different files (see attached) and some files (TLR7; TLR8) will be continuously rejected with the attached error code message ( MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1; PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741). Any recommendations on changes to help avoid these errors? Attached is another file I made that was accepted with no issues.  

Thank you!
Clara
[MSL3_tree_aligned.txt](https://github.com/veg/hyphy/files/14424127/MSL3_tree_aligned.txt)
[TLR7_tree_combined_file.txt](https://github.com/veg/hyphy/files/14424128/TLR7_tree_combined_file.txt)
[TLR8_tree_sequence_combined.txt](https://github.com/veg/hyphy/files/14424129/TLR8_tree_sequence_combined.txt)
[error_log_TLR8.txt](https://github.com/veg/hyphy/files/14424131/error_log_TLR8.txt)
[error_log_TLR7.txt](https://github.com/veg/hyphy/files/14424132/error_log_TLR7.txt)

**Comment by spond** [comment]
Dear @cmariencheck,

The issue appears to be caused by the mismatch between the tree/taxa list of the NEXUS file and the sequences actually present. For example, in `TLR7`, the tree and the `TAXA` block refer to `Pan_troglodytes_verus` while the `MATRIX` block refers to `Pan_troglodytes`. HyPhy gives precedence to sequence names from the `MATRIX` block if present. Simply editing those (`Pan_troglodytes` -> `Pan_troglodytes_verus` and `Cercocebus_torquatus` -> `Cercocebus_torquatus_atys`) resolves the issue.

Similar issues affect `TLR8`.

Best,
Sergei

[TLR7_tree_combined_file.txt](https://github.com/veg/hyphy/files/14438338/TLR7_tree_combined_file.txt)

**Comment by cmariencheck** [comment]
Hi @spond 

Thank you for your response! I see the issue with the TLR7 file but those were already remedied with the TLR8 file. Is there something else wrong with it?

Best, 

Clara

**Comment by cmariencheck** [comment]
Hi @spond 

The issue is now arising with an expanded format of the MSL3 file where I just added 2 more taxa. It is attached, and I am getting the same error message. See attached files. Please advise. 

Clara[
[MSL3_tree_seq_combined.txt](https://github.com/veg/hyphy/files/14465093/MSL3_tree_seq_combined.txt)
[MSL3_error.txt](https://github.com/veg/hyphy/files/14465095/MSL3_error.txt)
](url)

**Comment by spond** [comment]
Dear @cmariencheck,

Right, I see. This is not an issue with your data. It's a numerical instablity warning in `HyPhy`

@stevenweaver : could we enable `ENV="TOLERATE_NUMERICAL_ERRORS=1;"` by default on all datamonkey analyses?

Best,
Sergei

**Comment by stevenweaver** [comment]
Completed
