### ISSUE TITLE
No JSON file output from absrel

### ISSUE THREAD

**Issue by ShanfenO** [veg/hyphy#1693]
Dear @spond ,
       When I run the command ：
"hyphy absrel --alignment TAS1R1.align.mafft.trimal.cds.afa.genome.filtered.species.fasta --tree tree.newick > TAS1R1.hyphy.log"
,only a log file is generated without any JSON file output. Could you tell me what might have gone wrong?Many appreciate you!

Sam

**Comment by spond** [comment]
Dear @ShanfenO,

Are there any error messages in the log file? If the analysis terminates prematurely, the `JSON` file may be empty.

Best,
Sergei

**Comment by ShanfenO** [comment]
Dear @spond,

[TAS1R1.hyphy.out.txt](https://github.com/veg/hyphy/files/14446417/TAS1R1.hyphy.out.txt)
This is one of my log files.I dont see error messages expect "duplicate sequences​".But there no JSON file make.

Best,
Sam

**Comment by spond** [comment]
Dear @ShanfenO,

1. For the `aBSREL` run the log file indicates that the analysis did run to completion. Is the file at /slurm/home/zju/zhanglab/shenxulan/01.project/hyphy_work/00.data/TAS1R1/TAS1R1.align.mafft.trimal.cds.afa.genome.filtered.species.fasta.aBSREL.json` empty?
2. For the `50nt` file, if the alignment is not coding and in-frame, then you will see such an error. `RAxML` usually takes in nucleotide data, so it won't care if the sequences are not in frame.

Best,
Sergei

**Comment by ShanfenO** [comment]
Dear @spond ，
  1.There are no JSON files generated at all, so I am confused.
  2.Do you have any better suggestions for modifications?
  Thanks.
Best,
Sam

**Comment by spond** [comment]
Dear @ShanfenO,

1. I am not sure what is going on, because it could be system specific. Perhaps the process can't write to the directory. If you are running `hyphy` via schedulers, this could often be the case. It's also possible that the file is being written somewhere else if you spacified the `--output` option on the command line. I would try `aBSREL` outside the scheduler for a test run just to make sure that `json` files are being generated as expected.

2. I can't really give you meaninful advice on data clean-up and alignment generation without knowing a lot more about how you are obtaining, trimming, and aligning your sequences. For this specific example, you could simply trim off the last two nucleotides from each sequence. As a word of caution, something as short as **50** nucleotides will be tricky to build trees for and may have other statisitcal issues. A 16-17 amino-acid long protein is probably an incomplete fragment of something larger.

Best,
Sergei

**Comment by ShanfenO** [comment]
Dear @spond ,
    Thank you very much for your help. I'm going to try switching servers and using other ways to see if that can solve these problems. As I am a beginner in bioinformatics, I might have many questions, so I really appreciate your enthusiasm.
Best,
Sergei
