### ISSUE TITLE
aBSREL run time

### ISSUE THREAD

**Issue by lagphase** [veg/hyphy#1712]
Hello Sergei, 

I am running aSBREL on a 21 Mb alignment, hyphy version 2.5.36. The analysis has been running for over 1 day and it's still at 

> "Fitting the baseline model with  a single dN/dS class per branch, and no site-to-site variation."

Do you know approx. the run time for this alignment size? Do you think a newer hyphy version would speed up the process? Thanks.

**Comment by spond** [comment]
Dear @lagphase,

1. I would suggest updating to the latest `HyPhy` version. We did a lot of work in the recent 2+ years to improve speed. 
2. How many sequences are in the alignment?

Best,
Sergei

**Comment by lagphase** [comment]
Hello Sergei,

Thanks for your prompt response. The analysis has stopped with errors.

I have 12 sequences in my alignment (attached below). Could you take a look and let me know what went wrong? Thank you.
[pal2nal-12-seqs.fas.gz](https://github.com/veg/hyphy/files/15406741/pal2nal-12-seqs.fas.gz)


```
> Error:Internal error 
>  
> 	ERROR: [_LikelihoodFunction::LocateTheBump (index 65) current value   -25775513.04835993 (parameter =   0.9992685062681751), best value   -25775513.04835992 (parameter =   0.9992685062681751)); delta = 3.725290298461914e-09, tolerance =                
> 
> Parameter name NGYEXnlA.tree_0.N4.delta
> Internal error 
>  
> 	ERROR: [_LikelihoodFunction::LocateTheBump (index 65) current value   -25775513.04835993 (parameter =   0.9992685062681751), best value   -25775513.04835992 (parameter =   0.9992685062681751)); delta = 3.725290298461914e-09, tolerance =                
> 
> Parameter name NGYEXnlA.tree_0.N4.delta

```

**Comment by lagphase** [comment]
Hello Sergei,

Based on previous issues, it seems like if I add `ENV="TOLERATE_NUMERICAL_ERRORS=1;"` in the command line, the problem would be solved??

I used the interactive prompts `hyphy -i `, but I just restarted the analysis using command line with added the line above. Hope this will work this time.

**Comment by lagphase** [comment]
Hello Sergei, 

The analysis succeeded in ~ 8 hours., which was fantastic!! I have a question regarding aBSREL results which indicated that the branches I labeled as Foreground are under positive selection. But is this result relative, e.g. does this  mean other unlabeled branches (background) are not under selective pressure?  Or the method completely ignore other background branches?

**Comment by spond** [comment]
Dear @lagphase,

`aBSREL` does not do any testing on background (not selected branches). They could be under any kind of selection, including positive selection.

Also, in v 2.5.62, I added an option to `aBSREL` to support bag of little bootstrap upsampling approach (see https://pubmed.ncbi.nlm.nih.gov/34734192/ for more details). You can specify, `--blb 0.7` and run `aBSREL` 10 or so times, each time with a different random sample of your data. Because of what `blb` does, each analyses should be much faster than the full original analysis. You can then average, or take majorities, over replicate results.

Best,
Sergei
