### ISSUE TITLE
suggestions about running negative selection analysis - if thats what happening

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#1748]
hi all

Any advice will be greatly appreciated.

I am looking at a bunch of bacterial genomes and there are certain genes that seem to slowly dissapear from isolates that were collected at  a later point (e.g. after 2016).
When looking at the annotation tables, i can see that the occurrence of these genes in the genomes went from being often twice in the genomes to being there only once (single copy orthologs) or not at all. 
I have extracted the genes and the alignments show that occasionally the branches of the trees they form may be split based on the time they were collected. 
All of that (IMO) suggest that either these genes are no longer useful or some variants of these genes are getting eliminated suggesting negative/purifying selection - again IMO 

i have 2 questions; 1)would you agree that this is what is likely happening and 2) which software of hyphy suite would be the most appropriate to demonstrate negative selection?

Thanks in advance

**Comment by spond** [comment]
Dear @sapuizait,

Gene elimination (as in they are removed from genomes) is a process that cannot be modeled well by standard phylogenetic models, where the main (only) process is substitution. 

When gene copies become psudogenized this would typically be interpreted as loss of functional constrains, or loss of purifying/negative selection. You can test for this with RELAX, but that means that homologous copies of genes are still detectable. 

For bacterial genomes I would also investigate assembly/sequencing issues, because gene annotation / detection, as well as ortholody determination is quite noisy.

Please let me know if this makes sense.

Best,
Sergei

**Comment by sapuizait** [comment]
Dear Sergei

Thanks a lot for your reply. I can see that i had a very utopian idea of how negative selection would manifest on these genomes... but i see your point.

A couple of follow-up questions:
- Testing with RELAX for relaxed negative selection; would you use all genomes that have the homologous genes (leaving simply out of the analysis the paralogs) or would you use only genomes that only have the homologous genes and no paralogs?
- Would you use the phylogeny of the target gene (the one that is to be checked for signatures of selection) as input for RELAX or would you use a phylogeny that uses some stable housekeeping genes (and therefore presents a more accurate topology).

You make an excellent point about the assembly/annotating issues, i am not too worried cause all genomes come from the same lab, sequenced with the same methods  and at the same run. But i will definitely check flanking genes and genomic areas to make a point that the losses is not an artifact.

Again, thanks for the help
P

**Comment by spond** [comment]
Dear @sapuizait,

1. Good question. The choice of sequences to include in these analyses is absolutely critical. My general advice is to explore various configurations, as there are pros and cons for including/excluding paralogs. I would probably include paralogs in the overall tree, but designate them as "nuisance" branches, i.e., selecting proper orthologs as test and reference.
2. Most of the time, I recommend using the gene tree; this will be especially true for bacteria both because species trees are much harder to define (compared to euks.) and because you expect quite a bit of HGT and other processes as a prior (at least *I* would).

Best,
Sergei

**Comment by sapuizait** [comment]
excellent - thank you!
