### ISSUE TITLE
Brew Cask install is extremely out of date

### ISSUE THREAD

**Issue by ethanagon** [veg/hyphy#1753]
Installing hyphy from brew cask put version 2.5.2 on my machine.

**Comment by stevenweaver** [comment]
Dear @ethanagon, 

Do you happen to know which `tap` you are pulling from? I don't think we've personally updated any `homebrew` formula since `homebrew/science` was deprecated about 6 years ago. It's quite possible (and welcome) that someone outside of our lab kindly created a cask, but if I'm directed to where it is I can have a look.

Best,
Steven

**Comment by spond** [comment]
Dear @stevenweaver,

Looks like the relevant formula is for `2.2.7` (current as of six years ago).

https://github.com/brewsci/homebrew-science/blob/master/Formula/hyphy.rb

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

Yes, but @ethanagon found version `2.5.2`, which I couldn't immediately find on Github. 

Best,
Steven

**Comment by ethanagon** [comment]
Hi Stephen,

This is @ethanagon (Ethan). I don't know which tap it came from, I did this
a while ago and just now realized it's way out of date.

**Comment by stevenweaver** [comment]
OK, PR is here -- https://github.com/brewsci/homebrew-bio/pull/1945

**Comment by stevenweaver** [comment]
PR was merged. Please follow the instructions on the homebrew-bio page -- https://github.com/brewsci/homebrew-bio/pull/1947
