### ISSUE TITLE
Estimating dN and dS, gene-wise

### ISSUE THREAD

**Issue by jergosh** [veg/hyphy#229]
I would like to obtain the values of dN and dS (separately) for an entire alignment (rather than site-wise).

This kind of analysis has been done using HyPhy in this paper: http://mbe.oxfordjournals.org/content/31/5/1228.short but no details are given. So I was wondering what would be the best way of obtaining 'global' dN and dS? As far as I can tell it could be achieved using the 'evolutionary fingerprinting' mode by looking at results for a single rate category but I'm not sure if this is entirely correct. Perhaps there is a more direct way?

**Comment by antben** [comment]
Hi Sergei,

I'm trying to use this script for my own data and it seems to be working fine except that it estimates both dN and dS as zero for whichever leaf or node is at the end of the input tree string. I ran it both on my own data and some example data and I get the same result regardless. Is this expected behavior? Should I be assuming that the last taxon in the tree is an outgroup?

Thanks,
Ben

**Comment by spond** [comment]
Hi Ben,

Probably a bug. I'll take a look tomorrow.

Sergei

**Comment by antben** [comment]
Hi Sergei,

Just checking to see if you've had a chance to look into this bug. Any idea what the problem might be?

Thanks for the help,
Ben
