### ISSUE TITLE
Impact of out groups on selection analysis

### ISSUE THREAD

**Issue by michael-steffen** [veg/hyphy#265]
I've been trying to find an answer to the impact of including out groups in selection analysis. Can anyone tell me what the impact is, and possible references? Do the impact vary between methods?

Thanks,
Mike

**Comment by spond** [comment]
Hi Mike,

It's difficult to make completely generalizable statements, but here is some intuition

1. If the number of outgrips is much smaller than the number of ingroups, the impact should be minimal, especially for methods which pool signal over branches (FUBAR, FEL)

2. If you have a method which allows for branch-level variation (MEME, BSREL, aBSREL), then you could see more sites/branches under selection because you've added more data. Ideally, the inference based only on the in-group subtree should not matter.

3. Rooting is irrelevant for nearly all of our methods (except DEPS), so the primary reason for adding outgroups (to root the tree) is not important here.

4. The two case syou may need outgroups is (a) when you want to test for selection on the **branch** leading to the TMRCA of the in-group sequences; (b) when you have non-reversible models (e.g. in DEPS)

Sergei
