### ISSUE TITLE
SLAC with dS = 1?

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#268]
Hi -
 I'm wondering if there is an option in HyPhy to run a SLAC analysis with dS fixed to 1? Haven't found anything yet, and it seems as though the code in QuickSelectionDetection.bf will always consider synonymous rate variation when the SLAC option is selected.
Thanks!
-Stephanie

**Comment by spond** [comment]
Hi Stephanie,

The nature of SLAC makes it difficult to "fix" dS, because the computation is inherently site-by-site. The closest I can think of is to replace site-level calculations of ES and OS (expected and observed synonymous counts/ratios) with something averaged over the entire alignment. 

Sergei
