### ISSUE TITLE
Query about unexpected significant results with REL

### ISSUE THREAD

**Issue by kiwijo2000** [veg/hyphy#276]
Hi!
I have a query about REL results: for some of my sequence alignments, I get significant REL results (with Bayes Factors ranging from 59 to 510) for four codons where there is no sequence variation across the entire alignment. Other methods (SLAC, FEL, FUBAR, MEME) do not return these codons as significant. Within the REL results page, if I click on the codons link in the "additional information" for these invariant codons, I get an error message that says "the image cannot be displayed because it contains errors". 

So my question is, should I ignore the results for these codons, or are these valid results due to the codon substitution modelling (selected model is F81) or some other reason? If it matters, I am using a user specified (maximum likelihood) tree, but seem to get the same results if I use the HyPhy NJ tree, and if I run the analysis with HKY85 three of the codons are still showing significant results.

I have just rerun the analyses, and the current job ID is upload.386465530229170.1, in case you want to have a look (codons 1-4 are where the issue lies).

Many thanks,
Jo Chapman

**Comment by spond** [comment]
Hi Jo,

These sites are shown as **negatively** selected by REL and are indeed invariant. One could argue that invariable sites are indeed under very strong selective constraints. SLAC, FEL, and MEME never consider invariant sites (which REL and FUBAR do), because there is no signal for them there. REL results in this instance are statistical artifacts due to the fact that they have to be slotted somewhere into the fitted 3x3 distribution; so you get the false significance. This is part of the reason we recommend that FUBAR (which is more robust to these types of errors) be used in place of REL.

Sergei

**Comment by kiwijo2000** [comment]
Hi Sergei
Thanks for your response. I realised that REL was showing these sites to be under purifying selection, but wasn't sure if I should trust that. The genes I am studying appear to mostly be under purifying selection, with a few sites under diversifying selection in some genes. I am creating tables showing results for SLAC, FEL, REL, MEME and FUBAR, to give an indication of overall support for selection acting on individual sites in the genes. Based on your answer, I think I will leave the invariant codons out of the tables, given it is a statistical artefact in REL.

Cheers,
Jo
