### ISSUE TITLE
Which model fit to use for ancestral sequence reconstruction (results post-processing) ???

### ISSUE THREAD

**Issue by ondrej77** [veg/hyphy#283]
Hello,
I wanted to ask for clarification regarding which model fit should be used for ancestral sequence reconstruction. To give a little background, I would like to 'replicate' datamonkey visualization of codons positively or negatively selected on the phylogenetic tree, displaying the ancestral codon sequences (using ggtree), for figures. 
After running FUBAR, MEME, etc. ... your software has the option to go to post-processing of the results to get the ancestral sequence. There, however, you provide options for which model fit to use - codon model, current nucleotide model, ... etc.. The ancestral sequences reconstructed by these different models vary, so my question is what models do you use for displaying results on Datamonkey? I suppose the 'curent nucleotide fit'? The post-processing menu after running FUBAR, MEME, aBSREL also offers different models for reconstructing ancestral sequence. Can you please clarify the process (which is used by specific program to find selected codons) or suggest which one to use?

Thanks, Ondrej

**Comment by spond** [comment]
Hi Ondrej,

There is no universally **best** method for ancestral state reconstruction. The biggest differences will be

1. Using codon or nucleotide models -- for coding data you should use the former.
2. Using site-wise or global models (e.g. MEME vs FUBAR), because site-wise models are free to scale the tree at each site.

I would probably go with fitting a **local** MG94xREV with CF3x4 frequency estimator (using `AnalyzeCodonData.bf` and the `MG94CUSTOMCF3X4` model).

Depending on what ggtree needs as input, it may be more convenient to modify the code in [https://github.com/veg/hyphy/blob/master/res/UserAddins/MapSubstitutions](this file) to write out annotated strings.

Sergei
