### ISSUE TITLE
REL mean dN/dS vs. SLAC mean dN/dS?

### ISSUE THREAD

**Issue by AndrzejN** [veg/hyphy#286]
I think I getting somewhere with my analysis. However I got contradicting results SLAC tell me that mean dN/dS for gene is about 0.5, but REL mean dN/dS is 1.1. I read your paper about SLAC,REL and FEL and I do understand difference between this algorithms but why so much difference?

I working on 10 gene sequences. Which results are more "real"? 

SLAC will not detect any positively selected sites at 0.1 significance level, REL will detect 3 positively selected sites. When I lower SLAC significance level to 0.3, positively selected sites will be as in REL with 0.1 (some sites will be different, between SLAC and REL).

It is really critical for me to detect "real" site with positive selection as much as possible.

Do you thing MEME would be best...

Thank you for help!

**Comment by spond** [comment]
Hi AndrzejN,

There is never anything **real** when it comes to statistical inference. It is frequently a question of what you prefer: accuracy or power. Because none of these tests are uniformly most powerful (a desirable property), you can't always prefer one to another. MEME and FUBAR are, for practical purposes a replacement for SLAC, FEL, and REL. 

Take a look at this, now rather old, but still relevant (PLoS Biology piece) [http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0040087] for a good review on the subject of **real** selection.

Sergei
