### ISSUE TITLE
Is it possible to estimate strong purifying selection?

### ISSUE THREAD

**Issue by TakashiKoyama** [veg/hyphy#287]
Dear Sir.

Hello. It might be silly question but please let me ask.
I want to identify genes under strong purifying selection from several hundreds of orthologous gene sets.
At first, I tried to use CodeML but finally I realized that it was impossible to statistically identify them. So I am now looking for other tools to do it such as hyphy but still not find.
Could anyone tell me if there is such module in hyphy or other packages?
Thank you for your kind helps.

Sincerely,
TK

**Comment by spond** [comment]
Hi Takashi,

Sure, you can test for negative selection. However, you can **assume** that nearly every gene in your collection will be under strong purifying selection along most of its length. This is the default evolutionary mode: conservation of function and many neutral or nearly neutral variants. If you seek specific sites under strong purifying selection, you could use our method FUBAR (available on www.datamonkey.org) to generate a list of sites where dS > dN in a statistically significant manner.

Sergei

**Comment by TakashiKoyama** [comment]
Dear Sergei

Thank you for your reply. It might be better to explain a bit more specific what I want to do.
I would like to identify a set of genes in which their functions are well conserved in a paticular phylogenetic group such as mammal but not necessarily conserved in others.
So, I would like to exclude genes under positive selection or relaxed purifying selection within that group. Model selection based on LRT does not support this. I think AIC or BIC might be solution.

I think the FUBAR is not suitable for my objective because the presence of sites under strong purifying selection does not directly indicate functional conservation of the protein itself. If my understanding is correct, could you tell me an alternative way to test strong purifying selection you suggested in your message?

Thank your for your kind helps.

Sincerely,
Takashi

2015/05/13 0:55$B!"(BSergei Pond <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by spond** [comment]
Hi Takashi,

You may want to take a look at RELAX (http://test.datamonkey.org/relax, http://mbe.oxfordjournals.org/content/32/3/820) for this purpose. This method can test one possible definition of selection relaxation, which sounds like may be useful to you. Essentially you could take a gene tree, define a group of branches that you think are conserved, and compare whether or not the *distribution* of dN/dS on those branches is further away from neutrality (dN=dS), than in the rest of the tree. The paper I reference above is a worthwhile read, because it also contains references to other dN/dS tests that people have applied in the past.

Sergei

**Comment by TakashiKoyama** [comment]
Dear Sergei

Thank you for your valuable advises!

Takashi
