### ISSUE TITLE
MG94xHKY85_3x4

### ISSUE THREAD

**Issue by htetre** [veg/hyphy#292]
Hello, 

I am fairly new to using HyPhy. I am checking dN/dS ratios for chloropast genes within a single genus. I have a concern with a gene that has no variation across the species but am getting a shared_DNDS of 1.12697645. I was under the impression if there is no variation I would get zero. 

Any help would be very appreciated
Thank you

**Comment by spond** [comment]
Hi there,

The value of dN/dS would depend on the model. For example, if there is no variation at all (even at the nucleotide level), then dN/dS is undefined. 

Could you please tell me 

1 Which analysis did you use to estimate the ratio?
2 Did you remember to choose the correct genetic code?
3 Would you mind pasting the console output of your analysis?


Sergei

**Comment by htetre** [comment]
I have been using the partition data set window, running the MG94xHKY85_3x4 Substitution model. The partition type is set to codon and the parameters have been both Rate Het. and/or Global. 

When I ran a model through the console I used the Basic Analyses> AnalyzeCodonData.bf. Below is the console output.  
____________READ THE FOLLOWING DATA______________
15 species:{AGR,ANG,ANN,ANO,CUS,DIV,HET,PRA,DEC,GIG,GRO,HIR,MAX,STRUM,TUB};
Total Sites:306;
Distinct Sites:4
Please enter a 6 character model designation (e.g:010010 defines HKY85):010010

______________RESULTS______________
Log Likelihood = -377.987280755511;
Shared Parameters:
R=1.126976459249358
AC=1.126976459249358
AT=AC=1.126976459249358
CG=AC=1.126976459249358
CT=1=1
GT=AC=1.126976459249358

Thanks for your help!

**Comment by spond** [comment]
Hi there,

Looks like your alignment has no variation at all (4 site patterns), and all the parameters have the same 1.12 values. This is because when there is no variation, none of those are identifiable: setting them to any valid value will not change the likelihood. And that happens because they are all multiplied by branch lengths at some point. If branch lengths are 0, then the product is always 0. 

In this pathological case, the point estimates reported are meaningless. I will make a note to put some code that checks for this condition and warns the user.

Sergei.

**Comment by MunibaFaiza** [comment]
Hi,

I am trying to analyze codon data using AnalyzeCodonData.bf with MG94CUSTOM as the substitution model. But it asks for a tree file, I tried to input ML tree on the sequences in Newick format, it gave an error.
What kind of tree file do I have to input?

Thanks
