### ISSUE TITLE
How valid are branch-site results when target gene is an outgroup

### ISSUE THREAD

**Issue by ritututeja** [veg/hyphy#305]
Dear HYPHY users,

I wanted to know how valid are the branch site results when target gene itself seems to be an outgroup? For info, I tested around 100 genes and though my species of interest is not an outgroup but for few gene families the target gene is an outgroup and the branch site results shows these gene under positive selection. Wondering how valid my analysis is? Can anyone help with this?

Thanks,
Reetu

**Comment by spond** [comment]
Hi Reetu,

For branch site analyses, all branches are equally valid results of selection. There is no particular heed given to whether or not the branch is an outgroup. That said, because outgroup branches tend to be long, and encompass a lot of evolutionary time relative to the in-group (by definition), one would expect that such branches will light up like a Xmas tree when you scan for selection. 

aBSREL and BUSTED, our two current branch-site methods, both gain power over longer branches, until they become too long and saturate.

Thus, there is no statistical concern here, just one of relevance: you can ignore selection on outgroup branches if this is not what you are interested in.

Sergei
