### ISSUE TITLE
aBSREL and MEME on non-single copy orthologs

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#306]
Dear all,

This is more a theoretical question rather than a practical one. Giving a ortholog group/family (OG) from a bunch of related species, where all Othologs + In-Paralogs are present, together with the phylogenetic trees of the OG. There's any caveat or worst any deviation from statistical assumptions, regarding those methodologies?

I hope I explained myself clear...
best,
F

**Comment by spond** [comment]
Hi Francesco,

Nothing in particular I would be worried about, other than gene conversion (recombination), which can bias **all** phylogenetic methods. 

You could expect paralogs and orthologs to experience different selective pressures, but aBSREL and MEME are specifically designed to handle this, so you should be OK.

Sergei

**Comment by francicco** [comment]
So shell I go straight forward? aBSREL, ModelSelection and MEME?
Thanks a lot!
F

**Comment by spond** [comment]
Hi Francesco,

Yes. Skip ModelSelection, MEME and aBSREL (most recent version) assume GTR for the nucleotide component. Screen your data with GARD to check for recombination. 

Sergei

**Comment by francicco** [comment]
GARD for the whole multiple species alignment or just for the inparalogs?
F

**Comment by spond** [comment]
Hi Francesco,

Probably just the paralogs (if you are trying to catch gene conversion).

Sergei

**Comment by francicco** [comment]
It's going to be tricky since I have hundreds of orthologous groups.
Do you think a ML phylogeny of the og must be preferred to the easier UPGMA clustring, in order to confirm the right species phylogeny?

F

**Comment by spond** [comment]
Hi Francesco,

UPGMA is always a bad choice. Just run FastTree on your data, it won't take much time. I won't even attempt to guide you on gene/species tree phylogenies -- there is a lot of literature on it out there. For the purposes of this analysis (selection), you should stick with the gene tree.

Sergei

**Comment by francicco** [comment]
The gene tree even if does not reflect the species phylogeny?

**Comment by spond** [comment]
Hi Francesco,

Especially if it doesn't reflect the species phylogeny.

Sergei

**Comment by francicco** [comment]
Ok! I'm totally confused now!!! So, what about incomplete lineage sorting for instance? So, just grab orthologs with or without inparalogs, align them, search gene tree ...

I think I'm missing something...
F

**Comment by spond** [comment]
Hi Francesco,

Like I said, I can't give you meaningful guidance about gene/species tree for your specific problem. Incomplete lineage sorting is a minor problem (as it will only affect short branches, where there is no real selection signal). If you have gene trees which are significantly different from species trees, then you are running the risk of getting incorrect selection results if you force a species tree onto a gene tree. 

For MEME, where you care about sites, it is a no brainer to use a gene specific tree (it is really just a nuisance parameter). For aBSREL the question is trickier, because you want branches to be meaningful and comparable from tree to tree. I would use one of the many tools that is out there for finding evidence of species-gene incongruence as a first step here.

Sergei

**Comment by francicco** [comment]
Ok, I understand the problem. The issue is less straight forward then I was thinking. It's a work I didn't want to do a lot in vain.
Thank a lot for your clarification.

F

**Comment by francicco** [comment]
Hi Sergei,

sorry if I bother you again. I was thinking to do two parallel analysis, one on single-copy og and another on og+inparalogs to check, as you suggested, for convergence evolution. Do you have any paper to suggest me?

Thank you a lot

**Comment by spond** [comment]
Hi Francesco,

You can look at a relatively old paper from my collaborator, Topher Woelk, if you want to use our tools: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2174272/

Sergei
