### ISSUE TITLE
 which test to run to identify negative selection in only select taxa?

### ISSUE THREAD

**Issue by jwconnolly** [veg/hyphy#327]
I would like to identify the codons that are causing only one clade in my phylogeny (all hsp70 genes) to have much shorter branch lengths that the rest of the taxa, is there a way to do this in hyphy? I ran SLAC but every codon was listed as undergoing negative selection (because these genes are already under purifying selection) how can I differentiate the codons in the clade I am interested vs. everything else?

**Comment by spond** [comment]
Hi jwconnoly,

Have you considered running [RELAX](http://test.datamonkey.org/relax), which we published in [MBE](http://mbe.oxfordjournals.org/content/32/3/820) this year? This will give you a gene wide overview of selection intensification and relaxation, before you start looking at specific codons.

Also note that shorter branches are most likely due to strict conservation: a codon that is perfectly conserved will not be marked as negatively selected by SLAC (or other dN/dS methods), because it defines negative selection as an excess of synonymous substitutions, i.e. you need to have **some** variation. 

If you run FEL (following the steps described [in section 2.6.4 here](http://hyphy.org/pubs/hyphybook2007.pdf), for example), you can choose which branches will be tested for selection: if you have a monophyletic clade, then just choose the option to test a subtree and specify where the root of the subtree is.

Sergei

**Comment by jwconnolly** [comment]
Thanks sergei I ran relax (http://test.datamonkey.org/relax/55f0dd2afb1fe55716de06eb)... if im reading the output correctly is it saying that the branch I selected as the foreground has a significantly lower dn/ds (9.19*10^-9) than the rest of the tree (.00855)?

**Comment by spond** [comment]
Hi jwconnolly,

RELAX tests the entire distributions of &omega;, not just a single value, and measures if one distribution is more *extreme* (further away from neutrality, or 1), than the other. In your case the "test" (selected) branch has a more extreme distribution of &omega; (smaller values are closer to 0, and larger values are further away from 1 compared to the rest of the tree), i.e. selection is intensified, but the result is not statistically significant (p = 0.0857). Try selecting multiple branches as the test set, as the statistical power afforded by a single branch is relatively low.

Best,
Sergei

**Comment by jwconnolly** [comment]
Thanks, I will try testing more branches!

**Comment by jwconnolly** [comment]
hello spond, could you help me analyze the results of my rerun test? I want to make sure im drawing the correct conclusions from this analysis: http://test.datamonkey.org/relax/55f5a7cdfb1fe55716de0bbb#

**Comment by spond** [comment]
Hi @ jwconnolly,

Sure thing. You have selected 5 branches as your test set (see thick branches in the attached, also the tree tab of the results page. Relative to the rest of the tree, there is **relaxed* selection (both purifying and diversifying components are relaxed) operating on this set of branches (see the ω distributions under the Alternative model plot), i.e. all of the &omega; values are closer to 1. This result is statistically significant (p = 0.006). 

Sergei

![screen shot 2015-09-14 at 1 22 24 pm](https://cloud.githubusercontent.com/assets/1018513/9860918/cf31b8bc-5ae3-11e5-9e38-3d0b14df40c3.png)

**Comment by jwconnolly** [comment]
Thanks! these are opposite of what I was expecting
