### ISSUE TITLE
MEME results interpretation  

### ISSUE THREAD

**Issue by jwconnolly** [veg/hyphy#341]
Hi all, 
I ran MEME on 70 hsp70 sequences and want to make sure I understand the results. The test found 17 sites with evidence of diversifying selection at p=.05. What I do not understand are the β+ and β- values, I looked at the MEME paper but can't seem to figure this out. 
Also is there a way to infer what type of selection the site is usually undergoing versus what MEME identified? For example can one say "86% of the time site x is constrained but 14% it is undergoing positive selection." If someone could take a look it would be much appreciated.

http://www.datamonkey.org/cgi-bin/datamonkey/slacpvalue.pl?file=upload.37483454943897.1&pvalue=0.05&task=12

thanks, Joe

**Comment by spond** [comment]
Hi Joe,

Using the following screen shot as a guide...

![screen shot 2015-09-30 at 1 20 17 pm](https://cloud.githubusercontent.com/assets/1018513/10205424/04237bac-6776-11e5-9968-734e9a93ec8c.png)

At site 9, for instance, MEME has estimated the distribution of &alpha; (synonymous rate) and &beta;<sup>-<sup> (constrained to be &leq; &alpha;), and &beta;<sup>+<sup> (unconstrained) to have the following two bins

1. [Purifying or neutral]: &alpha; = 0.242413, &beta;<sup>-<sup> = 0.072039 (i.e. &omega; = 0.297) and weight of 0.883392

2. [Unconstrained, i.e. diversifying in this case, because of significant p-value]: &alpha; = 0.242413, &beta;<sup>+<sup> = 14.2679	0.116608	0.00861727	1	[ (i.e. &omega; = 58.9) and weight of 0.116608

You **could** describe this site as 

"Site 9 was inferred to be under purifying selection (&omega; = 0.3) 88.3% of the time, and under  diversifying selection (&omega; = 59), 11.7% of the time"

There is a little conflation of terms (mixture proportions are not exactly proportions of time, but it's more intuitive that way).

Sergei

**Comment by jwconnolly** [comment]
Thanks much!
