### ISSUE TITLE
BGM on amino acid alignments

### ISSUE THREAD

**Issue by lyy005** [veg/hyphy#367]
Hi there
I'm trying to use BGM on amino acid alignments. I followed the issue #303, however, after running MapAAMutationsToTree.bf my the binary output has uneven length as I got the error "Error:
Rows of unequal lengths in matrix definition". I checked the LIST option by printing the output on the screen and it looks right. Would you give me any advice on this? 

Thank you

YY

**Comment by ArtPoon** [comment]
Are you able to provide a small test sample of your data for reproducing your problem?

**Comment by lyy005** [comment]
Sure. It looks like this:
[tree.txt](https://github.com/veg/hyphy/files/60812/tree.txt)
[seq.txt](https://github.com/veg/hyphy/files/60811/seq.txt)

YY

**Comment by ArtPoon** [comment]
The root of the problem was how my script was handling gaps in the observed amino acid sequences.  There were several issues that I have patched in the updated `MapMutationsToTree.bf` gist that you should grab [here](https://gist.github.com/ArtPoon/1838da20c383e540076c).  (This sort of thing is why I posted those gists to #303 with the caveat that it is untested code - the same still holds true here, sorry!)

You should also remove columns with low numbers of substitutions, like with the following bit of `R`:
```
test <- read.csv('~/Desktop/yy/test.csv', header=F)
test2 <- test[,which(apply(test, 2, sum)> 10)]  # after having a look at the column summaries
write.csv(test2, file='~/Desktop/yy/reduced.csv', quote=F, row.names=F)
```

Running the bgm script on `reduced.csv` gave me the following (note that I've futzed around a bit with the DOT file):
![bgm dot](https://cloud.githubusercontent.com/assets/1109328/11774387/71176f72-a1e9-11e5-92c4-d5202f688372.png)

**Comment by ArtPoon** [comment]
By the way, the LIST output helped diagnose the problem -- there were stretches of consecutive amino acid positions corresponding to sequences with incomplete coverage, which were being reported as substitutions to `A`s on terminal branches.

**Comment by lyy005** [comment]
Hi Dr Poon
It works with no error output! Thank you so much. But I'm having a hard time understanding the messages.log file. What's the best way to get the co-evolving sites from this file? The format is quite different from the result from the SpiderMonkey website. 

YY

**Comment by ArtPoon** [comment]
The key files that you will want to work with are:
* `edgelist.out` - a CSV file containing the marginal posterior probabilities (MPPs) for every possible edge in the network.  The MPP of an edge from `i` to `j` is simply the proportion of graphs sampled from the posterior distribution that contain this edge.  (This isn't exactly true - since the batch file ran [order-MCMC](http://link.springer.com/article/10.1023/A:1020249912095), we are sampling node hierarchy permutations from a different posterior distribution - but it is close enough.)
* `bgm.dot` - a [Graphviz DOT file](http://www.graphviz.org/content/dot-language) that generates a graph layout of "significant" edges from the analysis.

One way to get co-evolving sites from the output files would be to load `edgelist.out` into *R* and filter accordingly.
