### ISSUE TITLE
fixing branch lengths in BUSTED

### ISSUE THREAD

**Issue by idavydov** [veg/hyphy#387]
Hi,
Is it possible to fix branch lengths in BUSTED.bf?
Also is there way to do this in MEME and other models?
There are some posts on this in the forum, but some contents is missing from the forum posts when you're not register, and the registration is closed.
Thanks!
Iakov

**Comment by spond** [comment]
Hi @idavydov,

It is possible, but I would't recommend it. The only benefit I see to fixing branch length is to reduce computational cost (fractionally). The major drawbacks are that 

1. Branch-site REL models (of which both BUSTED and MEME are examples) tend to produce somewhat different branch length estimates that do simpler models, and these changes tend to be large and important (see http://www.ncbi.nlm.nih.gov/pubmed/21705379)

2. Fixing branch lengths imposed some non-trivial constraints on dN/dS model components; I have no idea what this does to method performance.

That said, what CAN be done relatively easily (it already IS done for MEME), is to constrain relative branch lengths, i.e. if branch 1 is 2x longer than branch 2 in the input tree, then this relationship will be enforced.

May I ask why you are interested in implementing this constraint? I am sure there exists interesting scenarios that I haven't considered where this may be important, which is why I ask.

Cheers,
Sergei

**Comment by idavydov** [comment]
Dear Sergei,
Thank you much for your response.
Since I'm doing some simulations, I know the true branch lengths. So I suppose fixing them (or at least relative branch lengths) will improve the computational performance of the model by reducing the number of parameters.
Thanks,
Iakov

**Comment by spond** [comment]
Hi @idavydov,

OK, that makes sense. However, an important point to consider is this: did you simulate under the BUSTED model, or under a different model? If the latter, then fixing branch lengths in BUSTED could still lead to undesirable statistical artifacts.

Sergei

**Comment by idavydov** [comment]
Dear Sergei,
Thanks a lot for the clarifications. No, the model is more general.
I was considering this point, and I guess you're right. After all for my analysis it would be better to use BUSTED with the branch-length estimation.
Thanks a lot,
Iakov
