### ISSUE TITLE
Positive selection and relaxed purifying (negative) selection

### ISSUE THREAD

**Issue by francicco** [veg/hyphy#432]
Hi everyone,

I just got back a paper on genome-wise scan of positive selection rejected. One of the comment was the following:

- One of the problems of PAML is that signatures of positive selection might in fact be relaxed negative selection. Can this be the case in the present study? Please study further this possibility.

How may I reply to this criticism...

Thank you
F

**Comment by spond** [comment]
Dear @francicco,

I am not sure exactly what the comment is about: is it about PAML specifically, or codon-based &omega; methods in general?

If you are looking at gene-level selection, the best methods we have are BUSTED and RELAX, both available at test.datamonkey.org.

[BUSTED](http://www.ncbi.nlm.nih.gov/pubmed/25701167) will test for evidence of positive selection on the gene when &omega; varies across sites and branches. 

[RELAX](http://www.ncbi.nlm.nih.gov/pubmed/25540451) will allow you to directly test for relaxed negative selection, but only **relative** to another part of the tree.

Sergei

**Comment by francicco** [comment]
Dear Sergei,

I think I was not very clear. What I did in the paper was using aBSREL method to search for signature of positive diversifying selection of 2000 single-copy orthologous families on 25 species. One of the referee asks if the method I used can deal with false positive signatures of positive selection when in fact it is a relaxed negative selection.

From what I understood, but I may wrong, is that as you stated in your paper (Kosakovsky Pond et al. 2011 MBE) “In this manuscript, we present one case where they falsely identify positive selection on a neutrally evolving lineage (Type I or false positive error)". So apparently aBSREL should not have this Type I error. Is that right?

Thank you
F

**Comment by spond** [comment]
Dear @francicco,

**No** method that I know of can avoid false positives (due to relaxed selection or otherwise). aBSREL is able to deal with **some** types of false positives (due to the relative model inflexibility in PAML branch site tools). It also sounds like you should use BUSTED -- if you don't care **exactly** where selection took place, BUSTED will have more power than aBSREL, because aBSREL derives its signal from a single branch, whereas BUSTED pools signal from many branches. 

In dealing with this specific criticism, my suggestion would be to acknowledge that false positives are inevitable (with any statistical tests), and all you can do is due diligence to use the the best currently available method for the job.

1. BUSTED (or aBSREL) will control for false positive rates on the test that some sites/branches have &omega; > 1.

2. BUSTED (or aBSREL) will **not** however make any claims that &omega; > 1 is definitely due to positive selection, and not some other process. No other method based on sequences alone can make that claim either, so it's unavoidable. If, however, one agrees that relaxed selection implies that &omega; ~ 1, then BUSTED and aBSREL will not have elevated positive rates.

Sergei

**Comment by francicco** [comment]
Dear @spond,

"No method that I know of can avoid false positives" that is something I should tell to the referees. Thank you a lot for your explanation. Next time I'll use BUSTED (I guess there is a HyPhy script somewhere in the packadge) for next project, for what I could understand it, BUSTED is an extension of aBSREL, they should behave similarly right? Because I did all the analyses with it, I'd like not to throw everything in the trash bin.

Is there a way, some kind of plot I can generate to convince referees I'm not overfitting the data?

Thanks a lot, really helpful!
best
F
