### ISSUE TITLE
The importance of tree topology on selection analyses

### ISSUE THREAD

**Issue by kiwijo2000** [veg/hyphy#438]
I have performed a number of codon-based selection analyses (FEL, REL, SLAC, FUBAR and MEME via DataMonkey) on my datasets (15 datasets comprising between 8 and 105 unique sequences). My sequences are short (~120 bp) and comprise single genes (the coding portion of beta-defensin genes). In my input datafile, I always include a ML user tree, but have not partitioned the data further. I then use the integrative selection analysis function to infer evidence for selection on my genes.

I have had a comment from a reviewer in my resulting manuscript, which states "For the detection of positive selection, the authors to my understanding used a single topology. I would suggest that the authors use additional topologies, which can for instance be randomly sampled from the Bayesian posterior distribution, in order to exclude an effect of topology on the inference of sites under selection". I am wondering if this is indeed necessary? How much effect does tree topology have on the inference of selection using the above methods? 

In the "Not So Different After All: A Comparison of Methods for Detecting Amino Acid Sites Under Selection" paper, it is stated that "for small data sets, it may be advisable to run a sampling-based approach in order to assess how uncertainty in reconstructions affects the results". Does this subsampling refer to subsampling of trees? And if so, is there a general guideline for how many sequences constitute a "small" dataset? i.e. can I just be concerned about repeating the selection analyses with subsampled trees on those datasets with less then, say, 20 sequences?

For reference, 12 of the datasets show purifying selection and the other 3 show balancing selection. A friend wrote me an R code to randomly sub-sample Bayesian trees, but having to repeat all the analyses multiple times under different tree topologies would be very annoying indeed! 

Additionally, I am thinking that perhaps, instead of running all five analyses (SLAC; FEL; REL; MEME; FUBAR) on every dataset, I should tailor the analyses depending on the number of sequences (e.g. SLAC when I have over 40 sequences, FEL for 20-40 and REL for less). If so, is it OK to continue to continue to use FUBAR and MEME as well, or do they also have limitations on dataset size? Or do you feel it is best to run all five analyses on each dataset and report the integrative results to show the overall strength of support for selection acting on each codon?

Any thoughts would be very much appreciated!

**Comment by spond** [comment]
Dar @kiwijo2000,

Apologies for not responding to your post earlier. 

> How much effect does tree topology have on the inference of selection using the above methods?

Numerous simulation studies (by us and others) have found that anything less that gross errors in topological reconstruction have very little effect on method power/accuracy. For example, in MEME papers we have reconstructed trees using a very crude NJ method on simulated data, and found that using NJ vs true tree had a very minor effect. You **could** easily run faster methods (like FUBAR) on many trees, but 

1. I don't expect you will find much effect
2. The trees generated by Bayesian models are themselves predicated on (wrong) substitution models used to compute likelihood, e.g., even when Bayesian packages use codon models, they are typically something like GY94 with no rate variation. 

My personal advice is to do what the reviewer asks because it's easy, and will not affect your results.

> Does this subsampling refer to subsampling of trees?

No, it refers to assessing the sensitivity of SLAC to ancestral state reconstruction. If you use likelihood based methods (FUBAR, MEME, etc.) this error is irrelevant (because one computes a weighted sum over all possible ancestral state reconstructions)

> Additionally, I am thinking that perhaps, instead of running all five analyses ...

I would use only FUBAR (pervasive diversifying selection) and MEME (episodic diversifying selection).

FUBAR supersedes REL (always) and FEL (essentially always) and SLAC (always)
MEME does a different test that the other 4, because it allows selection to vary from branch to branch **and** site to site (instead of only from site to site)

Sergei
