### ISSUE TITLE
qvalue in QuickSelectionDetection.bf gives wrong values

### ISSUE THREAD

**Issue by idavydov** [veg/hyphy#440]
It seems that q-values produced by QuickSelectionDetection.bf are incorrect (a lot of zeros). This was already mentioned [on forums](http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1390912207) in 2014.
1. I'm not sure if there are plans to work on this. But I though it's good to mention the issue, this way you'll have it on your bug tracker.
2. As far as I understand, there's a link to some justification of not using q-value with MEME. But the link is not visible for non-registered users, and registration is closed. Is there a way to see the hidden link?
Thanks a lot,
Iakov

**Comment by spond** [comment]
Dear @idavydov,

Apologies for not responding sooner. We are working on re-engineering all the standard selection analyses and this issue will be fixed. 

As far as 2 goes, the basic justification is that in real data there will be almost no sites with the strict null (neutral evolution), hence the test is already conservative, and q-values (which assume that you can estimate rejection regions from the distribution of "null" p-values in the test set) will also be too conservative. 

If you reject the null at p = 0.05 then you are accepting 5% of false positives under the strict null (every site is undergoing neutral evolution), but in reality your false positives will be much lower because, for example, most sites are conserved (dN < dS) etc.

Sergei

**Comment by idavydov** [comment]
Thank a lot for your reply.
As far as I understand the problem, the fact that the test is too conservative, will affect the null-model p-value distribution. Depending on the effect, it might be possible to use more advanced pi0 estimators. We had a similar problem with branch-site test by Yang, and I think we found a nice and rather simple practical solution at least for that test. On the first impression, something similar could be used for MEME.
FDR has a lot of advantages compared to the p-value threshold.
