### ISSUE TITLE
basic questions about using MEME

### ISSUE THREAD

**Issue by jullee** [veg/hyphy#441]
Hi
I'm new to HyPhy and testing selection on phylogenies in general. I've followed several tutorials now and read Murrell et al. 2012 but still have some questions about using the software. Hoping this is the right place to get some answers to the following:

1) I am running tests of selection on different plastid genes subset from a whole-genome alignment. I have phylogeny based on the entire plastid. Is it appropriate when testing for selection on a single gene to use the whole-genome topology but use a substitution model (from modeltest) specific to the gene? 

2) For the tree input file, does MEME use the branch lengths? So far I have input the topology without branch lengths as per one of the tutorial examples. However, when setting up a run (using the Desktop application) I see that I can estimate dN/dS from data with branch corrections...Is this recommended over estimating without branch corrections? (not sure where to find out how these different options influence the analysis)?

3) Why is the default p value for the LRT 0.1? Is this because MEME is a conservative test? When should this be changed?

4) Regarding the output:  from what I understand B1 is B- . Is B2 = B+  from the MEME paper? Is the LRT is testing a model where B1<alpha for all sites versus one where some sites are allowed to have B1>alpha (unrestricted)? And am I correct that I interpret B- and the associated proportion as number of branches supporting negative selection at the site and B+ and the associated proportion as number of branches supporting positive selection? I found this section confusing.

Thanks in advance for the help and for your patience with a newbie!

**Comment by spond** [comment]
Hi @jullee,

1. A two part answer.
      * I would always use GTR for testing in MEME (it should not make much of a difference, but save you some work). The reason for it that ModelTest was mostly designed to make sure you don't use models that are too simple (e.g. F81), because that can cause known biases. 15-20 years ago it was noticeably more difficult to fit more complex models during tree search (due to slower computers), but in modern times you can pretty much stick with GTR by default. 
      * See #354 and #306 for some discussion on gene/species tree 
2. MEME will only use branch lengths supplied with the tree as initial guesses; branch lengths will always be optimized internally by MEME. Good initial guesses will make the analysis run a bit faster, that's all
3. Short answer: yes MEME is a conservative test (because the strict null of dN = dS is rarely found in real data). See #188 for a more detailed discussion. p-values and test cutoffs are always subjective (power vs accuracy).
4. &beta;<sub>2</sub> is indeed  &beta;<sup>+</sup>. The LRT test is for unrestricted  &beta;<sub>2</sub> (alternative), vs  &beta;<sub>2</sub> &le; &alpha; (null).  &beta;<sub>1</sub> is always restricted to be &le; &alpha;. You can loosely interpret the proportion of branches in the &beta;<sub>1</sub> category as those that are subject to negative selection (or more precisely, negative or neutral), but there is no formal test of this. For example you can find sites where &beta;<sub>2</sub> is also &le; &alpha; which means that 100% of branches are under neutral/negative selection.

HTH,
Sergei

**Comment by jullee** [comment]
Hi Sergei,

Thanks for the answers. I've finished running MEME for a couple of the genes that I'm interested in using the desktop version of HyPhy on my mac and following your suggestions about the GTR model (so far only using the topology from all genes combined rather than single genes as these are all chloroplast genes). The likelihood ratio file that is produced has a lot of zeros and 1s. 

For example here is the first few rows from the output file for one of the genes:

beta1,beta2,weight1,weight2,Length_scaler,LRT,p-value,q-value,Full Log(L)
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0
0,0,0,1,0,0,1,0,0

Is this to be expected when the alignment has many invariant sites or is this output indicating a problem with my execution of the program? 

Alternatively, ’m wondering if any of the following could be affecting the results:

1) How much is the analysis affected by a distance outgroup when the ingroup consists of closely related taxa? Should I be removing the outgroup? (the tree is rooted by the outgroup)

2) I think I read somewhere that the analysis works better between species rather than within species: does this mean that there is a minimum amount of variation before it is appropriate to run MEME? 

3) The phylogeny includes multiple individual from each of our species and the sampling may not be even across species. Should we reduce the dataset to one individual per species?

Thanks again for your help!

**Comment by spond** [comment]
Dear @jullee,

1). The `0,0,0,1,0,0,1,0,0` outputs you see are expected; because the maximum likelihood estimate for invariable sites is to have a Length scaler of 0 (and the likelihood of 1), these are output without any optimization for invariable sites, as a time saver.

2). While MEME gains power with more sequences/greater divergence, there is no _hard and fast_ lower bound. The between/within species distinction is more subtle: dN/dS is harder to interpret in the _within-species_ case, because, depending on the population structure and time-scales, some or many of the non-synonymous variants may be mutations and not substitutions. In other words, they are not necessarily fixed. One way to get around it is to test for selection on internal branches only (see http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020062 for example).

3. That should not be necessary, unless you care to distinguish among within-species selection (but also see point 2), and betweens-species selection.

Cheers,
Sergei

**Comment by jullee** [comment]
Thanks Sergei! Those answers help a lot!
