### ISSUE TITLE
Error using RELAX

### ISSUE THREAD

**Issue by skneitz** [veg/hyphy#445]
Hi All,

I am new to hyphy / relax and I have a very basic problem with correctly running an analysis. I want to use RELAX to detect relaxed selection in a set of 11 taxa. I have the alignments (fasta format) and trees (appended to my fasta in Newick format). When I try to run RELAX via GUI it seems to read my alignment file correctly, but somehow there are problems with the tree (I just tested using 4 taxa):

[RELAX] Loaded an MSA with 4 sequences and 450 codons from '/testalignment.fas'
A tree was found in the data file:
((({A},B),C),D)
Would you like to use it:(Y/N)?y
y
[RELAX] Selected 1 branches as the test set: Node3
[RELAX] Obtaining branch lengths under the GTR model
Error:
estimators.fitGTR.gtr_pi must refer to a column/row vector in the call to Model = ...

did I miss something in the input?

Thanks a lot for any comment,

Suzanne

**Comment by stevenweaver** [comment]
Hello Suzanne, 
Apologies for the delay due to the holiday weekend.

It looks as though your newick tree may need to be adjusted a bit in order to work with RELAX.

1) It looks as though you have curly braces for label A when you meant to use parentheses. 
`((({A},B),C),D)` should be `((((A),B),C),D)`.

2) You will want to label the branches you want to test using curly braces, for example:
`((((A{TEST}),B),C),D)`

Best,
Steven
