### ISSUE TITLE
setting PATHS correctly

### ISSUE THREAD

**Issue by halasadi** [veg/hyphy#467]
I am trying to run the BUSTED analysis (using the most current version). There were a few errors with paths but I have seemed to fixed them (e.g. some scripts call for Grabbag but Grabbag.bf is only available). However, I can't seem to get over this error:

```
Error:
Could not read command file in ExecuteAFile.
Original path: '/usr/local/lib/hyphy/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'.
Expanded path: '/usr/local/lib/hyphy/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'

Function call stack
1 : ExecuteAFile from file HYPHY_LIB_DIRECTORY+"TemplateBatchFiles"+DIRECTORY_SEPARATOR+"TemplateModels"+DIRECTORY_SEPARATOR+"chooseGeneticCode.def" using basepath /mnt/gluster/home/halasadi/markov/bin/hyphy/res/TemplateBatchFiles/lib2014/.
-------
2 : data_info=io.readCodonDataSet(dataset_name)
-------
3 : codon_data_info=utility.promptForGeneticCodeAndAlignment("codon_data","codon_filter")
-------
Segmentation fault

```

I don't know where it's getting  ```/usr/local/lib/hyphy```. Any suggestions to move forward?

**Comment by spond** [comment]
Dear @halasadi,

The `/usr/local/lib/hyphy` path is is the default path which you can override by supplying the `LIBPATH` command line argument like

```
$/path/to/HYPHYMP LIBPATH=/path/to/hyphy/lib
```

The `lib` directory is assumed to contain `TemplateBatchFiles` etc.

Regarding missing extensions, you should be fine, because calls like

```
LoadFunctionLibrary ("GrabBag");
```

will automatically try several standard extensions to resolve the path.

Sergei

**Comment by halasadi** [comment]
That worked. Thanks @spond!
