### ISSUE TITLE
BUSTED for detection of positive selection in single site 

### ISSUE THREAD

**Issue by Oferaidlinharari** [veg/hyphy#472]
Dear developers,

first i want to thank you for the opportunity to use the datamonkey server, it is so very useful for my research.

I'm using different tools from the package to for detection of positive selection in single site including MEME, i understood from your paper about the BUSTED tool that it can be used also to detect single sites under pos. sel. but i couldn't figure out how to do it.

Can you please help me and give instruction how can i infer a positive selection in single site in  P<0.05 given the output in the csv table.
 thanks a lot
Ofer

**Comment by spond** [comment]
Dear @Oferaidlinharari,

Unlike MEME, BUSTED does not provide a rigorous statistical test for finding individual sites under selection. BUSTED, instead, offers an *ad hoc* exploratory test to flag sites that prefer being able to allocate some of their evolutionary history to &omega; > 1.

The most direct comparison between MEME and BUSTED (again, this could only be advised for data exploration, and since you already ran MEME, I would just recommend that you base your inference on p-values reported by MEME), would be to compute take log evidence ratios reported by BUSTED, multiply them by two, and compare them to critical values of the &chi;<sup>2</sup> distribution to derive cutoffs. E.g. you might use 3.85 for p = 0.05, i.e. if 2*log (evidence ratio) > 3.85, you might call that site selected.

Best,
Sergei

**Comment by Oferaidlinharari** [comment]
Dear @spond,

Thanks alot, indeed u want to report the BUSTED result just to support the claim that a residue is positivly selected as detected by MEME.

Just to be sure, what value should i use to multuply and check against χ2 ? the "er_constrained" or "er_optimized_null"? or both? 

Thanks!
Ofer

**Comment by Oferaidlinharari** [comment]
Dear @spond,

if understood you correctly i should take the value of "er_constrained" as reported for the single codon in the csv output file and multiply it by 2, then assign to the χ2 distribution, e.i. if this value is higher then 3.85 i could infer this codon as a possibly positivly selected one. am i write?

can i make this procedure if the branch-site overaal test of BUSTED is giving a "no evidence of episodic diversifying selection"?

Thanks again
Best
Ofer

**Comment by spond** [comment]
Dear @Oferaidlinharari,

Yes, what you write in paragraph one is a possible procedure. However, considering that the **overall** test found no evidence of positive selection, you are even on shakier ground in term of interpretation. That's because you will be using an _ad hoc_ procedure to find outliers conditioned on the a model that's not supported by the data.

An analogy would be this. Having done a linear and non-linear (say quadratic) regression on some data points, you found that the data are well explained by a linear model, i.e., there is no evidence to reject it in favor of the quadratic regression. Conditioned on that, you would then proceed to look for outliers  (in a loose sense of the word), whose residuals are much lower in the quadratic fit than they are in the linear fit. That doesn't make much sense to me.

Sergei
