### ISSUE TITLE
rooted tree

### ISSUE THREAD

**Issue by nahidshokri** [veg/hyphy#480]
Hi Sergie, 

I am going to use TestBranchdnds.bf on CO2 gene sequences of four bees. As soon as I imported tree into Hyphy, the tree becomes unrooted so that one of the internal nodes got inactive while that node is very critical to estimate dNdS to the rest of tree. As I don't have any closed outgroup to my bees and using Honey bee(which has CO2 sequence )  will have effect on the output, I was wondering if there is any solution available to force hyphy to use rooted tree (with both internal nodes and four external branches active for analyses)?

Thanks in advance
Nahid

**Comment by nahidshokri** [comment]
Following my previous email, I was wondering how I can force Hyphy to use rooted tree in these batch files(Nucmodelcompare.bf. CodonModelcompare.bf, SelectionLRT.bf,Quick selectiondetection.bf)?

Thanks
Nahid

**Comment by spond** [comment]
Dear @nahidshokri,

You can add 

```ACCEPT_ROOTED_TREES = 1;```  

to the top of a batch file to force HyPhy to accept rooted trees. That said, all the analyses you have mentioned use **time-reversible** substitution models, meaning that there will be no difference it results whether or not you use rooted or unrooted trees. Using rooted trees is likely to result in slightly slower runs, due to the (unidentifiable) parameter(s) for the additional root branch. 

Even when you are doing branch level analyses, you **should** be using unrooted trees, and asking questions in the unrooted context. There is simply no information in any of the time-reversible models to allow you to assign "direction" to a tree. Even the canonical relative rate test (Muse and Weir), operates on unrooted trees, and makes use of outgroup information outside the model itself (to interpret rate estimates).

Best,
Sergei

P.S. I would encourage you to consider using more recent models for the analysis of selection: https://github.com/veg/hyphy-tutorials/tree/master/selection
