### ISSUE TITLE
Node numbers in aBSREL

### ISSUE THREAD

**Issue by nmathers** [veg/hyphy#484]
Hello,

How can I view or interpret the node numbers given in the datamonkey aBSREL output? Also, is it possible to save the results output?

Thanks!

**Comment by nmathers** [comment]
Hi Steven,

I should have been more clear - sorry. By node numbers, I meant the phylogenetic tree node numbers. For example, in the table of aBSREL results there are particular nodes in the tree that contained signatures of selection but I do not know how to find those nodes on the tree.

I am wondering how these node numbers are assigned to a user submitted tree in aBSREL and if there is a way to display them on the tree viewing widget?

Thank you!

**Comment by spond** [comment]
Dear @nmathers,

The node numbers are assigned as the order of pre-order tree traversal (e.g. the root is Node 0), unless you label them in the tree directly when you submit your jobs, e.g.

```
((a,b)ab,(c,d)cd...
```

Presently the tree widget does not allow you to display internal node names (because of spacing and clutter issues) but if you think it is a useful feature, please add a feature request @ https://github.com/veg/phylotree.js

Best,
Sergei
