### ISSUE TITLE
Relax analysis output interpretation

### ISSUE THREAD

**Issue by nahidshokri** [veg/hyphy#492]
Dear Sergei,

I tried Relax analyses on my data which contain CO1 sequences of host and parasite bees. I used full model option in Hyphy as my aim is comparison the rate of evolution between test and reference branches. I understood from your paper that I need to look at the result of **Partitioned Exploratory MODEL** to answer my aim. I attached my Json output file here and have two quick questions about the output.
[RELAX analysis result-whole parasite against whole hosts.pdf](https://github.com/veg/hyphy/files/599674/RELAX.analysis.result-whole.parasite.against.whole.hosts.pdf)

1)Is that correct saying that rate of evolution in test branch(parasite bees) is higher than reference branches(host bees) because 95% of codons in test branches has an omega value 0.0227 while 99% of codons in reference branches has an omega value around 0.00955?

2)Does the number of test and reference branches affect the result of Relax analysis? 
Could you please help me with these questions?
Many thanks in advance
Nahid

**Comment by spond** [comment]
Dear @nahidshokri,

1. The **formal** RELAX test reports that there is no significant difference (p = 0.12). You **can** look at point estimates (like you describe), but you can't say that one is significantly higher than another, because they are never compared directly. One way to think about it is that the rate estimates themselves have inference errors, say 0.00955 ± 0.005, and 0.0243 ± 0.01. Now you can see while the point estimates are different, their "confidence intervals" overlap.

Further, if you compare AIC scores between models, **Partitioned Exploratory** fits the data less well than **Null**, so there is no evidence that the &omega; distributions are different between test and reference branches.

2. Yes, but the relationship is hard to define a priori. The more branches you have, the more data you have to make inferences from. However, the more branches you have, the more likely it is that the RELAX model is (at least somewhat) misspecified. Importantly, you don't want very small reference / test sets, because it is difficult to infer anything precisely from a small sample. That is mostly reflected in very low power to detect difference.

Looks like your data don't have enough signal for RELAX to say anything definitive, other than there is site-to-site rate variation in &omega; because **Partitioned MG94xREV** [branch only variation] has worse AIC than any other model [branch-site variation]

Best,
Sergei

**Comment by nahidshokri** [comment]
Thank you so much for your wonderful explanation. 

Kind regards
Nahid
