### ISSUE TITLE
Ho to modify GARD.bf to run a HYPHYMPI analysis?

### ISSUE THREAD

**Issue by luisdelaye** [veg/hyphy#496]
Hi,

I'm relatively new to HYPHY. 

I have HYPHYMPI installed on a cluster. And I would like to know how to input  parameters to HYPHYMPI to make a GARD analysis or how to modify GARD.bf to make the analysis.

Thanks in advance for your help!

Luis Delaye

**Comment by luisdelaye** [comment]
For instance, this is the file I give to the cluster command qsub:
#PBS -N test_msgA1
#PBS -l nodes=1:ppn=1,mem=1gb
#PBS -q default
#PBS -V		
module load hyphy/2.220
HYPHYMPI BASEPATH=/LUSTRE/usuario/ldelaye/ msgA1.bf

and this is the file msgA1.bf:

SALIDA = "hyphy-output.msgA";
DataSet myData = ReadDataFile ("msgA/msgA.subset2.fas");
DataSetFilter myFilter = CreateFilter (myData,1);
F81RateMatrix =
               	{{* ,mu,mu,mu}
                 {mu,* ,mu,mu}
                 {mu,mu,* ,mu}
                 {mu,mu,mu,* }};
HarvestFrequencies (obsFreqs, myFilter, 1, 1, 1);
Model F81 = (F81RateMatrix, obsFreqs);
Tree myTree = (((((((T551_00327_Pj,T551_02438_Pj),T551_03401_Pj),T551_01854_Pj),T551_02056_Pj),T551_01856_Pj),T51_01659_Pj),T551_00909_Pj,T551_03686_Pj);
LikelihoodFunction theLikFun = (myFilter, myTree);
Optimize (MLEs, theLikFun);
fprintf  (SALIDA, theLikFun);

How do I go from here to a GARD analysis?

Thanks a lot for your help!

Luis Delaye

**Comment by ArtPoon** [comment]
Hi Luis,

First of all, I think you're going to need to call `mpirun` or `mpiexec` when you are invoking `HYPHYMPI` -- otherwise, you will be running a serial analysis and not MPI.  Next, you will need to call `GARD.bf` within the `TemplateBatchFiles` directory.  It is helpful to use standard input redirection from a wrapper script instead of trying to run an interactive session with `HYPHYMPI`.  Sometimes the user prompt fails to echo queries from HyPhy about which inputs it needs when running in an MPI environment.  I'll dig around my laptop and see if I can find a quick example for you.

Best,
- Art.

**Comment by ArtPoon** [comment]
Here's my command line invocation on my Mac:
```
mpirun -np 3 ./HYPHYMPI res/TemplateBatchFiles/GARD.bf 
```
which gives returns this:
```
Initialized GARD on 3 MPI nodes.
Population size is 4 models

```

Nothing else happens.  Why?  Because HyPhy is waiting for input from the user.  But we don't know what it's asking for because of the echo bug that I mentioned before!  Let's hit <return> and see what it was expecting:
```
/Users/art/git/hyphy/res/TemplateBatchFiles/Nucleotide file to screen::
```

Okay.  It's going to be more effective to go through the actual `GARD.bf` script and pick out the inputs that we need to submit.  (I find it handy to search through the file for the string `SetDialogPrompt` or `fscanf`.  Note the number of inputs varies with the choices you make; for example, if you choose to model rate variation you will have to specify the number of rate categories.)  Otherwise you're going to have a real lousy time waiting for your job to make it through the queue on your cluster.  Let's open up a new file in a text editor (I'm gonna use `vi`) and start recording the responses we'd like to feed into HyPhy via standard input redirection:
```
/Users/art/git/hyphy/res/data/p51.nex
010010
1
gard.out
```

`p51.nex` is a little HIV RT alignment that has been distributed with HyPhy for ages.  `010010` is a model specification string for HKY85.  `1' is my response to modeling rate variation (the first option is "None").  `gard.out` is the name of a file that I'd like HyPhy to record the results to.  I saved this text in a file I called `stdin.txt`.  Now let's use some UNIX input redirection to feed this into HyPhy:
```
mpirun -np 3 ./HYPHYMPI res/TemplateBatchFiles/GARD.bf < stdin.txt
```

and now we see GARD off to the races!

```
There are 227 potential breakpoints. Bit size of the sample is 8.

Fitting a baseline nucleotide model...
Done with single partition analysis. Log(L) = -3327.66601956091, c-AIC  = 6689.802085204775
Starting the GA...

GENERATION 2 with 1 breakpoints (~0% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1]
          0  6689.80
          1  6680.61        9.188        167 
GA has considered        3/         227 (3 over all runs) unique models
Total run time           0 hrs 0 mins 0 seconds
Throughput                 inf models/second
Allocated time remaining 1000 hrs 0 mins 0 seconds (approx. inf more models.)

[ SKIPPING LOTS OF OUTPUT ]

GENERATION 52 with 3 breakpoints (~100% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1] [BP      2] [BP      3]
          0  6689.80
          1  6676.76       13.045        161 
          2  6663.30       13.455        197         726 
          3  6663.30        0.000        197         726 
GA has considered        106/     1923825 (388 over all runs) unique models
Total run time           0 hrs 0 mins 39 seconds
Throughput                9.95 models/second
Allocated time remaining 999 hrs 59 mins 21 seconds (approx. 35814996.61538462 more models.)
Performing the final optimization...
```

Now since I didn't specify an absolute path for the output file, `gard.out` got written to the `TemplateBatchFiles` directory where `GARD.bf` lives.  That's okay for throwing together this example, but you'll want to be more careful about where you're telling HyPhy to write things.

Hope that helps!
Cheers,
- Art.

**Comment by luisdelaye** [comment]
Hi Art,

Ok, thanks a lot for your email.

I will try that and let you know!

Best,

Luis



________________________________
De: Art Poon <notifications@github.com>
Enviado: lunes, 5 de diciembre de 2016 08:27 p. m.
Para: veg/hyphy
Cc: Luis José Delaye Arredondo; Author
Asunto: Re: [veg/hyphy] Ho to modify GARD.bf to run a HYPHYMPI analysis? (#496)


Hi Luis,

First of all, I think you're going to need to call mpirun or mpiexec when you are invoking HYPHYMPI -- otherwise, you will be running a serial analysis and not MPI. Next, you will need to call GARD.bf within the TemplateBatchFiles directory. It is helpful to use standard input redirection from a wrapper script instead of trying to run an interactive session with HYPHYMPI. Sometimes the user prompt fails to echo queries from HyPhy about which inputs it needs when running in an MPI environment. I'll dig around my laptop and see if I can find a quick example for you.

Best,

  *   Art.

-

**Comment by luisdelaye** [comment]
Great!

I will try that!

Luis



________________________________
De: Art Poon <notifications@github.com>
Enviado: lunes, 5 de diciembre de 2016 08:43 p. m.
Para: veg/hyphy
Cc: Luis José Delaye Arredondo; Author
Asunto: Re: [veg/hyphy] Ho to modify GARD.bf to run a HYPHYMPI analysis? (#496)


Here's my command line invocation on my Mac:

mpirun -np 3 ./HYPHYMPI res/TemplateBatchFiles/GARD.bf


which gives returns this:

Initialized GARD on 3 MPI nodes.
Population size is 4 models



Nothing else happens. Why? Because HyPhy is waiting for input from the user. But we don't know what it's asking for because of the echo bug that I mentioned before! Let's hit and see what it was expecting:

/Users/art/git/hyphy/res/TemplateBatchFiles/Nucleotide file to screen::


Okay. It's going to be more effective to go through the actual GARD.bf script and pick out the inputs that we need to submit. (I find it handy to search through the file for the string SetDialogPrompt or fscanf. Note the number of inputs varies with the choices you make; for example, if you choose to model rate variation you will have to specify the number of rate categories.) Otherwise you're going to have a real lousy time waiting for your job to make it through the queue on your cluster. Let's open up a new file in a text editor (I'm gonna use vi) and start recording the responses we'd like to feed into HyPhy via standard input redirection:

/Users/art/git/hyphy/res/data/p51.nex
010010
1
gard.out


p51.nex is a little HIV RT alignment that has been distributed with HyPhy for ages. 010010 is a model specification string for HKY85. 1' is my response to modeling rate variation (the first option is "None").gard.outis the name of a file that I'd like HyPhy to record the results to. I saved this text in a file I calledstdin.txt`. Now let's use some UNIX input redirection to feed this into HyPhy:

mpirun -np 3 ./HYPHYMPI res/TemplateBatchFiles/GARD.bf < stdin.txt


and now we see GARD off to the races!

There are 227 potential breakpoints. Bit size of the sample is 8.

Fitting a baseline nucleotide model...
Done with single partition analysis. Log(L) = -3327.66601956091, c-AIC  = 6689.802085204775
Starting the GA...

GENERATION 2 with 1 breakpoints (~0% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1]
          0  6689.80
          1  6680.61        9.188        167
GA has considered        3/         227 (3 over all runs) unique models
Total run time           0 hrs 0 mins 0 seconds
Throughput                 inf models/second
Allocated time remaining 1000 hrs 0 mins 0 seconds (approx. inf more models.)

[ SKIPPING LOTS OF OUTPUT ]

GENERATION 52 with 3 breakpoints (~100% converged)
Breakpoints    c-AIC  Delta c-AIC [BP      1] [BP      2] [BP      3]
          0  6689.80
          1  6676.76       13.045        161
          2  6663.30       13.455        197         726
          3  6663.30        0.000        197         726
GA has considered        106/     1923825 (388 over all runs) unique models
Total run time           0 hrs 0 mins 39 seconds
Throughput                9.95 models/second
Allocated time remaining 999 hrs 59 mins 21 seconds (approx. 35814996.61538462 more models.)
Performing the final optimization...


Now since I didn't specify an absolute path for the output file, gard.out got written to the TemplateBatchFiles directory where GARD.bf lives. That's okay for throwing together this example, but you'll want to be more careful about where you're telling HyPhy to write things.

Hope that helps!
Cheers,

  *   Art.

-

**Comment by luisdelaye** [comment]
Dear Art,

It worked! Thanks a lot!

Luis

**Comment by ArtPoon** [comment]
Glad it worked for you 😄
