### ISSUE TITLE
Unexpected results from PARRIS

### ISSUE THREAD

**Issue by luisdelaye** [veg/hyphy#503]
Hi,

I ran an analysis by using PARRIS with the following options (command line on an MPI environment):

1
1
infile 
2
1
3
1
2
3
1
outfile

however I got this strange result:
```
RUNNING MG94xREV MODEL COMPARISONS on 0



########### 3x3 CLASSES ###########

+--------------------+----------------+---------------+-----------------+------------------+-----------+-----+-----------+
|       Model        | Log Likelihood | Synonymous CV |  NS Exp and CV  |  N/S Exp and CV  |  P-Value  | Prm |    AIC    |
+--------------------+----------------+---------------+-----------------+------------------+-----------+-----+-----------+
| discr(3), M1a      |  -127737.01606 |    0.00000000 | 0.00000,   -nan | 1.00000, 0.00000 |    N/A    | 1216|  257906.03|
+--------------------+----------------+---------------+-----------------+------------------+-----------+-----+-----------+
| discr(3), M2a      |  -127294.68743 |    0.00000000 | 0.00000,   -nan | 1.00000, 0.00000 |    N/A    | 1218|  257025.37|
+--------------------+----------------+---------------+-----------------+------------------+-----------+-----+-----------+
```

I followed mostly the example from (Kosakovsky, Murrell and Poon, Evolution of viral genomes - Interplay between selection, recombination and other forces). The only difference (apart from the input file) was that I didn't choose the "Dual" option (point number 7 in Kosakovsky et al, pp. 12). Instead, I choose the "Recommended" option.

Any idea why I got that result?

Thanks!

Luis Delaye

**Comment by spond** [comment]
Dear Luis,

I haven't looked at the PARRIS file in a long time:)

Looking at the code (which was written by Konrad Scheffler), it seems that the MPI version does not report p-values, because you can't guarantee that M1a will return before M2a. The rest of the output is as expected. Your test is highly significant, however, because (running in HYPHYMP -c mode)

```
LRT=2*(127737.01606-127294.68743)
NO RETURN VALUE
LRT
884.6572599999781
p_value=1-CChi2 (LRT,2)
NO RETURN VALUE
p_value
0
```

Our current recommended method is BUSTED (https://github.com/veg/hyphy-tutorials/tree/master/docs/selection), but I think you will get the same result.

Best,
Sergei

**Comment by luisdelaye** [comment]
Dear Sergei,
Thanks!
I will try BUSTED.
Best!
Luis
