### ISSUE TITLE
Is it possible to output from MEME calculations the most likely ancestral state of internal nodes of the phylogenetic tree?

### ISSUE THREAD

**Issue by pjdias87** [veg/hyphy#504]
Presently, I am using BUSTED, MEME and MrBayes to infer branches and residues under positive selection and to reconstruct ancestral sequences, respectively.

Although these software’s show overall consistency, some codon positions identified by MEME as having high empirical Bayes factor score in certain phylogenetic branches (suggesting being under positive selection) were not consistent with the ancestral sequence state with highest probability inferred by MrBayes phylogenetic software suite (using the topology constrain option).

However, equation 1 of the paper describing the MEME algorithm seems to allow determining the probability for all sequence states in all branches in the phylogenetic tree and for all codons in the multiple alignment.

This observation lead me to hypothesize that MEME algorithm itself could be used to directly infer ancestral sequences, under the same phylogenetic model used to infer positive selection and, therefore, avoid the inconsistencies caused by the use of different software suites for identifying positive selection and for reconstructing ancestral sequences,

Does this hypothesis make sense? If the answer is yes, is it possible to output the likelihood (probability) score for each possible ancestral state for each internal node in the phylogenetic tree and for each codon position in the multiple alignment?

This output would allow comparing the ancestral sequences states reconstructed by MEME algorithm with those calculated using alternative phylogenetic software suites and to identify amino acid (nucleotide) residues that were consistently retrieved and those that were not.

Regards,

pj

**Comment by spond** [comment]
Dear @pjdias87,

MEME already infers such ancestral states internally (for generating the plots); at the moment that are only used to generate the "heat map" figures in question, and to count substitutions per branch.

The relevant code is in `TemplateBatchFiles/qndhelper2.ibf`:

```
...
// ------ MEME helper function --------

function obtainBranchWiseEBEstimates (_sFactor,_nsFactor1,_nsFactor2, _mixingP,filterString) {

        ....
        LoadFunctionLibrary ("AncestralMapper");
        ancID = _buildAncestralCache ("siteLikelihood",0);
        subMap = _tabulateSubstitutionsAtSiteByBranch (ancID,0);
        _destroyAncestralCache (ancID);

```

The call to `_buildAncestralCache` creates an "opaque" object for reconstructed states at the site, and you can use the functions from `TemplateBatchFiles/Utility/AncestralMapper.ibf` to do more with them other than creating a substitution map. For example, you can use the function `_mapCharactersBySiteNewick` to return a Newick string with appropriate labeling of internal nodes.

Best,
Sergei

PS I would recommend aBSREL instead of BUSTED to look for selection along branches.

**Comment by pjdias87** [comment]
Sergei,

1) Thanks for the suggestion on aBSREL, I have missed reading that paper.

2) Seems I will have to start learning the Hyphy Batch Language. Many thanks for directing me for the more suitable functions that could (should) be manipulated to obtain the data regarding the ancestral sequences states.

3) Small question to help strengthen my christima’s resolve to plunge and learn Hyphy scripting: 

I’m guessing the best way to understand the code supporting the MEME algorithm is to execute it step by step and then related it with the math in the corresponding paper. 

I believe MEME algorithm considers each codon independent of all others, so I was thinking checking the value of the parameters and of the variables after the completion of the calculus for each codon, and writing all the values for parameters and values to external text files.

You think this approach is feasible or should I expect Hyphy to easily “choke” after manipulating the code supporting MEME algorithm and get a “fatal error message” or something of the kind related with code dependencies?

Regards,

Pj

Ps. I want to congratulate you and remaining researchers for maintaining the Hyphy software and this forum with quick and high-quality support, I think all Hyphy users and the phylogenetic software community in general will join me on this point.

**Comment by spond** [comment]
Dear @pjdias87,

Firstly, thank you for your kind words. Much appreciated. 

For this specific issue, you don't really need to learn much of HBL; in fact, we are planning to release a completely redesigned library of standard analyses with complete documentation and much better usability in the next few months. 

Luckily, there already IS code to output information to files in MEME. If you look inside https://github.com/veg/hyphy/blob/master/res/TemplateBatchFiles/QuickSelectionDetection.bf (around line 1210), you will see that as the script runs, it accumulates per branch information into a dictionary variable (`bySiteBranchReports`), and then writes them to an output file around line 1548.

If you modify what is returned by `obtainBranchWiseEBEstimates` (which presently returns **per-branch** estimates of empirical Bayes factors for selection) to return ML ancestral states, then you should be able to output them to file with relatively little effort. I can give you further pointers, if you decide to do it, because none of the internal code is documented well, and some of the data structures relating to trees in HBL are quite counter-intuitive (this will change with the new release).

Best,
Sergei

**Comment by pjdias87** [comment]
Sergei

Many thanks for the these precious pointers, i Will give a shot on trying implementing the code modifications.

Nice to hear About the future improvement on documenting the internal code, undoubtdly it Will help  developing hyphy, in revision of code and improvement of methologies.

Regards and merry christima's,

Pj
