### ISSUE TITLE
RELAX - Test for selection "unknown"

### ISSUE THREAD

**Issue by JohnAbramyan** [veg/hyphy#507]
Dear HYPHY community, 

I am trying to run RELAX on the Datamonkey server on 499 sequences and 2715 codons. The analysis seems to run fine, a tree file is included in my uploaded file and that seems to work fine. Ultimately, my analyses ran for more than 30 hours and I received  emails today for all of my jobs stating:

" Test for selection unknown(K = unknown) was unknown(p = , LR = )"

Could you please advise on what went wrong and if there's anything I can do to obtain my selection values??

thank you, 
John A. 

p.s. here is a sample of what I received back:
http://test.datamonkey.org/relax/58640761067d92370400d1c7

**Comment by stevenweaver** [comment]
Dear John A.,

The issue appears to be that HyPhy (what datamonkey is using as a backend), did not perform all of the model fitting that datamonkey is expecting. 

For example, if you were to append `results` to your url like so http://test.datamonkey.org/relax/58640761067d92370400d1c7/results, you would see the JSON results that HyPhy reported. Instead of multiple "fits", HyPhy only performed model fitting with `Partitioned MG94xREV`. Datamonkey jobs do have a time limit of 4 days, but if the time limit were to be reached, the job should report as `aborted`. I will need to see why HyPhy only performed one model fit. 

Best,
Steven
