### ISSUE TITLE
The power of MEME  and BUSTED in detecting sites under selection

### ISSUE THREAD

**Issue by zhiyi1988** [veg/hyphy#513]
Deer Hyphy producers,

Thank you very much for composing this program which is very helpful for analyzing my data. I came up with this question when using it. Hope you can tell me how to deal with it.

Considering this circumstance; a gene is strongly conserved and in many taxa the amino acid on several sites are the same. However, one species or several species of the same taxon appeared, and they are with a quite different character or live in a quite different environment compared with the remaining taxa. These species may experience different regime of selection in order to adapt. 

So the question is as they are new, and positive selection produces new amino acid unique to them on some particular sites, will MEME become less powerful to detect  sites under significant episodic positive selection, and BUSTED be less powerful to detect selection on gene level? Since on these sites all other species have the same conserved amino acid, which may mean there is no episodic changes in the past and the model is likely to regard them as conservative. Moreover, as the number of species with the new character on these sites is much smaller (maybe even a single branch as the foreground branch), will it also hamper MEME and BUSTED to detect periodic positive selection? 

For example, the giant panda is carnivore but eats bamboo mainly, some of its genes may have changed for adaptation and the changes can be relatively recent considering the species' evolutionary time. Here is a very conservative gene I studied, but according to branch model, the model in which only Panda gene has a hint of positive selection is the best fit. However,

1. When I used BUSTED to test positive selection on panda branch only, although it detected three sites experienced episodic positive selection according to 2*constrained evidence ratio, the branch as the whole is not under selection. I noticed that substitutions on these three sites are almost unique to the panda, is this the reason why BUSTED gave the insignificant result?

2. I also applied RELAX to detect changes of selective strength on giant panda only. It suggested intensification of selection, but still not significant (K=7.53, p=0.07, LR=3,21). The best fit model, which is Partitioned MG94*REV, showed omega value of panda branch obviously larger than 1 and that of the Reference branches (by the way, should I choose model based on AICc or LRT here in RELAX?). So again, is this because I tested single branch and the substitutions only happened in one or two species?

3. Moreover, among the above three sites, one site is in concordance with the results of MEME and branch-site in PAML if I lower their critical value a little, as I got BEB=0.94, P=0.12 for my data respectively. This site is on a very conservative gene, and only Panda and Large brown bat has Arg, but all other species have Pro. According to the physicochemical aspect, the substitution can be critical to panda. It makes this peptide of panda stands out from others. So although not significant, can those results still be used to indicate that panda gene is quite different from others (at least carnivores)? Maybe because these analytical methods are conservative, the results were not significant but actually still worth noting?

Sorry that I wrote such a long passage to ask many questions.  

Best regards,
Zhiyi

**Comment by spond** [comment]
Dear @zhiyi1988,

As a rule of thumb, if you have _a priori_ information, e.g., a clade in your tree is evolving in a different environment or subject to different selective constraints, then you should **use this information** to define your analysis.

For example, you should use BUSTED to test for selection on the clade of interest. **Importantly**, you cannot define this clade of interest based on any analysis of the sequence data, because then you will be committing one of the [cardinal sins of hypothesis testing](https://en.wikipedia.org/wiki/Testing_hypotheses_suggested_by_the_data). 

At some point you might also have to simply accept that if you have a small sample, then you will not be able to attain statistical significance. For example, BUSTED will be adequately powered by ~5-10% of sites experience sufficiently strong selection (i.e. &omega; sufficiently greater than one). 

To answer your specific questions.

1. BUSTED does not actually **test individual sites** subject to selection. The reports based on evidence ratios are purely exploratory, and indicate which sites "prefer" to have an &omega; > 1 class of rates. The correct way to interpret a BUSTED result where the overall test is not significant is 
>BUSTED failed to find significant evidence of episodic selection on the selected branch(es)

2. You should never use [point estimates alone](http://stattrek.com/estimation/estimation-in-statistics.aspx) because they give you no sense of estimation error and confidence. Because the LRT test is not significant, this again **should** be interpreted as lack of evidence for selective intensification. The RELAX test is based on LRT. If you use AIC<sub>c</sub> for model selection, there still is **no evidence** that any particular &omega;>1. If, say Model 1 if preferred to Model 2, you cannot say that Model 1 is better because a specific parameter has a value in a specific range.

3. There is no statistical significance based on what you report. However, you could definitely use the results as **suggestions for further testing**, e.g. by site directed mutagenesis or something along those lines. In other words, you can claim that the site **may be** of interest, but **not because of any statistical significance**. 

Best,
Sergei
