### ISSUE TITLE
how to check using bs-REL recombinant sequences? is it possible?

### ISSUE THREAD

**Issue by sapuizait** [veg/hyphy#520]
I am examining appx 400 single copy orthologs in closely related bacterial strains. These bacteria have different hosts and their topology in the phylogenetic tree is following the host distribution. i would like to examine all of the 400 genes using the bs-REL in order to see if some of those genes in a specific branch of the phylogeny (that includes 2 bacterial strains that I am interested in) are under positive selection. 
After examining the alignments for traces of recombination it turns out that half of the genes (or more) show signs of recombination. Therefore I have split my genes into two groups and for now I am only working with those that show no signs of recombination but what do i do with the rest? I know that if I would like to examine the dn/ds with a model like SLAC or REL I would use the different topologies that come out as a result of the recombination but what do I do if I am specifically interested in using the bsREL model?
besides 1-2 manuscripts that I found where people simply ditched the genes with signs of recombination, I couldn't find anything else so any advice would be highly appreciated!

**Comment by spond** [comment]
Dear @sapuizait,

Unlike site methods (SLAC/FEL/FUBAR etc), BSREL and aBSREL (the recommended flavor) require a fixed topology for all sites. This is because you need the concept of a fixed branch to run inference, and recombinant sequences will not offer you this concept. 

You **could** screen all genes for evidence of strong phylogenetic discrepancy using GARD (or something like that), split them into several parts based on recombination breakpoints, where each segment will now be properly described with a single tree, and then run aBSREL on each segment separately. You will lose power doing this, however. 

Best,
Sergei

**Comment by sapuizait** [comment]
Dear Sergei

thank you for your answer

yes, thats what I suspected, and in order to test my hypothesis I need a very specific tree that I use for all gene alignments...

in that case even if I identify the recombination breakpoints and out of each gene I make 2 or 3 or more, since I will not be able to use my original topology but I will have to stick with the GARD topology it does not help with the testing of my hypothesis...
I guess it wouldnt make much sense to use (for the recombinant genes) only the gene alignment fragments that the GARD topology agrees with my original topology... would it?


Cheers
P

**Comment by spond** [comment]
Dear @sapuizait,

I would advise against cherry picking segments that match any particular topology, because this can introduce all kinds of statistical bias in your analysis. What I would recommend instead (if you were to use non-recombinant segments), is to use the topology that is the best fit to that segment, and then interpret what specific branches correspond to you in your analysis.

Of course, recombination itself is often the driver of adaptation (or is driven by it), so evidence of recombination at/near lineages of interest is probably quite interesting as well.

Best,
Sergei
