### ISSUE TITLE
fscanf() issues?

### ISSUE THREAD

**Issue by Batwarren** [veg/hyphy#522]
I've been heavily modifying BranchSiteRel.bf in an attempt to allow me to automate it from the command line over a large number of different input files in different folders to allow me to run it as an array on an SGE cluster. One issue that I have run into is using fscanf() to read files from the command line. Notably, the line: 

fscanf(stdin,"String",ALIGNMENT_IN);

appears to work as intended only in the situation that the input file in the folder is in fact called ALIGNMENT_IN. 

I'm using HYPHY 2.220170113beta(MPI) for Linux.

**Comment by lonelyjoeparker** [comment]
Just been having a stab myself (@batwarren asked for help because they were using [my dodgy hack from 2014](http://lonelyjoeparker.com/wp/?p=1156)) and the fscanf() seems odd for sure. 

thx @stevenweaver 

The context for this is big phylogenomics analyses running via [SGE](https://www.google.co.uk/search?q=sun+grid+engine&oq=sun+grid+engine&aqs=chrome..69i57.3526j0j7&sourceid=chrome&ie=UTF-8) array jobs. My workaround was basically motivated by a desire to pass multiple args from the command line. In this case these were I/O files and a parameter. The only good alternatives at the time (2014) seemed to me to be using hardcoded tmp files/params (pretty poo option as fragile/not pll) or having yet another script to text-edit a batch file for each rep (also a bit shonky).

So as a side note if there's a better way now to pass multiple args through the command line (and avoid said crappy bodge altogether), so much the better...

**Comment by stevenweaver** [comment]
Hi @Batwarren and @lonelyjoeparker,

Instead of using `fscanf`, I would recommend piping the arguments directly into `HYPHYMP`.

For example : 
```
(echo 1; echo 1; echo 2; echo /path/to/fasta; echo /path/to/nwk; echo /path/to/output) | ./HYPHYMP LIBPATH=`pwd`/res ./res/TemplateBatchFiles/BranchSiteREL.bf
```

Where : 

`1` : Universal Code
`1` : Use the adaptive version of BS-REL
`2` : Allow alpha to vary from branch to branch, while omega vafries among branch-site combinations
`/path/to/fasta` : the path to your fasta file (with no newick tree in its contents)
`/path/to/nwk` : the path to your newick file
`/path/to/output`: where you would like to store the results

Please let me know if this works for you. 

Best,
Steven

@lonelyjoeparker : Thanks for the blog post! It's great to see postings like this.

**Comment by lonelyjoeparker** [comment]
thx @stevenweaver, @Batwarren hopefully let us know how it goes? 

ps: np ;)

**Comment by spond** [comment]
Dear all,

I don't really have an improvement over what @stevenweaver suggested, but I would like to add a caveat HyPhy will not correctly process pathnames with spaces and other "escapable" characters in them, so be aware of that if you see odd errors. Not a common occurrence, but worth keeping in mind.

Best,
Sergei

**Comment by lonelyjoeparker** [comment]
Thanks @spond

**Comment by Batwarren** [comment]
@stevenweaver's suggestion does the trick, though I needed to add in a couple of extra options in order to get it past the branch selection as without an input there, it crashed. So the line for testing all branches (with redirects of stdout and stderr) was as follows: 

(echo 1; echo 1; echo 2; echo /path/to/fasta; echo /path/to/nwk; echo 2; echo d; echo /path/to/output) | /path/to/HYPHYMPI /path/to/TemplateBatchFiles/BranchSiteREL.bf > ${INDIR}_aBSRel.out 2>${INDIR}_aBSRel.err

This worked just fine with using variables in the pathnames to allow me to iterate over all of the files. Thank you!

**Comment by lonelyjoeparker** [comment]
I've updated the advice on the original [blog post](http://lonelyjoeparker.com/wp/?p=1156) to point here as the hack-of-choice.

**Comment by luisacusick** [comment]
Hi, thank you for your suggestions! I am using this for HyPhy RELAX, but I have not been able to re-direct output. This is a problem because I am trying to run the program a number of times on each element (shuffling the foreground species to evaluate how that changes the output), and if I do so without re-directing the output then the result file for each analysis will overwrite the file for the previous analysis. 

Here's the script that I am using for my output. It is working aside from the output re-direct issue:
${gene} is the name of the element; I am looping through a list of them

`counter=1
while [ $counter -lt 51 ]
do
  input_tree="$gene_$counter.tre"
  aln_path="/path/to/aln/${gene}.fas"
  tree_path="/path/to/tree/$input_tree"
  out_ext="$gene_$counter"
  output_path="/path/to/output/dir/${out_ext}"

  (echo 1; echo ${aln_path}; echo ${tree_path}; echo ${output_path}; echo 2; echo 2;) | /zfs1/nclark/Luisa/hyphy/HYPHYMP /zfs1/nclark/Luisa/hyphy/build/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/RELAX.bf
  let counter=counter+1
done`

I think the problem is that RELAX never prompts the user for the output directory. Is there a way to change that? Or would you recommend capturing whatever is written to std out and parsing that instead?

Thank you!

**Comment by spond** [comment]
Dear @luisacusick,

Starting with release 2.4 (and we are now at 2.5.5) HyPhy allows use to specify command line arguments via keywords and not much around with redirects (see http://hyphy.org/tutorials/CLI-tutorial/). For example, you can now write (see 

```
hyphy relax --alignment sequences.fas --tree tree.nwk 
```

Try 

```
hyphy relax --help
```

for a list of command line options. 

The resulting file will be written to `sequences.fas.RELAX.json`, i.e. it will use the same path as the input alignment and create a file with the extension `RELAX.json`. The resulting JSON file can be parsed using whatever language you are comfortable with (R, Python, etc), and can be visualized using vision.hyphy.org/RELAX 

See http://hyphy.org/resources/json-fields.pdf for a (somewhat out of date) specification of what's in the JSON file.

So your script might look like 

```
`counter=1
while [ $counter -lt 51 ]
do
input_tree="$gene_$counter.tre"
aln_path="/path/to/aln/${gene}.fas"
tree_path="/path/to/tree/$input_tree"
out_ext="$gene_$counter"
output_path="/path/to/output/dir/${out_ext}"

/zfs1/nclark/Luisa/hyphy/HYPHYMP relax --alignment ${aln_path} --tree ${tree_path} > output_path

let counter=counter+1
done
```

Best,
Sergei

**Comment by luisacusick** [comment]
Thank you very much!
I have a follow up question: you say "The resulting file will be written to sequences.fas.RELAX.json, i.e. it will use the same path as the input alignment and create a file with the extension RELAX.json." Is there any way for me to change this? I am running this a number of times on each element, and I don't want to worry about output files over-writing one another.
