### ISSUE TITLE
Detection of recombination with GARD vs. Geneconv

### ISSUE THREAD

**Issue by MMP2017** [veg/hyphy#531]
Hello,

I have been investigating the occurrence of recombination within alignments involving 4 to 21 sequences of 2500 to 5000bp long. For the same purpose we analyzed the same datasets in Geneconv. This program searches for unusually long regions of high identity between all pairs of sequences in an multiple alignment. The statistical significance is determined by random shuffling of variable sites in the alignment. 
I understand GARD is based on a completely different approach. However I am trying to figure out how these results converge and would appreciate your insight. 

Please consider the following example:

In an alignment of 13 sequences 4608bp long GARD detects 5 breakpoints at positions 1277, 2806, 3467, 3563 and 3950. Only the ones at 2806, 3563 and 3950 are statistically significant at p=0.05. 

However among the significant pairwise recombination events detected by Geneconv only the last one (#7) involves a track which covers one of the statistically significant breakpoints detected by GARD. 
In the table below you will notice that the recombination events identified by geneconv involve alignment positions 62 to 3471 (look at the numbers in the last two columns "Begin" and "End"), while the statistically significant GARD breakpoints are mostly outside of these positions, at 2806, 3563 and 3950.

Result Sequences involved Pvalue    BC Pvalue Begin End
1 Al_859975;Al_860059	0.0086	0.01427	448	630
2 Al_859995;Al_860059	0.0483	0.07295	152	231
3 Al_859995;Al_860060	0.0451	0.06346	152	231
4 Al_860059;Al_860060	0.0236	0.03770	87	683
5 AT5G41550;AT5G41740 0.0377	0.05337	1733	 1787
6 AT5G41740;AT5G41750 0.0000	0.00000	62 752
7 AT5G41740;AT5G41750 0.0000	0.00005	2788	 3471

I wonder if you tested the convergence between the results of GARD and other methods. The aim of employing different, but somehow complementary approaches to detect recombination in our datasets was to cross-validate our results. 
Please let me know what you think about this approach to cross validation and whether you have compare the results from GARD and Geneconv (http://www.math.wustl.edu/~sawyer/geneconv/)

Thanks in advance for your time and looking forwards to your response.

**Comment by spond** [comment]
Dear @MMP2017,

Yes, we have compared the performance of GARD to other tools, including GENECONV (see Figure 2 in  https://academic.oup.com/mbe/article-lookup/doi/10.1093/molbev/msl051). Of course, this is done on simulated data, because then we know the truth. 

GARD and pairwise tools will generally report different results, because GARD looks for **large** changes in topology, and considers all sequences jointly. GARD is not designed to primarily find individual sequences involved in recombination events, but rather partition sequences into putatively recombination free fragments. 

Have you looked at RDP4? It's a nice tool that brings multiple recombination scanning approaches in a single package.

Best,
Sergei

**Comment by MMP2017** [comment]
Dear Sergei,

Many thanks for your explanation and the references.

Bests,

Mariana
