### ISSUE TITLE
datamonkey duplicate sequences

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#539]
The parser in datamonkey (test.datamonkey.org) seems to automatically remove duplicate sequences without warning. Possibly this should be a setting to toggle.

**Comment by stevenweaver** [comment]
Hi @sjspielman,

I agree that we should have some sort of user feedback whenever data files are manipulated.

Instead of an option, perhaps a warning message should appear to the user that they have uploaded a file with duplicate sequences, and then ask them if they wish to proceed.

Best,
Steven

**Comment by snaketron** [comment]
Why are duplicate sequences (by default) removed? 

Duplicate sequences occur quite often when one generates sequence alignments of different species (e.g. for different mammalian proteins). Can this additional piece of evidence not be used to improve the parameter inference?

Best

**Comment by spond** [comment]
Dear @snaketron,

Duplicate sequences contribute no additional information to most likelihood based phylogenetic sequence analyses. This is because you can model them with a zero-branch length which yields the probability of "not evolving at all" of 1 (i.e. does modify the value of the likelihood function). Including them does, however, incur additional computational costs. 

The only parameters that will be (mildly) influenced by duplicate sequences are the estimates of base frequencies, which, again is deemed not worth the added computational costs. 

Best,
Sergei

**Comment by MarcNiebel** [comment]
Dear @spond,

Some additional questions to this comment:
Does the command line version remove duplicates or does one need to do this beforehand?
Hypothetically, if one had sampled patients longitudinally would it be advisable to remove duplicates as well?

Kind Regards,

Marc

**Comment by spond** [comment]
Dear @MarcNiebel,

No, the command line version does not remove sequence duplicates automatically. This can be done via standalone scripts (see the thread for Issue 858)

You don't **have** to remove duplicates, it simply speeds up computation. 

Best,
Sergei

**Comment by MarcNiebel** [comment]
Dear @spond 

Thanks for that.

Kind Regards,

Marc

**Comment by rdvelazquez** [comment]
Moved this issue to the datamonkey repo: https://github.com/veg/datamonkey-js/issues/183
