### ISSUE TITLE
GA-RELAX ?

### ISSUE THREAD

**Issue by VinnyLynch** [veg/hyphy#540]
Hi All,

Is it possible to modify RELAX to automatically partition all branches of the phylogeny into groups according K? Something akin to what GA-Branch does for dN/dS?

Thanks
Vinny

**Comment by spond** [comment]
Dear @VinnyLynch,

Conceptually it is possible, sure. I haven't thought about that use of the method; did you have a use case in mind?

Best,
Sergei

**Comment by VinnyLynch** [comment]
Hi Sergei,

I always have use cases in mind, whether they make sense to actually carry out is the question!

Here is what I have in mind: We tested whether the progesterone receptor was positively selected in the human lineage, as previously suggested, using aBSREL and BUSTED. Neither found evidence for selection, but RELAX was significant with K=0 suggesting the episode of rapid evolution may be the result of relaxed constraint. So I'm curious if that relaxation is unique to the human lineage, or part of a larger trend in apes, or old world monkeys, or simiiform primates, or any other number of nested clades in which humans are a member. It doesn't seem right to just define a bunch of foreground lineages to test with RELAX, given I have no a priori hypothesis about which lineage the relaxation may have stated in. In such a case the more agnostic approach of GA-RELAX seems more (statistically) appropriate.

Vinny

**Comment by spond** [comment]
Dear @VinnyLynch,

OK, that makes sense. Bolting GA on RELAX at the moment would be a bit tricky (because I am rewriting major parts of HyPhy and everything in flux), but I will be factoring GA bits out soon enough (as a part of porting GARD to the new core/datamonkey implementations), so in a month or so it may be ready. 

In the meantime, you could try (this is totally a finish expedition, and not statistically justified, but you can do it now), the full exploratory model, which assigns a separate <kbd>k</kbd> to each branch, just to see what the distribution looks like, e.g. do some clades look "hot" or "cold". Then you can "test" a data driven hypothesis (which of course will be biased towards finding significance), where you choose which branches to put in the foreground based on the exploratory fit. The idea is that you *don't* find anything interesting in such a biased analysis, then there is nothing to be found. If you do find something, then you something like GA RELAX is worth pursuing. 

Best,
Sergei

**Comment by VinnyLynch** [comment]
Hi Sergei,

Thanks for the quick response. Your ad hoc approach sounds like a good way to explore the data. We'll give it a try. As for GA RELAX, we're not in a rush and happy to have to as a co-author on any paper that uses the method. 

Best,
Vinny

**Comment by stevenweaver** [comment]
Since further correspondence wouldn't involve this issue specifically, I'm going to go ahead and close it.
