### ISSUE TITLE
MEME MPI command line results - issue with q-values?

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#544]
Dear Developers,

I am trying to anayze my sequences for codons under selection.
I am using HyPhy MPI on CentOS command line (since I have a "large" dataset: 172 sequences, ~ 150,000 sites). I am currently working with test data (HIV polymerase) just to get my pipeline up and running before using real data.
After reading the MEME paper, I have run GARD on the HIV pol, then run MEME following this tutorial:
https://github.com/veg/hyphy-tutorials/tree/master/docs/selection
Thus choosing option 10 (positive selection), then option 9 (Quickly test for positive selection using several approaches), and so on.

When I look at the final cvs file, I do get significant p values, but the q values are all > 0.48.
Looking around I found that q-values for QuickSelectionDetection.bf may be bugged:
http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1390912207/1
It is somewhat an older post, I wonder if it still applies. In the same post it is also stated that the q-value is overconservative and it is not recommended to be used to spot selection at individual sites.

I am also not sure if I could follow a different path:
at the very beginning of HyPhy, I could choose option 12 (Selection/Recombination) --> option 2 - MEME. Is it going to do a different analysis? I have noticed that in this case, the resulting q values vary from 0 to 1, although many codons (171/520) have q-value=0 and p-value=1 !
I would like your opinion about it, and your advice regarding the correct way/statistic to assess my sequences.
Thank you for your kind consideration.

Sincerely,
Max Tagliamonte

**Comment by mstagliamonte** [comment]
P.S.: Here are my results:
[HIV.meme.test01.option10.gtr.txt](https://github.com/veg/hyphy/files/965647/HIV.meme.test01.option10.gtr.txt)
[HIV.meme.test02.option12.gtr.txt](https://github.com/veg/hyphy/files/965649/HIV.meme.test02.option12.gtr.txt)

**Comment by spond** [comment]
Dear @mstagliamonte,

The q-values in the MEME implementation are indeed somewhat buggy and we don't recommend their use. They were put there at some point because I reviewer insisted that we compute them. The standard practice for MEME is to use raw p-values and choose them based on the level of sensitivity/specificity you are comfortable with.

q-value = 0 for a p-value of 1 is clearly a silly bug on my part (these will most likely are invariable sites where there is no signal for selection).

In any case, we are about to release a completely re-engineered MEME with the new version of HyPhy/Datamonkey.

Best,
Sergei
