### ISSUE TITLE
Interpreting results from RELAX

### ISSUE THREAD

**Issue by j-kominek** [veg/hyphy#559]
Dear HyPhy team,
I am running some RELAX analyses locally and I am getting confusing results. One one hand, I get a significant p-value for K being different from 1, but at the same time the best fitted model based on both LnL and AIC-c is the General Descriptive, not Alternative (which is second best, but by a pretty large margin). How to interpret this kind of results? Does the test mean that there is enough support to trust the Alternative model, or should I always stick to the best fitted one? I attach a zip file with an alignment, tree and BF file used to run one analysis that I saw this in, as well as the JSON output from it. Thanks in advance for helping me out!

Cheers,
-Jacek
[GAL10_pal.fas.best.fas.zip](https://github.com/veg/hyphy/files/1058850/GAL10_pal.fas.best.fas.zip)

**Comment by spond** [comment]
Dear Jacek,

The RELAX test is a test of two nested models (Null vs Alternative) based on the likelihood ratio test. This is where K &neq; 1 inference will come from. It is **predicated** on the assumption that K = 1 under the null, so all it does is to test for selective intensification/relaxation somewhere on **test** branches.

Since _General Descriptive_ allows each branch to have its own **selection intensity** parameter (`k`), it will always provide a better fit that the Alternative model (each branch allocated to one of two values). Because AIC-c prefers _General Descriptive_, you can conclude two things

1. There is relaxation (K < 1) or intensification (K > 1) of selection on test branches relative to reference branches. This inference is based on the LRT.

2. There is also evidence of non-uniformity in selective pressures within each group of branches, I.e. the evolutionary process is variable through time. This inference is based on the AIC-c.

The two inferences are perfectly compatible.

Best,
Sergei

**Comment by j-kominek** [comment]
Dear Sergei,
Thank you for the clarification, much appreciated. I am still confused though, because wouldn't non-uniformity in selective pressures within each group of branches favor the Partitioned Exploratory model (different sites proportions and omegas in the test and ref) rather than the General Descriptive (different proportions and omegas across sites, but identical across branches in both test and ref)? The way I understand the two pieces of evidence are somewhat contradictory - one says that Alternative is better than Null, which means that there is diversity, but then the other says that the best model fitting the aligment fits one omega to 3 classes across all branches (ref and test), which points towards uniformity of rates in those two types of branches...I am probably getting something wrong here, so please bear with me, and thank you in advance for your help.

**Comment by spond** [comment]
Dear @j-kominek,

**General descriptive** model is (in almost all cases) the most general model fitted, because it has **branch-level** parameters. **Partitioned Exploratory** model is meant to investigate if selective regimes (&omega; and proportions) are different in a more complex way that simply shrinkage or expansion relative to &omega; = 1 (as Alternative does). It only adds 5 more parameters relative to **Alternative**, whereas **General Descriptive** adds B-2 (where B = number of branches). 

**General descriptive** model does not imply uniformity, but rather the __non__-uniformity over branches. 

Best,
Sergei

**Comment by j-kominek** [comment]
Dear Sergei,
Thanks again, I think I understand it now after your comment and re-reading the relevant part from Wertheim et al, 2014. I didn't realize that GD allowed branch-specific relaxation of K, so after looking into the JSON output I thought that all it provided was a single distribution of omega across all branches (like a site model from PAML), which was a mistake. 
I wonder if there is a way to access this branch-specific K somehow? I looked back at the JSON output and some models provide K as annotation-tag, but General Descriptive uniquely uses omega values for branch-annotations. If I understand correctly these branch-specific omegas are derived in some mathematical way from the average site distribution and the branch-specific K, right? It would be nice to access the K values themselves for visualization purposes on a tree, much like the RELAX module does on test.datamonkey.org.

Best,
-Jacek

**Comment by j-kominek** [comment]
Sorry, please disregard my previous question. I misread the annotation-tag between models - the omega is for the "Partitioned MG94xREV", not for GD, so all the Ks are there within the GD's section of the output as they should.

**Comment by j-kominek** [comment]
One more question, or perhaps just more of a check - the selection regime written in the JSON output of the **General Descriptive** model is the average selection regime that each of the branches relaxes or intensifies at it's own rate of branch-specific K, right?

**Comment by spond** [comment]
Dear @j-kominek,

Not quite average, but yes, it's a single branch level parameter. Recall that RELAX fits a 3-bin distribution of &omega; over **sites**:

&omega;<sub>i</sub> (with weight p<sub>i</sub>) where i = 1..3, with the added constraint that the geometric mean of &omega; = 1. The constraint is necessary for identifiability. 

Then each branch modifies this distribution by raising each &omega;<sub>i</sub> to power **k**, where **k** is the estimated branch-specific parameter (written to JSON). The p<sub>i</sub>parameters are the same for all branches. 

Best,
Sergei

**Comment by j-kominek** [comment]
Dear @spond,
Thank you again for the clarification, I am now much clearer about how different models work. I am still puzzled about one result though - when I do my analysis, I get a significant p-value for the Null vs Alternative test, and the K is lower than 1, which indicates relaxation of selection on the test branches. However, when I look at the branch-specific Ks output in the General Descriptive model (which is the best fit), I see that most of the test branches actually have Ks higher than the reference branches, which would suggest intensification of selection! In that case, I would expect (correct me if I'm wrong) that the K from the Null vs Alt test to be higher than 1, since it's averaged across the test branches, no?

**Comment by spond** [comment]
Dear @j-kominek,

While your intuition is correct, the results don't necessarily contradict it. If you think as the K estimate from the "Alternative" model as being, roughly, the average of the individual *k* estimates from the general descriptive models, then you would indeed expect that this average should be < 1. However, there are two wrinkles with this analogy.

1. In the general descriptive model, the more correct analogy would be to take the ratio of the averages of the "test" to "background" **k** estimates, because, if you look at the tree, many branches in the background also have k>1 estimates.

2. A better yet analogy is to add weighting to the average process, where different branches pull the mean with different forces. It could very well be that changes in a branch with **k<1** have an outsized influence on the log-likelihood, and would have to be considered more important than changes to branches with **k>1**. We don't know what those weights are _a priori_, but you could explore them by estimating standard errors on the **k** MLEs (using profile likelihood, for example). That is somewhat analogous to standard weighted mean where points with higher variances are "down-weighted".

Best,
Sergei
