### ISSUE TITLE
Working with trees in HBL

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#572]
Hi,

Is there a way to work with trees (add node, get node, ect.) in HBL?

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

Yes, there are many accessor functions, and some modification functions. Take a look at

1. [Get information about nodes and paths in the tree](https://github.com/veg/hyphy/blob/v2.3-dev/tests/hbltests/UnitTests/HBLCommands/BranchLength.bf)

2. You can access addition information on tree nodes via http://hyphy.org/w/index.php/GetInformation

3. In order to modify a tree object you can use + / - operations, like in the example below

```
Topology T = ((a:0.1,b:0.2)ab:0.05, (c:0.01,d:0.02)cd:0.03, ef:0.07);

fprintf (stdout, Format (T,1,1), "\n");

T + {"NAME": "e", "WHERE" : "ef", "LENGTH" : 0.125};
T + {"NAME": "f", "WHERE" : "ef", "LENGTH" : 0.15};

fprintf (stdout, Format (T,1,1), "\n");

T - "c";

fprintf (stdout, Format (T,1,1), "\n");
```

Best,
Sergei

**Comment by halabikeren** [comment]
Great, Thank you!
