### ISSUE TITLE
GARD analysis is too slow

### ISSUE THREAD

**Issue by SrivastavaM** [veg/hyphy#580]
Hello all, 

I run the command  on 56 nodes slurm cluster as following for computing around 3000 alignments

mpirun -np **56** HYPHYMPI run_GARD.bf

in 40 hours only 92 jobs are done. 

Thanks for your Suggestions

~
Srivastava

**Comment by stevenweaver** [comment]
Dear Srivastava, 

A dataset of 3000 sequences is quite large. Computational expense accelerates with growth, and it is CPU-bound. You may want to start with a smaller dataset to ensure that GARD will work for you.

How many sites do each of your sequences contain?

Additionally, the -np flag for mpirun declares the number of *processors*. Each node on a cluster most likely has anywhere from 8-32. 

Best,
Steven

**Comment by SrivastavaM** [comment]
Dear Stevan,

Thanks. In my local system its running much faster where I only have 4 cores , 16GB RAM. Here I am using OPENMPI but it cluster I have MPICH2. Do you think that might be a problem. If your answer is yes then do I need to have  OPENMPI  at cluster or I have any other option.

~
Srivastava

**Comment by stevenweaver** [comment]
Srivastava,

Conceptually, different MPI implementations should not impact performance drastically. At most, it would be something I would take into consideration only if the cluster is having performance issues despite whichever software package is being utilized. Even at that point, you would want to consider network latency issues first.

First, check what kind of processors your cluster has. Per core performance has improved drastically in processors over the past 4 years. If the cluster is old, that could simply be the case. Another possibility is that your cluster is heterogeneous. For example, if your head node has an Intel Xeon family processor, but the slave nodes have AMD processors, compiler optimizations conducted on the master node by while building HYPHYMPI could cause degraded performance. 

I would check that this issue is specific to HyPhy, or if it could be generalized. 

Best,
Steven

**Comment by SrivastavaM** [comment]
Hi our cluster is rather new and not heterogeneous. Today we checked the performance over local system but surprisingly the performance is decreasing when we are increasing the number of cores.
