### ISSUE TITLE
Using GARd on SNP data

### ISSUE THREAD

**Issue by mstagliamonte** [veg/hyphy#624]
Dear Authors,

I have a large coding SNPs dataset, and I would like to screen for recombination. I wonder if it would be correct to use GARD on a SNP alignment (i.e. a pseudo-sequence only containing SNPs from multiple genes). Would this strategy bias the analysis?

As an alternative, I could re-create the sequence for each isolate for each gene, SNPs included. Would it be correct to concatenate all the genes (possibly separated by stretches of 'Ns')? Or do I need to analyze each gene separately?

Also, as my SNPs only refer to coding segments, when generating the gene alignment, I would actually be joining the exons. Would this be a problem with GARD?

Thank you for your kind attention,
Max

**Comment by spond** [comment]
Dear @mstagliamonte,

Not a problem. We have done just that (SNP only) in a [published analysis](http://www.pnas.org/content/108/46/18732). 

Concatenating the genes (with sequences between SNPs) will

1. Make the analysis run **much** longer
2. Result in the same inference (essentially), because GARD will only place breakpoints on variable sites. 

Best,
Sergei

**Comment by mstagliamonte** [comment]
Dear @spond ,

Thank you for your help, being able to use the SNP alignment will makes things much easier. I will test it as soon as Irma lets me go out and play again.

Kind Regards,
Max
