### ISSUE TITLE
Document/Fix g++ version requirement

### ISSUE THREAD

**Issue by averagehat** [veg/hyphy#628]
[These lines](https://github.com/veg/hyphy/blob/926b1a36fb295481759b6bc53c42af84786627fa/CMakeLists.txt#L102-L106) hide a requirement for gcc version >= 4.9. Is this intended or necessary? It would be nice if this was in the README somewhere.

**Comment by stevenweaver** [comment]
Dear @averagehat,

Thank you for raising this issue. It is necessary because we have decided to move forward with using c++11 and c++14 features in our code base. Some of the new code was mainlined with HyPhy versions > 2.3.0 

https://gcc.gnu.org/projects/cxx-status.html

I've made a pull request with documentation and CMake requirement declaration updates. The changes should be in version 2.3.4.

Best,
Steven
