### ISSUE TITLE
Syntax error not raised in RequireVersion

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#634]
When "RequireVersion(...);" is syntactically wrong (i.e. no semi-colon), error not raised and instead (seems to) just assume requirement not met. Can simply reproduce with the following:

```
//with semi-colon, prints hello
RequireVersion(2.3.3);
fprintf(stdout, "\nhello\n");

/*******************************************/

//without semi-colon, there is **no** output but also no syntax error raised
RequireVersion(2.3.3)
fprintf(stdout, "\nhello\n");
```

**Comment by stevenweaver** [comment]
Hi @sjspielman, 

This is not an issue with RequireVersion specifically. It is an issue with the parser. 

I'm going to go ahead and close this bug with the idea that we will be tracking updates to the Parser (the development on it will likely not be occurring until next year) in our internal issue tracking system. 

Best,
Steven

**Comment by spond** [comment]
Dear @sjspielman  and @stevenweaver,

I can confirm that this issue is not specific to "RequireVersion", but rather a general parser issue which will be addressed wholesale in the migration to v3.

I do want to point out that the argument to `RequireVersion` is expected to be a string, as it

```
RequireVersion ("2.3.3");
```

Best,
Sergei
