### ISSUE TITLE
How to calculate dN and dS ?

### ISSUE THREAD

**Issue by nainiburman21** [veg/hyphy#645]
Can anyone describe how to calculte dN and dS in HyPHY GUI as I am not able to find any tutuorial of it on web.
Thanks

**Comment by stevenweaver** [comment]
Dear @nainiburman21,

This is actually a difficult question to answer since dN/dS ratios can be inferred in many different ways. There is an associated pdf that comes with the installation of HyPhy entitled `SelectionAnalyses.pdf` that may be helpful. 

This [link](http://hyphy.org/w/index.php/Workshop:Vancouver2011:SelectionAnalyses) or this [link](http://www.hyphy.org/w/index.php/Workshop:Fudan2013:SelectionAnalyses) from workshops may also help if you are looking for an online resource.

Best,
Steven

**Comment by nainiburman21** [comment]
Thank u sir.

-----Original Message-----

**Comment by stevenweaver** [comment]
You're welcome!
