### ISSUE TITLE
aBSREL error throw

### ISSUE THREAD

**Issue by labrat789** [veg/hyphy#647]
Hi there, first time submitting to github so my apologies if I screw something up.

I'm currently running aBSREL on a alignment of 100 sequences of 577 codons, and I keep getting this error thrown:

### Improving parameter estimates of the adaptive rate class model
Error:

Master node received an error:Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-107831] does not match the last recorded LF maximum [-107831]

Function call stack
1 : Optimize storing into, mles, the following likelihood function:^lf_id ; 
-------
2 : absrel.full_model.fit=estimators.FitExistingLF(absrel.likelihood_function_id,absrel.model_object_map)

This happens with single threaded and MPI versions. I've tried editing the likefunc.ccp file according to an earlier post, but to no avail. Is there some other fault in my data file that I'm unaware of? Or something related to the data itself?

Many thanks for your time,
Chris

**Comment by spond** [comment]
Dear @labrat789,

Would you mind sharing the datafile with me (email to spond.at.templ.dot.edu)? The error you see indicates that one of the optimization heuristics used by HyPhy needs to be adjusted. There's nothing wrong with your data, it's just an internal error. HyPhy throws it because when encountered (which it should not), the overall optimization results can be wrong. 

Finally, which version of HyPhy are you using?

Best,
Sergei

**Comment by labrat789** [comment]
Hi Sergei, thanks for the response. Sent an email, let me know if you need anything else.

chris

**Comment by spond** [comment]
Dear @labrat789,

I was able to confirm that the current release (2.3.4) is able to process your file without errors, hence I am closing the issue. Further details are in the e-mail I send you.

Best,
Sergei
