### ISSUE TITLE
error when loading a Newick tree file

### ISSUE THREAD

**Issue by zhaoxvwahaha** [veg/hyphy#651]
My newick tree file like this:

(198.1-1604.Asia.Israel.non-USA.Tel_Hashomer:0,
(((((((198.1-1151.North_America.USA.OH.Mentor:0.017339,
198.1-1695.Europe.Denmark.non-USA.Hvidovre:0.014082
)59:0.00092,
((198.2-2720.North_America.USA.NJ.Teaneck:0.007156,

but when loading it into hyphy, it report error like this:
Error:
Node names should begin with a letter, a number, or an underscore. Had:(198.?1-1604.Asia.Israel.non-USA.Tel_H
Function call stack
1 : Read the following data from PROMPT_FOR_FILE : Tree into givenTree;
-------

Do you know how to solve it?

**Comment by zhaoxvwahaha** [comment]
And I load my tree file to MEGA, there is no problem.

**Comment by spond** [comment]
Dear @zhaoxvwahaha,

Until more recent versions (2.3.3 and later), where this restriction has been removed for many standard analyses, HyPhy requires that your taxa names must only include letters, numbers, or underscores. You can upload your data to Datamonkey and then retrieve the converted alignment + tree file, because Datamonkey will convert taxa names for you, or you can do it manually. For example you would need to rename

`198.1-1604.Asia.Israel.non-USA.Tel_H` to `198_1_1604_Asia_Israel_non_USA_Tel_H`

Best,
Sergei

**Comment by zhaoxvwahaha** [comment]
Hi Sergei,

Thank you very much for your help, I followed your advice and changed the name, but I also have a problem:
After loading the tree, I enter the number of sequence types, nothing happened to hyphy (windows /GUI version), but it can continue on linux version, so do you know this problem?

Best,
zhao

**Comment by spond** [comment]
Dear @zhaoxvwahaha,

Please make sure you are typing your input into the lower window of the console, like shown in the attached screenshot

Best,
Sergei

![screenshot 2017-09-30 10 22 16](https://user-images.githubusercontent.com/1018513/31046604-6c7fb0d8-a5c9-11e7-977e-0a256017620b.png)

**Comment by zhaoxvwahaha** [comment]
Dear Sergei,

Following your guide, Hyphy run normally now, thank you very much for your help.

Best Wishes,
Zhao

**Comment by zhaoxvwahaha** [comment]
Dear @spond ,

I also have two problems when using Hyphy to do "Slatkin-Maddison test" on linux, and I don't find guide or example on homepage, so I ask for your advice:
(1) when running HYPHYMP, I manually input the options one by one, such as type of analyses, the reg exp used to define clade and so on. Can we run the Hyphy by command line, i.e. put these options as the parameters, for example : HYPHYMP -a -b -c
(2) Because I have dozens of tree files to do this analysis, so I need the batch mode, and the Hyphy denote that "Please select type of analyses you want to list (or press ENTER to process custom batch file)", I have no idea about the "custom batch file", I try to give a file which is the list of my tree files, but that didn't work, I should misunderstand the means, so could you give me some help?

Looking forward to your reply,
Zhao

**Comment by zhaoxvwahaha** [comment]
Dear Sergei,

I try the batch file mode by typing "./HYPHYMP hyphy-2.2.6/lib/hyphy/TemplateBatchFiles/SlatkinMaddison.bf" , but this also need I manually type the input file, enter a reg exp used to define clade, enter a descriptive name for TYPE and define the permutations times, so how could I run the Hyphy by parameter rather than the interactive shell?

Looking forward to your reply,
Zhao

**Comment by rdvelazquez** [comment]
Dear @zhaoxvwahaha,

If you are still looking to run Slatkin-Maddison analyses, we have developed a new method which can be run via this batch file: https://github.com/veg/hyphy/blob/develop/res/TemplateBatchFiles/SM-2019.bf from the develop branch. This method runs both the canonical Slatkin-Maddison test as well as a modified version.

This analysis is also available at http://galaxy.hyphy.org under "hyphy" in the list of tools on the left of the homepage.

Regarding running hyphy by parameter rather than interactive shell. We are in the process of implementing key word arguments (parameters) which will be included with the next release.

Best,
Ryan

**Comment by Xiaojun928** [comment]
Hi, 

I am runing SM test for strains from over 30 locations. My newick file is attached. When I run this command in Linux
`hyphy sm Pro_spatial.nwk --groups 33 pos1 pos1* pos2 pos2* pos3 pos3* pos4 pos4* pos5 pos5* pos6 pos6* pos7 pos7* pos8 pos8* pos9 pos9* pos10 pos10* pos11 pos11* pos12 pos12* pos13 pos13* pos14 pos14* pos15 pos15* pos16 pos16* pos17 pos17* pos18 pos18* pos19 pos19* pos20 pos20* pos21 pos21* pos22 pos22* pos23 pos23* pos24 pos24* pos25 pos25* pos26 pos26* pos27 pos27* pos28 pos28* pos29 pos29* pos30 pos30* pos31 pos31* pos32 pos32* pos33 pos33*--replicates 10000 --output Pro-location.sm.jason > hyphy_log.txt`

I got the error like this:

> Error:Empty branch set for _pos2_ in call to assert(Abs(_value_)>0, "Empty branch set for _"+sm.regexp_to_name[_key_]+"_");
Empty branch set for _pos2_ in call to assert(Abs(_value_)>0, "Empty branch set for _"+sm.regexp_to_name[_key_]+"_");

It seems no one met such a problem before. Could you please let me know what I should do?
Thanks in advance!

Since *.nwk cannot be upload, I changed it into txt.
[Pro_spatial.txt](https://github.com/veg/hyphy/files/6837487/Pro_spatial.txt)

**Comment by spond** [comment]
Dear @Xiaojun928,

Please use the expected command line syntax and enclose arguments like `pos21*` in single quotes to avoid shell expansion

```
hyphy sm --tree ~/Downloads/Pro_spatial.txt --groups 33 --description-1 pos1 --regexp-1 'pos1_.*' --description-2 pos2 --regexp-2 'pos2_.*' --description-3 pos3 --regexp-3 'pos3_.*' --description-4 pos4 --regexp-4 'pos4_.*' --description-5 pos5 --regexp-5 'pos5_.*' --description-6 pos6 --regexp-6 'pos6_.*' --description-7 pos7 --regexp-7 'pos7_.*' --description-8 pos8 --regexp-8 'pos8_.*' --description-9 pos9 --regexp-9 'pos9_.*' --description-10 pos10 --regexp-10 'pos10_.*' --description-11 pos11 --regexp-11 'pos11_.*' --description-12 pos12 --regexp-12 'pos12_.*' --description-13 pos13 --regexp-13 'pos13_.*' --description-14 pos14 --regexp-14 'pos14_.*' --description-15 pos15 --regexp-15 'pos15_.*' --description-16 pos16 --regexp-16 'pos16_.*' --description-17 pos17 --regexp-17 'pos17_.*' --description-18 pos18 --regexp-18 'pos18_.*' --description-19 pos19 --regexp-19 'pos19_.*' --description-20 pos20 --regexp-20 'pos20_.*' --description-21 pos21 --regexp-21 'pos21_.*' --description-22 pos22 --regexp-22 'pos22_.*' --description-23 pos23 --regexp-23 'pos23_.*' --description-24 pos24 --regexp-24 'pos24_.*' --description-25 pos25 --regexp-25 'pos25_.*' --description-26 pos26 --regexp-26 'pos26_.*' --description-27 pos27 --regexp-27 'pos27_.*' --description-28 pos28 --regexp-28 'pos28_.*' --description-29 pos29 --regexp-29 'pos29_.*' --description-30 pos30 --regexp-30 'pos30_.*' --description-31 pos31 --regexp-31 'pos31_.*' --description-32 pos32 --regexp-32 'pos32_.*' --description-33 pos0 --regexp-33 'pos0_.*' --replicates 10000 --output ~/Downloads/Pro_spatial.json
```

Results attached. Use https://observablehq.com/@spond/node-level-slatkin-maddison-support to view

Best,
Sergei

[Pro_spatial.json.zip](https://github.com/veg/hyphy/files/6843084/Pro_spatial.json.zip)

**Comment by Xiaojun928** [comment]
Dear Sergei,

Thank you so much for the quick response! I didn't realize that 'pos2*' can also match 'pos22'. 'pos23' etc. 
Your command works well. Thanks a lot!

Best regards,
Xiaojun
