### ISSUE TITLE
MEME results: # branches = 0 & implemented versions hyphy, datamonkey

### ISSUE THREAD

**Issue by franzileo** [veg/hyphy#666]
Dear Developers,

I recently ran a MEME analysis (using the hyphy package) with my own data and for each codon detected to be under positive selection I got the output that 0 branches show evidence for positive selection at this site (# branches in the terminal output).
Then I also ran the analysis as described in the current release tutorial (https://veg.github.io/hyphy-site/tutorials/current-release-tutorial/) (with the h3_trunk.fna file) to check up what results I get here. I got exactly the same results as shown in the screenshot of the tutorial page (same codons, p-values, e.g.) only the # branches was not the same but 0 again for each codon.

How can positive selection be detected at a codon without evidence for positive selection at any branch of the tree? Do you have an idea what could be the reason for the divergent results I get using the tutorial data concerning this matter?

Furthermore, with the same data currently I get different results (number of codons detected to be under positive selection) running MEME with hyphy and the datamonkey web-server. Are there different versions implemented?

Thanks a lot in advance!
Best,
Franziska

**Comment by spond** [comment]
Dear @franzileo,

This is a **regression** bug, meaning I thought I had fixed it but the current version contains it anyhow. It is fixed by the referenced commit. You can click on the commit to see what change was made if you don't want to wait for the next release. It is a simple one line fix to `MEME.bf`.

That said, it is possible to have a site reported as experiencing significant selection, with 0 individual
branches supporting signal for selection. This occurs when the signal for selection is _diffuse_, i.e., there's uncertainty about which branch experienced non-synonymous changes, or no single branch carrying enough substitutions to "light up", or selection occurring along long branches (which are more likely to permit non-synonymous changes).

Best,
Sergei

PS. @stevenweaver : I pushed this to the beta branch; please make sure it makes its way to the next release.
