### ISSUE TITLE
MEME: Branches with evidence for positive selection

### ISSUE THREAD

**Issue by franzileo** [veg/hyphy#669]
Dear developers,

Is it possible (for a single codon detected to be under positive selection) to find out which branches show evidence for positive selection at this codon? When I'm doing the analysis in the datamonkey server I get these extra information for each codon so I wondered whether it is also possible obtaining this information when running the analysis with the hyphy package. I'm aware that these branch specific information should only be used for exploratory purposes instead of actual hypothesis testing. However, these extra information about which branches **might** have experienced positive selection at a codon would help me a lot to set up hypothesis for further testing.

Thanks in advance!
Best,
Franziska

**Comment by spond** [comment]
Dear @franzileo,

This feature is currently not easily accessible, but I will add it to the next release (2.3.7). Currently, MEME will report **how many** (but not which) branches at a given site have high empirical Bayes factors for positive selection. 

You have to be careful though about using these types of inferences to set up hypotheses **on the same data** (e.g. HARKing, see https://www.nature.com/articles/s41562-016-0021). Generally this is not a statistically valid approach, because it will greatly overstate significance. 

Best,
Sergei
