### ISSUE TITLE
Memory usage in creation, computation and optimization of a likelihood function

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#728]
Hey dear team,

I am experiencing memory issues in the creation and computation/optimization of large likelihood functions (that consist of a codon model, such as RELAX, and multiple alignments and trees).

The issue is detectable also when creating a likelihood function with a single alignment and tree, with a simpler, nucleotide model, such as GTR:

```
// process input
alignment_path = io.PromptUserForString("\n>Provide full path to seqData.txt");
tree_path = io.PromptUserForString("\n>Provide full path to unlabeled_tree.txt");
DataSet alignment = ReadDataFile(alignment_path);
DataSetFilter data_filter = CreateFilter (alignment, 1);
fscanf(tree_path, "String", TreeStr);

// generate a model
Freqs = {{0.25},{0.25},{0.25},{0.25}};
RateMatrix = {{*,a*t,b*t,c*t}
			  {a*t,*,d*t,e*t}
			  {b*t,d*t,*,f*t}
			  {c*t,e*t,f*t,*}};
Model model = (RateMatrix, Freqs); 
Tree tree = TreeStr;

// generate a likelihood function
LikelihoodFunction lf = (data_filter, tree);
fprintf(stdout, "lf: ", lf, "\n"); 

// compute the likelihood function
num = io.PromptUser("\n>calling  ComputeLF. Press some number to continue", 0, 1, 10, FALSE);
estimators.ComputeLF (&lf);
num = io.PromptUser("\n>calling  ComputeLF. Press some number to finish", 0, 1, 10, FALSE);

// optimize the likelihood function
num = io.PromptUser("\n>calling  Optimize. Press some number to continue", 0, 1, 10, FALSE);
Optimize (MLEs, lf);
num = io.PromptUser("\n>calling  Optimize. Press some number to finish", 0, 1, 10, FALSE);
```

In the above example, one can detect (using the command `free` between the prompts in the above code) a spike of:
approximately 25 mega when creating the likelihood function. 
approximately 30 mega when computing the log likelihood. 
approximately 100 mega when optimizing. 

When using a codon model and multiple copies of alignments and trees, the creation of the likelihood function causes a spike of around 150 mega, and is time consuming as well. The spike in the computation of the log likelihood and optimization is larger, accordingly.

Is there a way to bypass this issue? I will state that I am using multiple copies of the same codon alignment in my function (since using a reference of the same copy caused an error when I tried to delete the likelihood function, due to multiple attempts to delete the same data filter). 

Additionally, Is there a way to extract the log likelihood value from the likelihood function, rather than computing it again using estimtors.ComputeLF()? I can see it's already computed in the creation of the likelihood function when I print the instance:

```
Log Likelihood =       -4.8e+101;
Tree tree=...
```

Many thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

How many sites are in your alignment? The usages you cite are very high for any sensible size nucleotide alignment. For example, I profiled memory use on the dataset with **3112** sequences and **873** sites under the GTR model, and peak memory use is < 150MB when the function is being optimized. 

Here are some general remarks on how HyPhy manages memory with likelihood functions.

1. HyPhy has two representations of the likelihood function, one of which is "compact", and the other "expanded". The expanded version allocates various caches and storage spaces for transition matrices. Likelihood functions cannot be computed in the compact form. The sizes of the bigger caches are as follows 

```
        // for each partition, indexed "I"
        // patternCount : how many unique site patterns
        // stateSpaceDim : # of characters in the model (4 for nucleotides, etc)
        // categoryCount : number of site-level rate categories for this partition (e.g. 1 if there is no rate variation)
        // iNodeCount : # of internal nodes in the tree
        // leafCount : # of leaf nodes in the tree


        if (leafCount > 1UL) {
            conditionalInternalNodeLikelihoodCaches[i] = new _Parameter [patternCount*stateSpaceDim*iNodeCount*cT->categoryCount];
            branchCaches[i]                            = new _Parameter [2*patternCount*stateSpaceDim*cT->categoryCount];
        }

        siteScalingFactors[i]                          = new _Parameter [patternCount*iNodeCount*cT->categoryCount];
        conditionalTerminalNodeStateFlag[i]            = new long       [patternCount*MAX(2,leafCount)];
```

2. When a likelihood function is created, there is a step that optimizes the order of sites to speed up likelihood calculations; this is done once and scales like the square of `patternCount` (same as above).

More specifically, 

> Additionally, Is there a way to extract the log likelihood value from the likelihood function, rather than computing it again using estimtors.ComputeLF()? I can see it's already computed in the creation of the likelihood function when I print the instance:

When you print the likelihood function it is implicitly computed. `estimators.ComputeLF()` is an expensive way to repeatedly compute likelihood functions, because the function is converted between formats (see "1" above), and this call is meant to only evaluate the function once.

Can you give me more context about how you are using `estimators.ComputeLF()`?

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you Sergei!

This definitely clarifies a lot.

Please find attached the data I used. This is the data from RELAX paper, figure 5A. I believe that based on this data, the simulations reported in the paper were created. The number of codon sites is 21154 and the number of sequences is 50.

I am using estimators.ComputeLF() in order to iteratively compute the likelihood function of my model, given different sets of trees. In each iteration, I generate a new set of trees, create a new likelihood function instance, and compute or optimize the likelihood. In the current implementation, I always use either estimators.ComputeLF() or Optimize() immediately after the creation of the likelihood function.

**In order to reduce running time and memory usage, If wonder if the following possibilities exist:**
1) Is there any way to compute the log likelihood without having its format converted to the expanded form? If not, is there a less expensive way to compute the log likelihood, given that I wish to compute it immediately after the creation of the function?
2) Say I create the likelihood function only once, and change only the tree instances references by the tree names I provide as the components of the function. Would this allow me to alter the data of the same, existing, likelihood function, in each iteration, without having t re-create it?
3) In my likelihood function, I couple each tree with the same codon alignment. When I used the same copy of the alignment in each couple, I received as error in deleting the function (the issue is reproducible with the attached script 'delete_lf'). Is there any way to use the same copy and still be able to delete the likelihood function? Could it potentially reduce the duration of creating and using the function instance?

[unlabeled_tree.txt](https://github.com/veg/hyphy/files/1602743/unlabeled_tree.txt)
[seqData.txt](https://github.com/veg/hyphy/files/1602744/seqData.txt)
[delete_lf.txt](https://github.com/veg/hyphy/files/1602776/delete_lf.txt)

Thanks again!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

I'll see if I can suggest some optimization strategies. To answer your questions

0. Memory usage seems sensible for a long codon alignment, but I will check. 

1. No, the only way to compute the LF is to create an expanded version at the moment. This is because I made the decision that in the vast majority of applications multiple calculations will be done in a row, and the cost of maintaining two separate branches of code to compute the likelihood based on LF representation is not worth the payoff.

2. When you change the tree, HyPhy will have to recreate the likelihood function in general, because the set of model parameters change, cache layout changes, etc. There is no easy way to reuse existing data structures. 

3. This used to be possible, but it could easily lead to fragile code (because changes to the data filter anywhere would have to be propagated to all objects that depend on it). I made the behavior stricter in order to reduce errors. Let me look at your use case and see if I could make some code modifications (for example by automatically cloning data filter structures). The proper solution to this problem is a "tree mixture" model, where it is assumed that the same data filter applies to all trees. I may spend some time implementing it, because it seems like this use case may be generally useful.

Stay tuned for more suggestions on how to speed up your code. I'll profile it. 

Best,
Sergei
