### ISSUE TITLE
RELAX: error processing job

### ISSUE THREAD

**Issue by MareikeJaniak** [veg/hyphy#748]
Good morning,

I'm trying to run RELAX on datamonkey and keep getting an email that something went wrong with my job a few minutes into the run. The output does not list any error message that I can see, it only says that there was an error processing my job. I don't think the issue is because of my file, because I am getting the same issue with a file I have run successfully in the past. 

The links are below: 
http://datamonkey.org/relax/5a787fd0e60ba95fe85c9eab http://datamonkey.org/relax/5a787e93e60ba95fe85c9e87 http://datamonkey.org/relax/5a787dede60ba95fe85c9e64

Thanks!

Best,
Mareike

**Comment by PSC1951** [comment]
This happened to me as well even though I have used the same data file in other analyses here.

**Comment by stevenweaver** [comment]
Dear @MareikeJaniak, 

There seems to be an issue with HyPhy throwing an exception. 

```
Error:
EyxOpJFS.tree_id_0.Node1 is not a valid likelihood function/data set filter/tree topology/tree node in call to SetParameter(

Function call stack
1 : Set parameter MODEL of EyxOpJFS.tree_id_0.Node1 to relax.reference
-------
2 : ExecuteCommands in string "SetParameter (`id`."+model.ApplyModelToTree.list[model.ApplyModelToTree.b]+",MODEL,"+model.ApplyModelToTree.apply_model+")"
-------
3 : model.ApplyModelToTree(lf_components[2*i+1],tree[i],None,model_map[i])
-------
4 : relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE})
-------
```
Please allow me some additional time to investigate the HyPhy source code.

Best,
Steven

**Comment by PSC1951** [comment]
Thank you so much!



> On Feb 5, 2018, at 3:19 PM, Steven Weaver <notifications@github.com> wrote:
> 
> Dear @MareikeJaniak,
> 
> There seems to be an issue with HyPhy throwing an exception.
> 
> Error:
> EyxOpJFS.tree_id_0.Node1 is not a valid likelihood function/data set filter/tree topology/tree node in call to SetParameter(
> 
> Function call stack
> 1 : Set parameter MODEL of EyxOpJFS.tree_id_0.Node1 to relax.reference
> -------
> 2 : ExecuteCommands in string "SetParameter (`id`."+model.ApplyModelToTree.list[model.ApplyModelToTree.b]+",MODEL,"+model.ApplyModelToTree.apply_model+")"
> -------
> 3 : model.ApplyModelToTree(lf_components[2*i+1],tree[i],None,model_map[i])
> -------
> 4 : relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE})
> -------
> 
> Please allow me some additional time to investigate the HyPhy source code.
> 
> Best,
> Steven
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Patrice Showers Corneli
Associate Research Professor
Department of Biology
University of Utah 
Salt Lake City, UT 84112
corneli@biology.utah.edu

**Comment by MareikeJaniak** [comment]
Thanks, Steven!

**Comment by spond** [comment]
Dear @MareikeJaniak and @stevenweaver,

Issue identified, fix in progress. HyPhy (and RELAX) does not handle trees that look like this

```
((...))
```

consistently. In effect, these trees have a root node with a single branch (see image), and at some point HyPhy unroots these trees to look like the second image, but the definition of branch sets is based on the first one. `Node1` is the branch that disappears during this unrooting.

You can solve the issue before the fix is posted simply by editing your tree string to remove the extra set of parentheses at the top level.

Best,
Sergei

**Single root child**

<img width="526" alt="screen shot 2018-02-06 at 1 44 19 pm" src="https://user-images.githubusercontent.com/1018513/35877643-ea63944e-0b43-11e8-883e-df12db113307.png">

**Tree with this branch removed**

<img width="579" alt="screen shot 2018-02-06 at 1 47 16 pm" src="https://user-images.githubusercontent.com/1018513/35877758-438706b4-0b44-11e8-8210-0c9a68cd5326.png">
