### ISSUE TITLE
Problem with sequences from an alignment file

### ISSUE THREAD

**Issue by MarcNiebel** [veg/hyphy#749]
I have 58 sequences which I submitted for a FEL analysis to the online version, however only 52 were analysed. I identified the sequences which were not accepted and ran these separately. However only 4 were accepted. I have changed the header title and also which files to analyse with no success. Any help would be much appreciated. I have attached a file with the problematic sequences. 
[transmitting_couples.txt](https://github.com/veg/hyphy/files/1702489/transmitting_couples.txt)

**Comment by spond** [comment]
Dear @MarcNiebel,

If you have N identical sequences in your alignment, Datamonkey will only retain one for the analysis, and discard the other N-1. This is because identical sequences do not contribute any information to selection analyses, but do increase run time. 

It seems to be that you have exactly this situation, and identical sequences are being filtered out. This behavior is expected and will **not** affect the results of your analysis.

Best,
Sergei

**Comment by MarcNiebel** [comment]
Ok that makes sense. Thanks for the response.
