### ISSUE TITLE
RELAX - a different internal error in alternative model fitting when setting initial values manually

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#774]
Dear HyPhy team,

I am experiencing another internal error from the optimization of the alternative model in RELAX, when setting the initial values for the model manually.

The error is inconsistent (that is, not consistently reproducible in the general case of setting the initial values manually, but is consistently reproducible in the attached instance).

The settings of the initial values are done in the same manner as described in [issue 771](https://github.com/veg/hyphy/issues/771).

The error:

```
Error:
Internal error: Encountered a positive log-likelihood (293373) at evaluation 49867, mode 0, template 0

Function call stack
1 : Optimize storing into, mles, the following likelihood function:likelihoodFunction ;
-------
2 : relax.alternative_model.fit=estimators.FitLF(relax.filter_names,relax.trees,{"0":relax.model_map},relax.general_descriptive.fit,relax.model_object_map,{terms.run_options.retain_lf_object:TRUE})
```

Information to reproduce the issue:
1) The script to reproduce the error: [k_0.5_replicate_0_aln_len_1000.bf.txt](https://github.com/veg/hyphy/files/1828974/k_0.5_replicate_0_aln_len_1000.bf.txt)
2) The input sequence alignment: [simulated_dataset.k_0.5._replicate_0.txt](https://github.com/veg/hyphy/files/1828979/simulated_dataset.k_0.5._replicate_0.txt)
3) The input tree (Test labels are named 'FG'): [labeled_tree.nwk.txt](https://github.com/veg/hyphy/files/1828980/labeled_tree.nwk.txt)
4) The outcome of the execution: 
[terminal_output.txt](https://github.com/veg/hyphy/files/1828985/terminal_output.txt)
[messages.log.txt](https://github.com/veg/hyphy/files/1828986/messages.log.txt)
[errors.log.txt](https://github.com/veg/hyphy/files/1828987/errors.log.txt)

Please let me know if there is anything else I can provide.

Thanks!
Keren

**Comment by spond** [comment]
Dear @halabikeren,

This issue takes a bit of time to unpack, but there are three key observations.

1). The error you see is because the model had a bunch of **local** K parameter that created a combination of large values that led to a numerical overflow in matrix exponentiation, and therefore incorrect LF calculations (this is the reason for the "positive" log likelihood). This is because what `SetParameters` is doing is essentially executing commands like 

```
parameter_name = parameter_value
```

and without the `global` qualifier `parameter_name` becomes a local variable for the rest of the run. 

2). Because you called `SetParameters` **prior** to defining the model (you call it on line 370, and the models are not instantiated until right afterwards), **all** the parameters, including theta_AG, etc, _aux rates etc were initialized as local. In other words you have **undesirable** behavior, when instead of having one set of nucleotide substitution rates per alignment, you have a set of parameters per branch, like in 

```
// repeat for each branch
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.bsrel_mixture_aux_0=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.bsrel_mixture_aux_0:<1;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.bsrel_mixture_aux_1=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.bsrel_mixture_aux_1:<1;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.t=2.686204064526815;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega1=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega1:<1;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega2=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega2:<1;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega3=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.omega3:>1;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.theta_AC=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.theta_AT=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.theta_CG=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.theta_CT=0;
YRoTczNB.tree_id_0.Pseudomonas_aeruginosa.theta_GT=0;
```

It is generally useful to debug issues like this by serializing the likelihood function that has been created using 

```
io.SpoolLF 
```

and inspecting the results.

3. In this particular instance, you should **not** call `SetParameters`, but rather pass them as initial values to 

```
relax.alternative_model.fit =  estimators.FitLF (relax.filter_names,
                                                 relax.trees,
                                                 { "0" : relax.model_map},
                                                 relax.initial_values,
                                                 relax.model_object_map,
                                                 {terms.run_options.retain_lf_object: TRUE});
```

Alternatively, you can call `SetParameters` **after** all the model declarations, i.e. right before the call to ```estimators.FitLF```.

Best,
Sergei

**Comment by halabikeren** [comment]
Thank you, Sergei!

This indeed clarifies a lot. 
I suspect that [issue 754](https://github.com/veg/hyphy/issues/754) is also a result of the same mistaken usage of `parameters.SetValues`, as in that case, printing the information of the likelihood function showed multiple local parameters corresponding to `K` (can be seen in the last email I sent regarding this issue).

Your second suggestion appears to yield the desired affect.

**Concerning the first suggestion of passing the values as initial values:** 
Since I wish to initialize variables which have been constrained prior to the call to `estimators.FitLF`, I expect the initialization to fail on the constrained parameters, due to reasons you have clarified before in [issue 753](https://github.com/veg/hyphy/issues/753). A minor modification to the script from the previous post  can validate this: [k_0.5_replicate_0_aln_len_1000_first_suggestion.bf.txt](https://github.com/veg/hyphy/files/1832836/k_0.5_replicate_0_aln_len_1000_first_suggestion.bf.txt)
The outcome: [first_suggestion_lf_info.txt](https://github.com/veg/hyphy/files/1832838/first_suggestion_lf_info.txt)

**Concerning the second suggestion of calling `SetParameters` after all the model declarations:** 
It appears that when I call `parameters.SetValues` before settings the constraints and after declaring the model parameters, I get the desired outcome.
A minor modification to the script from the previous post  can validate this: [k_0.5_replicate_0_aln_len_1000_second_suggestion.bf.txt](https://github.com/veg/hyphy/files/1832839/k_0.5_replicate_0_aln_len_1000_second_suggestion.bf.txt)
The outcome: [second_suggestion_lf_info.txt](https://github.com/veg/hyphy/files/1832840/second_suggestion_lf_info.txt)

So, I am closing this issue and issue 771.

Many thanks!
Keren
