### ISSUE TITLE
Mean of branch lengths in aBSREL

### ISSUE THREAD

**Issue by avicens** [veg/hyphy#787]
Hi,

Could anybody clarify to me how interpret the branch lengths of a phylogenetic tree yielded by the full adaptive model of aBSREL? 
These branch lengths do not seem to be concordant with those inferred by a ML-based tree (number of substitutions per nucleotide) or a Codeml-based tree (number of nucleotide substitutions per codon).
Running aBSREL with my datasets often yields trees with most of branches very short and a few very long.

Thank you in advance for any help you can provide to me.

**Comment by spond** [comment]
Dear @avicens,

Branch lengths in aBSREL are a little tricky to define because they are over a mixture of models on a per branch basis, and they are quite sensitive to the outliers; e.g. large &omega; values will inflate them quite a bit. Otherwise, they should be the same as other branch lengths: expected substitutions per site per unit time.

Nonetheless, they should be broadly comparable with Codeml or ML based trees, except in cases of strong heterogeneity in selection regimes, like what we described in this [2011 MBE paper](https://www.ncbi.nlm.nih.gov/pubmed/21705379), when significant and important differences arise.

Best,
Sergei

**Comment by avicens** [comment]
Thank you so much for your response Sergei,

I have another question. I want to apply branch-site tests on a single branch of interest but for a collection of ~500 tree. In this case, it is mandatory to perform a correction for multiple testing? I know this has to be done for testing multiple branches in a tree, but not sure for a single branch in multiple trees.

Thanks in advance.
Alberto

**Comment by spond** [comment]
Dear @avicens,

Whether or not you apply multiple test correction really depends on your inference goals. The key difference between testing multiple genes / trees and multiple branches in the same tree is that the latter case applies multiple tests to the same data, whereas the former -- to many independent datasets. That said, if you run 500 tests with p-value 0.05 on 500 neutral datasets, you are still expected to derive ~25 false positive findings. **However**, it the case of aBSREL none of the datasets are likely to be strictly neutral (but rather negatively selected), hence you would expect fewer spurious false positives. Furthermore, because you are testing a single branch, your power to detect selection is going to be somewhat limited, hence a multiple test correction will likely completely wash the power away. Therefore, my standard practice here is to use raw p-values to find genes/trees that may be under selection, and only apply multiple test/FDR correction if you wish to make statements like `at least one gene in family X is subject to episodic positive selection at p <= 0.05`.

Best,
Sergei

**Comment by avicens** [comment]
Thanks a lot, professor!
I will consider the robust significant LRTs (p-adj < 0.01) but probably I also mention those LRTs with p-raw < 0.01.
Best.
Alberto

**Comment by spond** [comment]
Dear @avicens,

I will be very surprised if you find **any** adjusted p-values of <0.01. There's simply not that much power in a single branch selection testing. I would recommend something like FDR of 0.1 - 0.2.

Best,
Sergei
