### ISSUE TITLE
iFEL analysis, HYPHY: dN=1 and p-value equal or similar to 1 for all sites

### ISSUE THREAD

**Issue by vanessacpmcorreia** [veg/hyphy#788]
Hi,
I have been working with very large sequence datasets of different subtypes of influenza neuraminidase (1400 to 3700 sequences) for which I have performed SLAC and FEL analysis. For these same datasets I am now performing iFEL analysis to identify which positive selection is in fact occurring at population level, but for two of them I got very weird results. I got a dN=1 and a p-value equal or similar to 1 for all sites except those conserved. The datasets for which I got this problem are the ones comprising the highest number of sequences (>3200 sequences) but even when performing a downsampling of sequence datasets I got the same results. 
What could be in the basis of these results and how may I overcome this issue?
Thanks!

**Comment by spond** [comment]
Dear @vanessacpmcorreia,

This does seem like abnormal behavior. This may be a reflection of some weird convergence issue (infinite branch lengths). 

I would actually recommend that your run FEL/MEME on internal branches, using the newer version of the analysis that allows you to select a subset of branches to test on. The older version of IFEL is no longer maintained. This may be an easy way to work around the problem. 

Also, instead of SLAC, please use FUBAR: same or greater speed and much better power.

http://hyphy.org/tutorials/current-release-tutorial/#using-hyphy-to-detect-selection

Best,
Sergei

**Comment by vanessacpmcorreia** [comment]
Hi Sergei,
Thank you so much. I will follow your recommendations and then I will let you know if it worked.

Best,
Vanessa
