### ISSUE TITLE
What is the proper way to read GARD results ?

### ISSUE THREAD

**Issue by mhdatefzayed** [veg/hyphy#815]
Dear Sir,

I have questions about interpreting my own GARD results. 
I have a single gene from different plant genera that is aligned based only on its coding sequence (CDS) which is guided by its protein alignment. The gene show duplication events inside some species. I would like to see if these intraspecies duplication events relating to this gene is a result of recombination. I use the alignment of all CDS of this gene from different plant genera to detect if there is any event of recombination by GARD (SITE-TO-SITE RATE VARIATION=NONE, RATE CLASSES=2). Then, I got this result:

GARD found evidence of recombination breakpoints. GARD examined 3289 models in 3:3:20 wallclock time, at a rate of 0.30models per second. The alignment contained 8842 potential breakpoints, translating into a search space of 39094903 models with up to 2 breakpoints, of which 0.01% was explored by the genetic algorithm.

![x1](https://user-images.githubusercontent.com/39471256/42193117-d9e8cc00-7e3a-11e8-9d66-c04c109d525f.png)

As this is my first time to use GARD and also to work on recombination. I would like to ask:

1-	It looks like there is only one confident break point as the position 822. But Looking to LHS p-vlaue looks not significant but RHS p-value is significant. In Significance column, nothing is there. Is my result is a strong evident of recombination or not ? 

2-	I have used the default which is SITE-TO-SITE RATE VARIATION=NONE, RATE CLASSES=2. I do not know should I try Site-to-Site rate variation = Beta-Gamma, rate class = 3 ?

3-	I was trying to use Site-to-Site rate variation = Beta-Gamma, rate class = 3, on the same dataset but it never work or run on GARD, I am afraid this maybe a bug. 

Sorry for basic kind of questions and many thanks for your time and consideration.

**Comment by spond** [comment]
Dear @mhdatefzayed,

Because GARD does not **enforce** different topologies across the breakpoints, sometimes you can get significant improvement in AIC scores simply because your dataset has significant and **heterotachy** across partitions. The result you reported indicates that there is no evidence that using the tree on the right hand side of the first breakpoint to fit the data on the left hand side of the breakpoint results in significantly worse log-likelihood scores. However, there is significant difference in AIC, the evolutionary processes appear different across the breakpoint. This could be, for example, because on one side of the breakpoint you have faster / slower evolution on some branches compared to others. 

I **do** recommend that you rerun your analysis with site rate variation set to "General Discrete" and "3" rate classes, because this model will account for some site-to-site rate variation that could be driving the signal. Let me know what you find.

Best,
Sergei

**Comment by mhdatefzayed** [comment]
Dear Sir,

Thank you so much for your immediate response. 

I tried your recommendation of repeating the analysis with site rate variation set to "General Discrete" and "3" rate classes. However I can see that the job takes too much time in comparison with the job that I run before, it is not finished yet, here is the link

http://datamonkey.org/gard/5b3c3f360ba11710eda29b15

Is this analysis suppose to take that much time ?  

Many thanks for your time and consideration.

**Comment by spond** [comment]
Dear @mhdatefzayed,

The analysis seems to have gotten "stuck"

@stevenweaver or @stephenshank or @kjlevitz : can you please take a look?

Best,
Sergei

**Comment by kjlevitz** [comment]
Dear @mhdatefzayed,

I apologize for the delay, we are still investigating what caused your job to become stuck. This investigation may take some time. In our investigation we have restarted your job twice, one of these jobs has completed the other was started this morning.

Here are the results of the completed first run;
http://datamonkey.org/gard/5b3e15360ba11710eda2bccc

Here is a link to the currently running job that was restarted this morning;
http://datamonkey.org/gard/5b436639cbe0c7233dc4f63a

Please review the completed job from the first link and let me know if the results are satisfactory. 

Thank you,

Kevin Levitz

**Comment by mhdatefzayed** [comment]
Thank you so much @kjlevitz for you help. Many Thanks.
