### ISSUE TITLE
Can not run a batch file because of a version issue

### ISSUE THREAD

**Issue by ATVincent** [veg/hyphy#816]
Hello,

I am trying to run aBSREL with the following batch file:

> inputRedirect = {};
inputRedirect["01"] = "Universal"; //  (1):[Universal] Universal code.
inputRedirect["02"] = "Yes"; //  (1):[Yes] Both alpha and beta vary
inputRedirect["03"] = "No"; 
inputRedirect["04"] = "/home/phylogeny/Desktop/Leptospira/Malaysia_7/hyphy/Analysis/HyPhy_script/test.aln"; 
inputRedirect["05"] = "/home/phylogeny/Desktop/Leptospira/Malaysia_7/hyphy/Analysis/HyPhy_script/tree_node_labels.tre"; 
inputRedirect["06"] = "All"; 
inputRedirect["07"] = ""; 
inputRedirect["08"] = "/home/phylogeny/Desktop/Leptospira/Malaysia_7/hyphy/Analysis/HyPhy_script/results"; 

>ExecuteAFile("/home/phylogeny/Desktop/software/hyphy-bin/lib/hyphy/TemplateBatchFiles/BranchSiteREL.bf", inputRedirect);

However, hyphy refuses to run the batch file because of a version problem:
>Error:Current batch file requires at least version :2.13.20141020 of HyPhy. Please download an updated version from http://www.hyphy.org and try again. in call to RequireVersion(

This is surprising since I download today the latest version (HYPHY 2.3.13.20180706beta (MP) for Linux on x86_64)

Did I missing something?

Thank you very much,

Antony

**Comment by spond** [comment]
Dear @ATVincent,

Until recently, HyPhy was not always using properly formatted semantic versions. Because of that older files, like BranchSiteREL, have non-complaint version strings in ‘RequireVersion’. I’ll review those for the next release. 

In the meantime you have two options

1.  Comment out the ‘RequireVersion’ line from BranchSiteREL. 

2. Use the **current** version of aBSREL, which is in TemplateBatchFiles/SelectionAnalyses/aBSREL.bf

Best, 
Sergei

**Comment by ATVincent** [comment]
Thank you, the option 1 works perfectly.
