### ISSUE TITLE
Conflicting results using REL

### ISSUE THREAD

**Issue by ChariteVirology** [veg/hyphy#834]
Hi,
I was re-analysing some alignments I did some weeks ago and I get different results now for the REL analysis. Was there any update on this method in the last weeks?

Thank you,
Best Anna

**Comment by spond** [comment]
Dear Anna,

Which REL analysis are you referring to and what type of difference are you seeing?

Best,
Sergei

**Comment by ChariteVirology** [comment]
Hi Sergei,
I am referring to the REL pressure analysis in datamonkey. The Bayes factor as well as post. probabilities values are slightly different. I expected them to be exactly the same with the identical dataset.

Best, Anna

**Comment by spond** [comment]
Dear @ChariteVirology,

Because HyPhy (the analytic engine behind Datamonkey) supports parallel execution, using multiple CPUs, there's actually going to be slight run-to-run variation. Essentially this is because floating point operations are neither commutative (`a + b` need not equal `b+a`) nor associative (`(a+b) + c` need not equal `a + (b+c)`). When multiple CPUs work on the same task, the order of some operations in the code is not determined, because the order in which each CPU finishes its task could be quite random. Therefore, you will see variation from run to run. It should not matter much, and if you do observe large changes, this typically implies that the inference error is quite high (e.g. small datasets, low divergence, etc)

Best,
Sergei
