### ISSUE TITLE
aBSREL multiple hypothesis testing across many genes

### ISSUE THREAD

**Issue by jdaane** [veg/hyphy#841]
Hey,

My goal is use aBSREL to identify genes with evidence of positive selection within a single internal branch of a dataset of >10,000 genes from 47 species.  I am unsure how to handle multiple hypothesis correction in this case.  It seems like it is essential and already built into the program if looking at multiple branches with the same gene/alignment. However, it is unclear if it is necessary or even appropriate to apply corrections (bonferroni, fdr, etc.) across the p-values from all 10,000+ genes.

**Comment by spond** [comment]
Dear @jdaane,

Please see https://github.com/veg/hyphy/issues/787 

In your case since you are really testing 10,000+ **independent** hypotheses (since you are using **different** genes and different sequences for testing), multiple testing correction is both somewhat inappropriate and will simply be way too conservative.

Best,
Sergei

**Comment by jdaane** [comment]
Thanks Sergei!
