### ISSUE TITLE
FEL. Confused tree topology

### ISSUE THREAD

**Issue by trilisser** [veg/hyphy#843]
Hello! I try to use the FEL method to calculate dN/dS but it gives me a confused tree topology (wrong relationships between major viruses subtypes). What can I do next, is that serious bias for a dN/dS calculation? 
Regards.

**Comment by spond** [comment]
Dear @trilisser,

Is the topology being inferred by datamonkey or supplied in the alignment file? My suggested solution would be to include the preferred topology in the alignment file. Another suggestion would be to confirm that the alignment does not have unanticipated issues because major topological errors might imply that something got lost in translation, so to speak.

Best,
Sergei

**Comment by trilisser** [comment]
dear Sergei! Thank you for your reply!
The topology is inferred by datamonkey. How can I include the preferred topology in the alignment file?

**Comment by spond** [comment]
Dear @trilisser,

Depends on the file format. For FASTA, you just add the tree string after all the sequence data. For NEXUS, you need to add a TREE block. 

I would also confirm that there are no unanticipated errors in the alignment, especially if you also get long tree branches in the inferred trees.


Best,
Sergei

**Comment by trilisser** [comment]
@spond 
I think is alignment is ok since we get the right topology by the MEGA and the BEAST. For example, if we don't use a bootstrap in the MEGA we get as the same confused topology as in the datamonkey.

Thank you so much for your reply!
Artem
