### ISSUE TITLE
GARD jobs crashed, empty log?

### ISSUE THREAD

**Issue by wadhamite** [veg/hyphy#859]
I've had the same error running two GARD jobs yesterday that I would appreciate some guidance: 5be31d95a431111dcce1f0ce and 5be31dc4a431111dcce1f0f2
"We're sorry, there was an error processing your job"
The log is empty when I download it.
Any idea what has caused this - two many samples in my alignment, ORFs too long...? I used the default GARD settings.

Thanks,
Charlotte

**Comment by stephenshank** [comment]
Dear @wadhamite,

I am unable to reproduce the failure. I've obtained the files corresponding to these two jobs from our server, downloaded them to my local machine, and successfully ran them through Datamonkey with the default settings.

Could you please try once more? If the error persists, please email me the original file at sshank@temple.edu so that I can try to trouble shoot from start to finish.

Best,
Stephen

**Comment by LaMartaC** [comment]
I am having the exact same issue. Did you manage to solve the problem?
Thanks

Marta

**Comment by rdvelazquez** [comment]
Hi @LaMartaC and @wadhamite,

Sorry for the delayed response.

There were stochastic errors with GARD in hyphy version 2.3.14. datamonkey.org has been modified to use an earlier version of HyPhy (version 2.3.11) for GARD analyses. If you try to run your analyses again they should work without issue.

GARD is being revised to address the stochastic errors for the next (2.4) release.

Best,
Ryan
