### ISSUE TITLE
MEDS problem in hyphy-2.3.14

### ISSUE THREAD

**Issue by geofrunz** [veg/hyphy#860]
Dear All,
I've installed hyphy-2.3.14 (HYPHYMP) on my ubuntu 18 distribution.
However, when I try to use this analysis following thee path "Positive Selection" and "(12) Test for Episodic Directional Selection on a set of labeled branches" I get the following error:
Error:
'ClearConstraints(nonsynDIR);' contained syntax errors, possibly a missing semicolon. ''
Check errors.log for details on execution errors.

Apparently this is the only test which doesn't work 
does have anybody experienced a a similar problem and find a solution?
Thank you for any help
Very best regards
Giovanni

**Comment by spond** [comment]
Dear @geofrunz,

Let me take a look and get back to you. Looks like the analysis has gone stale, i.e. it may have contained a syntax error that used to be permitted by the old language parser, but no longer is.

Best,
Sergei

**Comment by srwis** [comment]
Hi @geofrunz,

Turns out this error was a missing semicolon on line 471:
`ClearConstraints(omegaT);`

It is fixed on the develop branch in [this](https://github.com/veg/hyphy/commit/694ab74e866da0dc2a067cd026244afe83347bf4) commit. So you can either try to pull down the develop branch of HyPhy or you can just use this MEDS.bf file instead:
[MEDS.bf.txt](https://github.com/veg/hyphy/files/3070145/MEDS.bf.txt). Just remove the .txt at the end and it should run with 2.3.14.

Best,
Sadie
