### ISSUE TITLE
Analysis with MEME on the command line

### ISSUE THREAD

**Issue by MarcNiebel** [veg/hyphy#885]
Hi,

I am running HYPHY on the command line using a batch command for MEME (HYPHYMP MEME_Script.bf). I have 60 different alignments and was wondering if there is a way to improve the time to completion?

Kind Regards,

Marc

**Comment by rdvelazquez** [comment]
Hi @MarcNiebel. If by "improve the time to completion" you mean automating the analysis (rather than running through the list of arguments manually each time) then I would recommend you write a simple bash script for this task. See https://github.com/veg/hyphy/issues/522 for how to run a HYPHY analysis from a bash script and then just iterate over your 60 different files with a loop (see http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-7.html or any of the other online documentation/tutorials for bash). You can see an example bash script for running meme here: https://github.com/veg/hyphy-gui/blob/master/scripts/meme.sh; you would just replace the `$1` and `$4` with the actual values and then loop over the file paths (`$2` and `$3`) in that script.

if you want each MEME analysis to complete more quickly you could try running them on https://datamonkey.org

Hope this is helpful. Feel free to reach out with any other questions or if you run into issues.

**Comment by MarcNiebel** [comment]
Hi @rdvelazquez
Thanks for the prompt reply. I was not clear in my question. I already have a bash script that iterates through each alignment & tree but the problem I am facing is that it can often takes days to run to completion so I was wondering if there was a way to specify CPUs to be used or parallelisation to improve time to completion. Thanks for your time.

**Comment by spond** [comment]
Dear @MarcNiebel,

MEME uses MPI for parallelization. One multi-core machines (at least Linux and OS X), you can install OpenMPI (if the system doesn't already have an MPI library installed), compile HYPHYMPI, and use multiple processors that way.

@rdvelazquez : do we have a API published for submitting jobs to data monkey programmatically? That would be another solution.

Best,
Sergei

**Comment by MarcNiebel** [comment]
Dear @spond 
Thanks for that information. Will look at getting that installed.

**Comment by rdvelazquez** [comment]
@spond I'm not aware of a published API for submitting jobs to datamonkey programmatically but I can add this to our (long) backlog
