### ISSUE TITLE
interpreting GARD results: p-value differences across breakpoint

### ISSUE THREAD

**Issue by rinikas** [veg/hyphy#895]
I would like some clarification on how to interpret my GARD results. 

I ran GARD a Drosophila gene underwent duplication in some lineages, and I included both the orthologs across Drosophila as well as the paralogs within a lineage. I am interested in determining if there is evidence for recombination within this locus in lineages where this gene duplicated.

I ran GARD using site-to-site rate variation = general discrete and rate classes = 3.  I got the following result: 
"GARD found evidence of recombination breakpoints. GARD examined 5794 models in 27:46 wallclock time, at a rate of 3.48 models per second. The alignment contained 872 potential breakpoints, translating into a search space of 110509868 models with up to 3 breakpoints, of which 0.01% was explored by the genetic algorithm."

I am confused as to how GARD found evidence for recombination but the RHS p-value is not significant. 

Based on the explanation provided with the topological incongruence report, I think this means that there is rate variation but the breakpoint does not show evidence to be a true topological incongruence. Am I appropriately interpreting the GARD output?

Are there changes I should make to my input file or when I run the analysis in the site-to-site variation/rate class that can help disambiguate the result?

Thanks for your help,
Rini

![nnk-with-linker-gard-results-subsection](https://user-images.githubusercontent.com/47258662/52148183-c9058500-261d-11e9-9b6f-16cbf2939a07.png)

**Comment by rdvelazquez** [comment]
@rinikas Sorry for the long delay in getting back to you. The Kishino Hasegawa topological incongruence table has been a point of confusion for a number of people, myself included, and we are considering doing away with the table in the newer version of GARD. 

You may find [this discussion](https://github.com/veg/datamonkey-js/issues/188) somewhat helpful in understanding how to interpret the results, specifically this excerpt:

> The highlighted text and Kishino Hasegawa results table do seem to be in conflict however they are describing related but different things.
The highlighted text: Is describing the results of testing the best break point model to look at how much of the improvement in c-AIC can be attributed to topological differences between partitions rather than branch lengths. We fit a model on the partitioned data letting the branch lengths vary between partitions but keep the tree topology constant. We then compare this c-AIC with the c-AIC for the best model (letting both branch lengths and topology vary)
The Kishino Hasegawa table: is evaluating single break point models (a separate model for each break point) and looking at how much support is provided for that break point by the partition on the left and the partition on the right.
@spond may be able to speak to this more, but from my understanding of what GARD is doing, the Kishino Hasegawa table is not very informative because partitions and not breakpoints are the unit of recombination... As your example results file nicely illustrates, there are instances where two individual break points may not have strong support however the three partitions which these two break points form do have strong support.

Thanks for reaching out with your question; please reach out if you have additional questions or issues.
