### ISSUE TITLE
jobs terminating today 31 May

### ISSUE THREAD

**Issue by harturchin** [veg/hyphy#971]
Hi Steven,

I saw that the datamonkey job queue had filled up and then was cleared (I guess by cancelling jobs)? I tried to restart my jobs (GARD, MEME, aBSREL) but they are terminating with the little pink message box:

"We're sorry, there was an error processing your job. Please try again, or visit our GitHub issues and create an issue if the issue persists."

I thought it must be my data file so I tried downloading & running the flu.fasta example file. That input file generates the same error message (in MEME). Thanks for investigating.

Cheers!
Mike

**Comment by stephenshank** [comment]
Dear @harturchin,

Thanks for raising this issue! I've placed a warning banner on the main site for the time being.

@rdvelazquez @stevenweaver A few bread crumbs from my cursory investigation... when I try to run the tests on `datamonkey-js-server`, I get

```
stderr=/home/datamonkey/datamonkey-js-server/staging/app/absrel/../../.hyphy/HYPHYMP: error while loading shared libraries: libamdlibm.so: cannot open shared object file: No such file or directory
```

I tried rebuilding HyPhy with `make install`, but cmake appears to have been updated system wide to 3.14 which is a relatively newer release and now throws an error.

I will investigate this further tomorrow.

Best,
Stephen

**Comment by spond** [comment]
Dear @stephenshank and @rdvelazquez,

`libamdlibm.so` is a part of the `aocc` module (AMD specific CLANG compiler). I think if you load the module, the issue my go away.

Best,
Sergei

**Comment by stephenshank** [comment]
Dear @spond,

I did try this, and this is what prompted the cmake issue I referenced.

Why the HyPhy executable would suddenly stop working is beyond me...

Best
Stephen

**Comment by stephenshank** [comment]
Very strange issue. First, I am not sure that redis is configured to startup properly as I could not ping it from datamonkey-main. I now have it running in a tmux session where I can ping from both locations that consume it.

Second, after making this change I ran about 10 jobs earlier, all of which succeeded. To the best of my knowledge, I did not touch anything, but now all my jobs error out and the same error regarding `libamdlibm` shows up in the logs.

When I try the command that datamonkey-js-server tries to run to invoke HyPhy, it runs successfully with or without the aocc module loaded, without complaining about finding the shared object file.

**Comment by rdvelazquez** [comment]
@stephenshank Thanks for looking into this!

I'm not sure what is going on but there are a few things that are making me believe it is more an issue with our cluster (torque, maui, qsub, etc.) than with datamonkey specific processes.
1. Brittany has also had intermittent issues trying to run HyPhy jobs through the queue, sometimes they work sometimes they fail. The failing jobs have the same error message we are seeing in the logs: `HYPHYMP: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory`
2. When we completely cleared the queue yesterday afternoon and then restarted torque and maui, I was able to run 20 datamonkey jobs and only got one error (the other 19 ran to completion). The queue was empty at that point except for those datamonkey jobs.
3.  Prior to clearing the queue yesterday afternoon, most of the datamonkey jobs that we submitted failed however, some of them passed. 

Based on the above, one possible explanation could be something like:
- When the system restarted yesterday morning some of the nodes only came partially back online
- These nodes that only came partially back online are shown as available to submit jobs to however they are missing something, or are incorrectly configured, such that HyPhy jobs immediately fail when submitted to them.
- This could explain why some jobs worked and some errored (it just depended if it was submitted to a "good" or "bad" node)
- This could also explain why most the datamonkey jobs worked when the queue was empty (the jobs were being submitted to available nodes which happened to be the good ones) but why most the datamonkey jobs errored when the queue was full (with a full queue all the "good" nodes were full of running jobs but the "bad" nodes had open processors because the jobs that were submitted to them immediately failed).

I've tried to find something to confirm this suspicion as well as to determine which nodes are "bad" and what to do to fix them but as yet I haven't found anything concrete. The following commands have been helpful `beostatus -c`, `diagnose -n` (only works for me when I'm the root user for some reason), `pbsnodes`; and the files in `/var/log/beowulf/`, `/var/spool/torque/mom_logs/`, and `/etc/beowulf/conf.d/` have also been helpful.

**Comment by rdvelazquez** [comment]
In an effort to try and see which, if any, nodes may be behaving differently and potentially causing the issue, I `bpsh`ed HYPHY jobs to each node individually. `SLAC` jobs ran fine on all the nodes except for node 16; the error message when trying to run `SLAC` jobs on node 16 was the same libomp error as seen previously. I attempted to take node 16 out of the queue by removing the `batch` and `datamonkey` designation from the node in `/var/spool/torque/server_priv/nodes` and restarting torque. I tested 10 `SLAC` jobs on datamonkey, 9 ran fine 1 failed... I'll keep the maintenance banner up on the site for now and then we can look at it again on Monday morning.

**Comment by rdvelazquez** [comment]
The site is now fully functional. Node 16 was the problem and a simple restart of the node has fixed the issue. Thank you @harturchin for posting the issue! Please let us know if you have any issues again. Sorry for any inconvenience that this down time has caused.
Best,
Ryan

**Comment by harturchin** [comment]
Great thanks Ryan!
