### ISSUE TITLE
Running hyphy using Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by RANP10** [veg/hyphy#977]
Dear all
I am trying to run the file BranchSites_delta_alt.bf (https://github.com/JoeThorntonLab/MNM_SelectionTests) under Ubuntu 18.04 LTS Windows. Here is the code:

[hyphy_error_20190607.txt](https://github.com/veg/hyphy/files/3267427/hyphy_error_20190607.txt)

As you can see, I tested if the HyPhy build was successful and if the library files were in the right place. 

I apologize if the issue is too basic, I have never used the command line to run any Hyphy script.

Best

Ricardo

**Comment by stevenweaver** [comment]
Dear @RANP10, 
This is indeed a bug. Notice the lines at the top of your error log. 

```
Original path: '../../hyphy/res/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'.
Expanded path: '/home/hyphy/res/TemplateBatchFiles/TemplateModels/chooseGeneticCode.def'
```

HyPhy is incorrectly setting the `LIBPATH` to be two directories up instead of one. To circumvent the issue until it is addressed, make sure to use `LIBPATH=`pwd`/res` as in the command you invoked later in your log. 

```
./HYPHYMP LIBPATH=`pwd`/res 
```
Best,
Steven
