### ISSUE TITLE
Extremely slow GARD runs in HYPHY v2.5.0 

### ISSUE THREAD

**Issue by NatJWalker-Hale** [veg/hyphy#987]
Hi guys, 

I am running GARD analyses with HYPHYMPI v2.5.0. Analyses which previously ran very quickly in v2.3 and v2.4 are now taking multiple days with no sign of completion. I wondered if this expected of any changes you'd implemented, or if there was something I could do to speed it up? 

Even using `mpirun -np 32` is still very slow. 

The dataset is 13 sequences of ~3,200 bp. 

Thanks, 

Nat

**Comment by rdvelazquez** [comment]
Hi @NatJWalker-Hale,

This seems unusual. Could you provide some additional information to help us look into it? Any of the following would be helpful: System specs (os, processors, RAM, etc.), GARD parameters and dataset. Feel free to email me at ryan.velazquez0001@temple.edu.

Best,
Ryan

**Comment by NatJWalker-Hale** [comment]
Hi @rdvelazquez, 

I've emailed you the extra info as well as the dataset. 

Thanks, 

Nat

**Comment by rdvelazquez** [comment]
@NatJWalker-Hale The issue has been fixed in the develop branch (https://github.com/veg/hyphy/commit/ad115895eba893a83e9230c6c7c70fa27465a9cd). The mpi queue was being terminated after each model was evaluated rather than after each generation of the genetic algorithm; mistaken placement of a closing `}` prevented any work form being parallelized. 

Thank you for letting us know about the issue!

**Comment by NatJWalker-Hale** [comment]
@rdvelazquez thanks for the prompt follow up! I'll move to the development branch now. 

Thanks, 

Nat
