### ISSUE TITLE
Select branches for aBSREL and BUSTED 2.5

### ISSUE THREAD

**Issue by henri-05** [veg/hyphy#992]
Hello, 

I want to test a subset of a tree labeled with {Foreground} with BUSTED and aBSREL. In previous versions that was no problem. With the new version I do not know how to specify branches in both interactive mode and in command line argument. 
In the command line argument for RELAX I give "path/to/treefile" "Foreground" as arguments and this works fine.
In interactive mode I am not asked which branches I want to test and "branches –> All" shows up automatically. 

Thank you for your help!
Henrietta

**Comment by stephenshank** [comment]
Dear @henri-05,

You can execute `hyphy absrel --help` to get a description of how to write various command line invocations. With the following tree saved in `CD2-Foreground.new`:

```
((((Pig:0.147969,Cow:0.213430):0.085099,Horse:0.165787,Cat:0.264806):0.058611,((RhMonkey{Foreground}:0.002015,Baboon{Foreground}:0.003108){Foreground}:0.022733,(Human{Foreground}:0.004349,Chimp{Foreground}:0.000799){Foreground}:0.011873){Foreground}:0.101856){Foreground}:0.340802,Rat:0.050958,Mouse:0.097950);
```

I invoked HyPhy 2.5.0's aBSREL method to select the branches labeled as `Foreground` with

```
hyphy absrel --alignment CD2.fasta  --tree CD2-Foreground.new --branches Foreground
```

and do indeed see in the output:

```
### * Selected 8 branches for testing: `RhMonkey, Baboon, Node9, Human, Chimp, Node12, Node8, Node1`
```

which leads me to believe that command line interface has picked up this intent. Note the `{Foreground}` annotation in the Newick string that designates a given node as part of this set, and that adding the `--branches Foreground` flag is crucial since the CLI will not specify this on its own.

Regarding your issue with interactive mode, I indeed had a similar experience. We would greatly appreciate you keeping this issue open until this is resolved... in case others experience the same issue, and as a reminder to us to fix it.

Hope this was helpful, and do let us know if you encounter any additional issues!

Best,
Stephen

**Comment by henri-05** [comment]
Dear @stephenshank , 

Thanks for your help! 

I previously invoked HyPhy with a command that looked like this: 
HYPHYMP LIBPATH=/hyphy-2.5.0/res/ /hyphy-2.5.0/res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf "path/to/alignment" "path/to/species_tree.txt"

I tried your version, inserted the LIBPATH and everything works again. 

Best, 
Henrietta
