### ISSUE TITLE
Three questions regarding RELAX

### ISSUE THREAD

**Issue by kmeusemann** [veg/hyphy#994]
Hi alll,

thanks again for your great help in the past.

Three (rather urgent) questions:
1) When I have in my dataset actually 3 groups - (and define then: group1, group1, background), and since RELAX can test only two groups: would you recommend e.g. to test group 1 against gr2+background and group2 against gr1+background, or can RELAX also handle more than 3 groups? (This i do additionally to single species specify as test against all others since my datasets are quite small in terms of species)
2) does RELAX also consider columns with gaps (not only gaps but some) or are only those positions analysed internally with no gaps (=maximal overlap) for all? incl. species?
3) any recommendation if I have a supermatrix that i want to analyse with is quite big (maybe 500000 sites) - on runtime/performance, would it maybe better here to heavily reduce the dataset (include only codons available for all species)?

Many thanks Karen

**Comment by spond** [comment]
Dear @kmeusemann,

1. The current version of RELAX (in v2.5) allows you to perform group tests, i.e. consider more than 2 groups at once. In this situation, the RELAX test compares whether or not **K** (the intensification/relaxation parameter) is different between the multiple groups, with one of the **K** values set to one -- for the reference group. 

2. RELAX considers all alignment columns. Gaps are treated as missing data.

3. If by supermatrix you mean a concatenated alignment with multiple genes, I would advise **against** running RELAX on it. In addition to becoming slow, you are also likely to run into fairly severe model violations, since it is highly unlikely that all the genes share the same selective parameters, and this would be *assumed* by RELAX. Perhaps a better alternative is to run individual genes through RELAX and then perform post-processing.

Best,
Sergei

**Comment by kmeusemann** [comment]
Dear Sergej,

thanks for the fast reply :). 

1) 2.5 sounds very promising i will try this i thin as well. Is in the manual an example how to specify this in the command (I guess groupo one labeled, group 2 labeled and the remaining ones not in the tree and then calling the 2 labeled groups?
2) thanks for the info!
3) yes sounds very plausible of course. I considered to do something as done in Wertheim (empirical dataset 1) since they also used a concatenated alignment -(see Fig. 6) -  but maybe I misunderstood something and it was run then on all single alignments of the 69 single copy genes, or was above concerns at that time not raised yet?

Many thanks and best, Karen
