### ISSUE TITLE
BUSTED positively selected sites - assumptions and output

### ISSUE THREAD

**Issue by Conny8** [veg/hyphy#999]
Hi there, we have used BUSTED to infer positive selection on our foreground branches and we have 2 questions.

1.) We detected positive selection in several genes. In these genes, does BUSTED assume the foreground branches to have the identical amino acid at a given position that differs from the background branches (scenario A) OR can the foreground branches have different amino acids that all differ from the background (scenario B)? For example, scenario A) at position 2 of the alignment all foreground branches have Leucin and the background branches have either Asp or Cys. Scenario B) at position 2, the foreground branches have either Leu or Lys, while the background has Asp or Cys.

2.) BUSTED explores which individual sites may have been subject to selection. Where in the output do I find these positions? We used hyphy from the command line and the .out file doesn't provide this information.

Thanks a lot!
Conny

**Comment by srwis** [comment]
Hi Conny,

1) BUSTED will use the sequence information from the given partitions, so in this case B is the more correct way of thinking about it. If the background branches have Leu or Lys at position two then that is the information BUSTED will use. 

2) Can you locate a BUSTED.json file? There should be one that is input_name.BUSTED.json by default. Within that file, you'll find Evidence Ratios for each site for both the constrained and unconstrained models. Please note that: 

> BUSTED additionally calculates "Evidence Ratios" (ERs) for each site. The ER gives the likelihood ratio (reported on a log-scale) that the alternative model was a better fit to the data compared to the null model. The ER for each site thus provides descriptive information about whether a given site could have evolved under positive selection. The ERs should not be interpreted as statistical evidence for positive selection at individual sites (instead, methods like MEME, FEL, or FUBAR should be used for detecting selection at individual sites). (http://www.hyphy.org/methods/selection-methods/)

Best, 
Sadie

**Comment by spond** [comment]
Dear @Conny8,

To add to @srwis, you can view the results by loading the JSON into vision.hyphy.org/BUSTED and view the evidence ratios. 

Also, in response to your point 1: BUSTED estimates substitution rates, so it is informed by variation in FG, and what happens in BG is best thought of nuisance parameters -- i.e., something you fit to make the model work, but don't care about. Scenario 1 you describe is unlikely to contribute to the selection signal much, because there is no variation in FG branches; sites like that would add to **whole tree** selection analyses, but **not** to partitioned analyses. The best signal would likely derive from sites where FG branches have **multiple** amino-acids, without much consideration given to what happens in BG.

Best,
Sergei
